(function(CF){
  'use strict';
  const S=CF.S,L=CF.L,E=CF.esc,Q='P-O-PR-01',D='P-O-PR-02',ROOT='/ops/pledge-reviews';
  const status={pending:['Pending review','待审核','warn'],approved:['Approved','通过','ok'],rejected:['Rejected','驳回','danger'],withdrawn:['Withdrawn','已撤回','gray'],timeout:['Pledge failed · review timeout','质押失败（审核超时）','danger']};
  const follows={none:['Not initiated','未发起'],ready:['Awaiting deposit confirmation','待确认入池'],invalid:['Pre-check invalidated','复核作废'],expired:['Expired before initiation','未发起已过有效期'],processing:['Executing','执行中'],success:['Execution succeeded','执行成功'],failed:['Execution failed','执行失败'],verify:['Result under verification','结果待核实'],difference:['Reconciliation discrepancy','对账差异']};
  const categories=[['Ownership or entity in question','代币归属或主体存疑'],['Underlying receivable issue','底层应收账款存在问题'],['Token does not match project','代币与目标项目不匹配'],['Incomplete or inconsistent materials','申请材料不完整或不一致'],['Other','其他']];
  const fDefault=()=>({status:'pending',owner:'',project:'',type:'',from:'',to:'',q:'',follow:''});
  let seed=CF.pledgeSeed();
  const A={rows:seed.rows,now:seed.now,clock:Date.now(),filter:fDefault(),editFilter:fDefault(),page:1,sort:'submitted',dir:1,
    filtersOpen:false,tab:'overview',role:'review',response:'success',upload:'success',preview:'success',view:'default',draft:null,busy:false,error:'',selected:null,events:[],epoch:0};
  let routeKey=null,restoreContext=false;
  const positions=new Map();
  const now=()=>A.now+(Date.now()-A.clock),txt=x=>Array.isArray(x)?L(x[0],x[1]):x;
  const time=t=>t?CF.fmtTime(t):'—',money=v=>v==null?L('To be verified','待核实'):CF.fmtAmt(v)+' USD';
  const owner=r=>L('Demo Asset '+r.owner,'示例资产企业 '+r.owner),project=r=>L('Demo project '+r.project,'示例融资项目 '+r.project);
  const b=(en,zh,act,value='',cls='',disabled=false)=>`<button type="button" class="btn ${cls}" data-act="pr-${act}" data-v="${E(value)}" ${disabled?'disabled':''}>${L(en,zh)}</button>`;
  const link=(en,zh,act,value)=>act==='view'?`<a class="actlink" href="#${E(detailRoute(value,'overview',S.page===D?A.selected:''))}" data-act="pr-view" data-v="${E(value)}">${L(en,zh)}</a>`:`<button type="button" class="actlink" data-act="pr-${act}" data-v="${E(value)}">${L(en,zh)}</button>`;
  const badge=r=>CF.tag(status[r.status][2],txt(status[r.status]));
  const field=(label,html)=>`<div class="field"><label for="${(html.match(/id="([^"]+)/)||[])[1]||''}">${label}</label>${html}</div>`;
  const input=(id,v,type='text')=>`<input class="inp" id="${id}" type="${type}" value="${E(v)}">`;
  const select=(id,value,options)=>`<select class="inp" id="${id}">${options.map(([v,label])=>`<option value="${E(v)}" ${v===value?'selected':''}>${E(label)}</option>`).join('')}</select>`;
  const note=(s,type='')=>CF.note(type,s);
  const error=()=>A.error?`<p class="pr-error" role="alert">${E(txt(A.error))}</p>`:'';
  const kv=items=>`<dl class="pr-kv">${items.map(([label,value,wide])=>`<div ${wide?'class="pr-wide"':''}><dt>${label}</dt><dd>${value??'—'}</dd></div>`).join('')}</dl>`;
  const section=(en,zh,html)=>`<section class="card pr-section"><h2 class="pr-h2">${L(en,zh)}</h2>${html}</section>`;
  const canRead=()=>['review','read'].includes(A.role)&&A.view!=='denied';
  const row=()=>A.rows.find(r=>r.id===A.selected);
  const canWrite=r=>canRead()&&A.role==='review'&&r?.status==='pending'&&now()<r.deadline&&A.uncertain?.id!==r.id;
  const duration=ms=>{const m=Math.max(0,Math.floor(ms/60000));return m<60?`${m} ${L('min','分钟')}`:m<1440?`${Math.floor(m/60)} ${L('h','小时')}`:`${Math.floor(m/1440)} ${L('d','天')} ${Math.floor(m%1440/60)} ${L('h','小时')}`;};
  function event(r,title,text='',actor=['System','系统']){r.events.unshift({at:now(),title,text,actor});}
  function expire(){A.rows.forEach(r=>{if(r.status==='pending'&&now()>=r.deadline){r.status='timeout';r.ended=r.deadline;r.events.unshift({at:r.deadline,title:['Review timed out','审核超时'],actor:['System','系统'],text:['No review completed within 48 hours. Application hold released; no execution fees.','48 小时未完成审核，申请占用已释放，本次未执行、零费用。']});A.events.push({id:r.id,event:'timeout'});}});}
  function params(){return new URLSearchParams({...A.filter,page:String(A.page),sort:A.sort,dir:String(A.dir)});}
  function queueRoute(){return ROOT+'?'+params();}
  function detailRoute(id,tab='overview',source=''){
    const p=params();p.set('id',id);p.set('tab',tab);if(source&&source!==id)p.set('source',source);return ROOT+'/detail?'+p;
  }
  function remember(){
    const el=document.activeElement;
    positions.set(location.hash,{y:window.scrollY,act:el?.dataset.act,value:el?.dataset.v});
  }
  function syncContext(){
    if(routeKey===location.hash)return;
    routeKey=location.hash;const p=new URLSearchParams(location.hash.split('?')[1]||'');
    const f=fDefault();for(const k of Object.keys(f))if(p.has(k))f[k]=p.get(k);
    if(f.status&&!status[f.status])f.status='pending';if(f.follow&&!follows[f.follow])f.follow='';
    for(const k of ['from','to'])if(!/^\d{4}-\d{2}-\d{2}$/.test(f[k]))f[k]='';
    A.filter=f;A.editFilter={...f};A.page=Math.max(1,parseInt(p.get('page'),10)||1);
    A.sort=['submitted','waiting','value','deadline'].includes(p.get('sort'))?p.get('sort'):'submitted';A.dir=p.get('dir')==='-1'?-1:1;
    A.selected=p.get('id');A.tab=['overview','related','activity'].includes(p.get('tab'))?p.get('tab'):'overview';
    A.source=p.get('source');if(!A.rows.some(r=>r.id===A.source)||A.source===A.selected)A.source='';
  }
  function saveContext(){
    const next=S.page===D?detailRoute(A.selected,A.tab,A.source):queueRoute();
    history.replaceState(null,'','#'+next);routeKey=location.hash;
  }
  function navigateRoute(route){remember();A.epoch++;A.busy=false;A.draft=null;A.error='';S.layer=null;A.view='default';location.hash='#'+route;}
  function visit(id){
    const target=id?detailRoute(id,'overview',S.page===D?A.selected:''):queueRoute();
    if(A.draft&&(A.draft.files.length||A.draft.reason||A.draft.remark)){A.next=target;open('discard');return;}
    navigateRoute(target);
  }
  function navigate(id){navigateRoute(id?detailRoute(id):queueRoute());}
  function restoreView(){
    if(!restoreContext)return;restoreContext=false;
    requestAnimationFrame(()=>{
      if(S.layer)return;
      const saved=positions.get(location.hash);
      if(saved){window.scrollTo(0,saved.y);const target=[...document.querySelectorAll('[data-act]')].find(el=>el.dataset.act===saved.act&&el.dataset.v===saved.value);if(target)target.focus({preventScroll:true});else document.getElementById('pr-f-q')?.focus({preventScroll:true});}
      else window.scrollTo(0,0);
    });
  }
  function open(key){CF.openLayer('modal','pr-'+key);}
  function identity(r){return `<div class="pr-confirm">${E(r.id)} · ${E(r.token)}<span class="pr-meta">${E(r.batch)} · ${E(project(r))}</span></div>`;}
  function deny(){A.error=['This action is unavailable with the current account, permissions or record status.','当前账号、权限或记录状态不允许此操作。'];A.busy=false;A.draft=null;S.layer=null;CF.render();CF.toast(txt(A.error));}
  function filtered(ignoreState=false){const f=A.filter;return A.rows.filter(r=>(!f.owner||r.owner===f.owner)&&(!f.project||r.project===f.project)&&(!f.type||r.type===f.type)&&(!f.from||r.submitted>=Date.parse(f.from+'T00:00:00'))&&(!f.to||r.submitted<new Date(new Date(f.to+'T00:00:00').setDate(new Date(f.to+'T00:00:00').getDate()+1)).getTime())&&(!f.q||[r.id,r.batch,r.token,owner(r)].join(' ').toLowerCase().includes(f.q.trim().toLowerCase()))&&(ignoreState||((!f.status||r.status===f.status)&&(!f.follow||r.follow===f.follow))));}
  function filters(){const f=A.editFilter,applied=A.filter;
    const extra=['owner','project','type','from','to','follow'],count=extra.filter(k=>applied[k]).length;
    const labels={owner:L('Asset holder','资产方'),project:L('Project','项目'),type:L('Application type','申请类型'),from:L('From','起始日期'),to:L('Through','结束日期'),follow:L('Follow-up','后续情况')};
    const values={owner:applied.owner?owner({owner:applied.owner}):'',project:applied.project?project({project:applied.project}):'',type:applied.type==='first'?L('Initial pledge','建池首笔'):L('Additional pledge','追加'),follow:applied.follow?txt(follows[applied.follow]):''};
    return `<form id="pr-filter-form" class="pr-filter-wrap"><div class="pr-filter-bar">${field(L('Search applications','搜索申请'),`<input class="inp" id="pr-f-q" value="${E(f.q)}" placeholder="${L('Application, token, batch or company','单笔、代币、批次或企业')}">`)}${field(L('Review status','审核状态'),select('pr-f-status',f.status,[['',L('All','全部')],...Object.entries(status).map(([k,v])=>[k,txt(v)])]))}<div class="pr-actions"><button type="button" class="btn" data-act="pr-filters" aria-expanded="${A.filtersOpen}" aria-controls="pr-advanced">${L('Filters','筛选条件')}${count?' ('+count+')':''} <span aria-hidden="true">${A.filtersOpen?'⌃':'⌄'}</span></button>${b('Reset','重置','reset')}<button type="submit" class="btn primary">${L('Search','查询')}</button></div></div>
      <div id="pr-advanced" class="pr-filters" ${A.filtersOpen?'':'hidden'}>${field(labels.owner,select('pr-f-owner',f.owner,[['',L('All','全部')],['A',L('Demo Asset A','示例资产企业 A')],['B',L('Demo Asset B','示例资产企业 B')]]))}${field(labels.project,select('pr-f-project',f.project,[['',L('All','全部')],['01',L('Demo project 01','示例融资项目 01')],['02',L('Demo project 02','示例融资项目 02')]]))}${field(labels.type,select('pr-f-type',f.type,[['',L('All','全部')],['first',L('Initial pledge','建池首笔')],['add',L('Additional pledge','追加')]]))}${field(L('Submitted from','提交开始日期'),input('pr-f-from',f.from,'date'))}${field(L('Submitted through','提交结束日期'),input('pr-f-to',f.to,'date'))}${field(labels.follow,select('pr-f-follow',f.follow,[['',L('All','全部')],...Object.entries(follows).filter(([k])=>k!=='none').map(([k,v])=>[k,txt(v)])]))}</div>
      ${count?`<div class="pr-applied" aria-label="${L('Applied filters','已应用筛选')}">${extra.filter(k=>applied[k]).map(k=>CF.tag('gray',E(labels[k]+': '+(values[k]||applied[k])))).join('')}</div>`:''}</form>`;
  }
  function sortButton(k,en,zh){return `<button data-act="pr-sort" data-v="${k}">${L(en,zh)} ${A.sort===k?(A.dir===1?'↑':'↓'):'↕'}</button>`;}
  function queue(){
    const stats=filtered(true),start=new Date(now());start.setHours(0,0,0,0);start.setDate(start.getDate()-6);
    const counts=[stats.filter(r=>r.status==='pending').length,stats.filter(r=>r.status==='timeout').length,stats.filter(r=>['approved','rejected'].includes(r.status)&&r.decisionAt>=start.getTime()).length];
    const state=A.view==='default'?null:surface();
    const metrics=`<div class="pr-metrics">${[['Pending review','待审核'],['Review timeout','质押失败（审核超时）'],['Reviewed · last 7 calendar days','近 7 个自然日人工审结']].map((x,i)=>`<div class="card pr-metric"><span>${txt(x)}</span><strong>${['loading','error'].includes(A.view)?'—':A.view==='empty'?0:counts[i]}</strong><span class="pr-meta">${L('applications','笔')}</span></div>`).join('')}</div><p class="pr-meta">${L('Summary uses company, project, type, submission dates and keyword filters. Status filters do not change this summary.','统计应用资产方、项目、类型、提交时间及关键词条件，不受审核状态和后续情况筛选影响。')}</p>`;
    let found=filtered();found.sort((a,c)=>{let av=A.sort==='waiting'?(a.decisionAt||a.ended||now())-a.submitted:a[A.sort],cv=A.sort==='waiting'?(c.decisionAt||c.ended||now())-c.submitted:c[A.sort];return av==null?1:cv==null?-1:(av-cv)*A.dir||a.id.localeCompare(c.id);});
    const pages=Math.max(1,Math.ceil(found.length/CF.PAGE_SIZE));if(A.page>pages){A.page=pages;A.error=['The previous page is empty; showing the last available page.','原页已无记录，已返回最后有效页。'];}
    let table=state||(!found.length?CF.empty(L('No applications found','暂无符合条件的申请'),L('Change the filters or return to pending reviews.','调整筛选条件，或返回待审核队列。'),b('Reset filters','重置筛选','reset')):`<div class="tablewrap"><table class="tbl pr-table pr-queue-table"><thead><tr><th>${L('Application / token','单笔 / 代币')}</th><th>${L('Asset holder','资产方')}</th><th>${L('Project','项目')}</th><th aria-sort="${A.sort==='value'?(A.dir===1?'ascending':'descending'):'none'}">${sortButton('value','Value (USD)','价值（USD）')}</th><th aria-sort="${A.sort==='deadline'?(A.dir===1?'ascending':'descending'):'none'}">${sortButton('deadline','Review deadline','审核截止')}</th><th>${L('Review status','审核状态')}</th><th class="col-act">${L('Action','操作')}</th></tr></thead><tbody>${found.slice((A.page-1)*CF.PAGE_SIZE,A.page*CF.PAGE_SIZE).map(r=>`<tr><td><strong class="mono">${r.id}</strong><span class="pr-meta mono">${r.token}</span></td><td>${E(owner(r))}</td><td>${E(project(r))}</td><td class="pr-num mono">${r.value==null?L('Unknown','待核实'):CF.fmtAmt(r.value)}</td><td>${time(r.deadline)}</td><td>${badge(r)}</td><td class="col-act">${link('View','查看','view',r.id)}</td></tr>`).join('')}</tbody></table></div><div class="pager"><span class="total">${L('Total','共')} ${found.length} ${L('applications','笔')} · ${CF.PAGE_SIZE} ${L('per page','笔／页')}</span>${b('Previous','上一页','page',A.page-1,'sm',A.page===1)}<span>${A.page} / ${pages}</span>${b('Next','下一页','page',A.page+1,'sm',A.page===pages)}</div>`);
    return title(L('Pledge reviews','代币质押审核'),L('Review each token application independently.','逐笔查看并处理代币质押申请。'))+metrics+`<section class="card">${filters()}<div class="pr-list-tools">${field(L('Sort by','排序'),select('pr-order',A.sort+':'+A.dir,[['submitted:1',L('Submitted · oldest first','提交时间 · 最早优先')],['submitted:-1',L('Submitted · newest first','提交时间 · 最新优先')],['waiting:-1',L('Waiting · longest first','审核等待 · 最长优先')],['waiting:1',L('Waiting · shortest first','审核等待 · 最短优先')],['value:-1',L('Value · highest first','价值 · 从高到低')],['value:1',L('Value · lowest first','价值 · 从低到高')],['deadline:1',L('Deadline · earliest first','审核截止 · 最早优先')],['deadline:-1',L('Deadline · latest first','审核截止 · 最晚优先')]]))}</div><div class="pr-section" ${A.error?'':'hidden'}>${error()}</div>${table}</section>`;
  }
  function title(t,sub){return `<div class="pr-title"><div><h1>${t}</h1><span class="pr-meta">${sub}</span></div>${CF.tag('gray',L('Demonstration data','演示数据'))}</div>`;}
  function fileList(r){return r.files.length?r.files.map((f,i)=>`<div class="pr-file"><strong>${E(f.name)}</strong><span class="pr-meta">${['invalid','expired'].includes(r.follow)?L('Invalidated · archive only','已失效 · 仅存档'):L('Linked to this decision','已关联本笔结论')}</span>${link('Preview','预览','preview',i)}${link('Download','下载','download',i)}</div>`).join(''):note(L('No formal agreement for this application.','本笔暂无正式协议。'));}
  function detail(){const r=row();if(!r)return CF.empty(L('Application unavailable','申请不可用'),L('Return to the review queue.','请返回审核队列。'),b('Back to queue','返回队列','back'));
    if(A.view!=='default')return title(E(r.id),'')+surface();
    const batch=A.rows.filter(x=>x.batch===r.batch),pending=batch.filter(x=>x.status==='pending').length;
    const related=A.rows.filter(x=>x.owner===r.owner&&x.project===r.project&&x.batch!==r.batch).sort((a,b)=>b.submitted-a.submitted);
    const summary=Object.entries(status).map(([k,v])=>`${txt(v)} ${batch.filter(x=>x.status===k).length}`).join(' · ');
    const permission=A.role==='read'?L('View access only.','当前仅有查询权限。'):r.status!=='pending'?L('This review has ended. The record is read-only.','本笔审核已结束，记录只读。'):L('Record your offline decision for this token.','请维护本笔线下审核结论。');
    const decision=['approved','rejected'].includes(r.status)?section('Decision and evidence','审核结论与凭据',kv([[L('Reviewer','审核人'),txt(r.operator)],[L('Decision time','结论时间'),time(r.decisionAt)],[L('Decision record','结论记录编号'),r.reviewId],[L('Decision value','结论时价值'),money(r.value)],...(r.status==='rejected'?[[L('Category','原因归类'),r.category!==''?txt(categories[+r.category]):'—'],[L('Rejection reason','驳回原因'),`<div class="pr-confirm">${E(r.reason)}</div>`,true]]:[]),...(r.remark?[[L('Internal note','内部备注'),E(r.remark),true]]:[])])+(r.status==='approved'?`<div class="pr-evidence"><h3>${L('Agreement files','质押协议')}</h3>${fileList(r)}</div>`:'')):'';
    const overview=section('Application overview','申请概览',kv([[L('Asset holder','资产方'),E(owner(r))+'<span class="pr-meta mono">DEMO-ENTITY-'+r.owner+'</span>'],[L('Project','项目'),E(project(r))+'<span class="pr-meta mono">DEMO-PJ-'+r.project+'</span>'],[L('Project status / type','项目状态 / 类型'),L('Open · financing project','进行中 · 融资项目')],[L('Application type','申请类型'),r.type==='first'?L('Initial pledge','建池首笔'):L('Additional pledge','追加')],[L('Submitted','提交时间'),time(r.submitted)],[L('Batch identifier','批次编号'),r.batch]]))+
      section('Token details','代币详情',kv([[L('Token identifier','代币编号'),r.token],[L('Quantity / currency','数量 / 币种'),CF.fmtAmt(r.amount)+' '+r.currency],[L('Underlying tenor','底层账期'),r.term+' '+L('days','天')],[L('Buyer','买方企业'),r.buyer||L('To be verified','待核实')],[L('Validity','有效性'),r.valid?L('Valid','有效'):L('Invalid','已失效')]]))+decision+(r.status==='approved'?execution(r):'');
    const associations=section('Batch context','批次上下文',`<div class="pr-row"><b class="mono">${r.batch}</b>${CF.tag('gray',pending===batch.length?L('Pending review','待审核'):pending?L('Review in progress','审核进行中'):L('Review ended','审核已结束'))}</div><p class="pr-meta">${summary}</p><p class="pr-meta">${L('Approved applications — execution: ','已通过笔执行进度：')}${[['none',L('Not initiated','未发起')],['processing',L('Processing','处理中')],['success',L('Success','成功')],['failed',L('Failure','失败')]].map(([k,label])=>label+' '+batch.filter(x=>x.status==='approved'&&(k==='none'?['none','ready','invalid','expired'].includes(x.follow):k==='processing'?['processing','verify','difference'].includes(x.follow):x.follow===k)).length).join(' · ')}</p><div class="tablewrap"><table class="tbl pr-table"><thead><tr><th>${L('Token / application','代币 / 单笔')}</th><th>${L('Review','审核')}</th><th>${L('Reviewer / time','审核人 / 时间')}</th><th class="col-act">${L('Action','操作')}</th></tr></thead><tbody>${batch.map(x=>`<tr><td>${x.token}<span class="pr-meta mono">${x.id}</span></td><td>${badge(x)}</td><td>${x.operator?txt(x.operator):'—'}<span class="pr-meta">${time(x.decisionAt||x.ended)}</span></td><td class="col-act">${x.id===r.id?L('Current','当前'):link('View','查看','view',x.id)}</td></tr>`).join('')}</tbody></table></div>`)+
      section('Related applications','相关申请',`<p class="pr-meta">${L('Same project and asset holder.','同项目、同资产方的申请。')}</p>${related.length?`<div class="tablewrap"><table class="tbl pr-table pr-related"><thead><tr><th>${L('Application / token','单笔 / 代币')}</th><th>${L('Batch / submitted','批次 / 提交时间')}</th><th>${L('Review status','审核状态')}</th><th class="col-act">${L('Action','操作')}</th></tr></thead><tbody>${related.map(x=>`<tr><td><strong class="mono">${E(x.id)}</strong><span class="pr-meta mono">${E(x.token)}</span>${x.previous?`<span class="pr-meta">${L('Reapplication of ','再次申请自 ')}${E(x.previous)}</span>`:''}</td><td>${E(x.batch)}<span class="pr-meta">${time(x.submitted)}</span></td><td>${badge(x)}</td><td class="col-act">${link('View','查看','view',x.id)}</td></tr>`).join('')}</tbody></table></div>`:note(L('No related applications.','暂无相关申请。'))}`);
    const activity=section('Activity','本笔记录',r.events.slice().sort((a,b)=>b.at-a.at).map(e=>`<div class="pr-event"><b>${E(txt(e.title))}</b><span class="pr-meta">${time(e.at)} · ${E(txt(e.actor))}</span>${e.text?`<p>${E(txt(e.text))}</p>`:''}</div>`).join(''));
    const tabs=[['overview',L('Overview','概览')],['related',L('Linked applications','关联申请')],['activity',L('Activity','操作记录')]];
    return (A.source?`<div class="pr-origin"><a class="actlink" href="#${E(detailRoute(A.source,'related'))}" data-act="pr-origin">${L('Return to ','返回来源申请 ')}${E(A.source)}</a></div>`:'')+title(E(r.id),E(r.token))+(A.draft?'':error())+
      `<div class="card pr-detail-summary"><div><span class="pr-meta">${L('Review status','审核状态')}</span>${badge(r)}</div><div><span class="pr-meta">${L('Token value','代币价值')}</span><strong class="pr-value mono">${money(r.value)}</strong></div><div><span class="pr-meta">${L('Review deadline','审核截止')}</span><strong>${time(r.deadline)}</strong></div></div>`+
      (r.status==='timeout'?note(L('Review timed out. Application hold released; no on-chain operation or fee occurred.','审核超时，申请占用已释放；未发生链上操作或费用。')):'')+
      `<div class="pr-grid"><div class="pr-detail-main"><div class="pr-tabs" role="tablist" aria-label="${L('Application sections','申请详情分区')}">${tabs.map(([k,label])=>`<button type="button" role="tab" id="pr-tab-${k}" aria-selected="${A.tab===k}" aria-controls="pr-detail-panel" tabindex="${A.tab===k?0:-1}" data-act="pr-tab" data-v="${k}">${label}</button>`).join('')}</div><div id="pr-detail-panel" role="tabpanel" tabindex="0" aria-labelledby="pr-tab-${A.tab}" class="detail-stack pr-stack">${A.tab==='overview'?overview:A.tab==='related'?associations:activity}</div></div>
      <aside class="pr-stack pr-rail">${section('Review application','审核处理',`<p class="pr-meta">${permission}</p>${r.status==='pending'?`<div class="pr-rail-time"><span class="pr-meta">${L('Time remaining','剩余审核时间')}</span><strong>${duration(r.deadline-now())}</strong><span class="pr-meta">${L('Waiting','已等待')} ${duration(now()-r.submitted)}</span></div>`:`<p class="pr-meta">${L('Review waiting','审核等待')} · ${duration((r.decisionAt||r.ended)-r.submitted)}</p>`}${A.role==='review'?`<div class="pr-stack">${b('Approve application','通过申请','approve','','primary',!canWrite(r))}${b('Reject application','驳回申请','reject','','',!canWrite(r))}</div>`:''}${r.status==='pending'?`<p class="pr-meta pr-disclosure">${L('Approval does not mean the pledge has succeeded.','审核通过不等于质押成功。')}</p>`:''}`)}${r.status==='approved'?section('After approval','审核后续',`<div class="pr-follow">${CF.tag('gray',txt(follows[r.follow]))}</div>`+kv([[L('Deposit deadline','入池截止'),time(r.entryDeadline),true],...(r.started&&!r.completed?[[L('Execution waiting','执行等待'),duration(now()-r.started),true]]:[])])):''}</aside></div>`;
  }
  function execution(r){return section('Follow-up','后续情况',kv([[L('Pre-check','入池前复核'),r.follow==='invalid'?L('Failed · project is closed','不通过 · 项目已终结'):['ready','expired'].includes(r.follow)?L('Not checked','未复核'):L('Passed','通过')],[L('Execution','执行情况'),txt(follows[r.follow])],[L('Initiated','发起时间'),time(r.started)],[L('Completed','完成时间'),time(r.completed)],[L('Actual fee','实际费用'),r.started?(r.fee==null?L('Fee under verification','费用待核实'):r.fee+' '+r.feeCurrency):L('Not executed · no fee','未执行 · 零费用')],[L('Evidence','执行凭据'),r.tx?`${E(r.tx)} ${link('Copy','复制','copy',r.tx)}`:'—'],[L('Reason','原因'),r.executionReason?E(txt(r.executionReason)):'—',true]])+(r.started?`<p class="pr-meta">${L('Fees already incurred are not refunded, including failed executions.','已产生的费用不退，包含执行失败的费用。')}</p>`:''));}
  function surface(){S.st=A.view;return CF.surface({emptyTitle:L('No applications yet','暂无申请'),emptyDesc:L('New applications will appear here.','收到新申请后将在此显示。'),deniedDesc:L('Contact the platform administrator to check access.','请联系平台建设方核对权限。'),backTo:ROOT,backLabel:L('Back to queue','返回队列'),skelRows:5});}
  function start(mode){expire();if(!canWrite(row()))return deny();A.draft={id:row().id,mode,files:[],reason:'',category:'',remark:'',ack:false};A.error='';open('edit');}
  function validate(){const d=A.draft;if(!d)return false;A.error='';if(d.mode==='approve'){
      if(d.files.length<1||d.files.length>5)A.error=['Choose 1–5 agreement files.','请选择 1～5 个协议文件。'];
      else if(d.files.some(f=>f.state!=='ready'))A.error=['Wait for all uploads to finish, or remove and replace failed files.','请等待所有文件上传完成，或移除并替换失败文件。'];
      else if(Array.from(d.remark).length>200)A.error=['Internal note must not exceed 200 characters.','内部备注不能超过 200 字。'];
      else if(!d.ack)A.error=['Confirm that approval is not pledge success.','请确认知悉：审核通过不等于质押成功。'];
    }else{const s=d.reason.trim(),n=Array.from(s).length;if(n<10||n>500||!/[\p{L}\p{N}]/u.test(s))A.error=['Enter a reason of 10–500 characters; punctuation alone is not valid.','原因需为 10～500 字，不能仅填标点。'];}
    return !A.error;
  }
  function finalReason(d){return d.reason.trim();}
  function applyDecision(r,d,other=false){if(r.status!=='pending')return false;r.status=d.mode==='approve'?'approved':'rejected';r.decisionAt=now();r.operator=other?['Demo operator Chen','示例审核员陈']:['Demo operator Lin','示例审核员林'];r.reviewId=r.id.replace('PR','RV');r.reason=d.mode==='reject'?finalReason(d):'';r.category=d.category;r.remark=d.remark;r.files=d.mode==='approve'?d.files.map(f=>({...f})):[];r.entryDeadline=d.mode==='approve'?now()+7*86400000:null;r.follow=d.mode==='approve'?'ready':'none';event(r,status[r.status],r.reason,r.operator);A.events.push({id:r.id,event:r.status});return true;}
  function submit(){expire();const d=A.draft,r=row();if(A.busy)return;if(!d||d.id!==r?.id||!canWrite(r))return deny();if(!validate()){open('edit');return;}A.busy=true;A.error='';CF.render();const epoch=A.epoch,response=A.response;
    setTimeout(()=>{if(epoch!==A.epoch||A.draft!==d)return;expire();A.busy=false;if(!canWrite(r))return deny();
      if(response==='fail'){A.error=['Could not save the decision. Your inputs are preserved.','结论保存失败，已保留输入，请重试。'];open('edit');return;}
      if(response==='withdraw'){r.status='withdrawn';r.ended=now();event(r,['Withdrawn by asset holder','资产方已撤回']);A.draft=null;S.layer=null;A.error=['The asset holder withdrew this application. No decision was saved.','资产方已撤回本笔，未保存审核结论。'];CF.render();return;}
      if(response==='concurrent'){applyDecision(r,{...d,mode:'reject',reason:L('Materials require further verification by the applicant.','申请材料尚需资产方进一步核实后重新提交。'),files:[]},true);A.draft=null;S.layer=null;A.error=['Another reviewer has decided this application. The current result is shown.','本笔已由其他审核员处理，已显示当前结论、审核人及时间。'];CF.render();return;}
      if(response==='unknown'){A.uncertain={id:r.id,d:{...d}};A.draft=null;S.layer=null;A.error=['Decision result is being confirmed. Check the current result before proceeding.','结论结果待确认，请查询当前结果后再操作。'];CF.render();return;}
      applyDecision(r,d);A.tab='overview';saveContext();A.draft=null;S.layer=null;A.response='success';CF.render();CF.toast(L('Decision saved for this application.','本笔审核结论已保存。'));
    },650);
  }
  function editLayer(){const d=A.draft,r=row();if(!d||!r)return {title:L('Unavailable','不可用'),html:'',foot:b('Close','关闭','cancel')};
    const docs=d.files.map((f,i)=>`<div class="pr-file">${E(f.name)}<span class="pr-meta">${f.state==='ready'?L('Ready','已就绪'):f.state==='uploading'?L('Uploading…','上传中…'):L('Upload failed — remove and retry','上传失败，请移除后重试')}</span>${f.state==='uploading'?'<progress class="pr-progress" aria-label="Uploading"></progress>':''}${b('Remove','移除','remove',i,'sm',A.busy)}</div>`).join('');
    const body=d.mode==='approve'?`${field(L('Agreement files','质押协议'),`<label class="btn pr-upload" for="pr-upload">${L('Upload agreements','上传协议')}<input class="sr-only" id="pr-upload" type="file" accept="application/pdf,image/jpeg,image/png" multiple></label>`)}<span class="pr-meta">${L('PDF / JPG / PNG · 1–5 files · up to 10 MB each','PDF / JPG / PNG · 1～5 个 · 每个不超过 10 MB')}</span>${docs}${field(L('Internal note (optional)','内部备注（选填）'),`<textarea class="inp" id="pr-remark" aria-invalid="${!!A.error&&Array.from(d.remark).length>200}">${E(d.remark)}</textarea><span class="pr-meta">${Array.from(d.remark).length} / 200</span>`)}<label><input id="pr-ack" type="checkbox" ${d.ack?'checked':''}> ${L('I understand that approval does not mean the pledge has succeeded.','我已知悉：审核通过不等于质押成功。')}</label>`:
      `${field(L('Category (optional)','归类（选填）'),select('pr-category',d.category,[['',L('Not selected','未选择')],...categories.map((x,i)=>[String(i),txt(x)])]))}${field(L('Reason shown to asset holder','向资产方展示的原因'),`<textarea class="inp" id="pr-reason" aria-invalid="${!!A.error}" aria-describedby="pr-form-error">${E(d.reason)}</textarea><span class="pr-meta">${Array.from(d.reason.trim()).length} / 500 · ${L('Minimum 10 characters','至少 10 字')}</span>`)}`;
    return {title:d.mode==='approve'?L('Approve application','通过本笔申请'):L('Reject application','驳回本笔申请'),html:`<div class="pr-form">${identity(r)}${body}<div id="pr-form-error">${error()}</div></div>`,foot:b('Cancel','取消','cancel')+b('Review decision','核对结论','confirm','','primary')};
  }
  const layers={
    'pr-edit':editLayer,
    'pr-confirm':()=>({title:L('Confirm decision','确认审核结论'),html:identity(row())+`<div class="pr-section"><b>${A.draft?.mode==='approve'?L('Approve this application only','仅通过本笔申请'):L('Reject this application only','仅驳回本笔申请')}</b><div class="pr-confirm">${A.draft?.mode==='approve'?A.draft.files.map(f=>E(f.name)).join('<br>'):E(A.draft?.reason.trim())}</div><p class="pr-meta">${A.draft?.mode==='approve'?L('The asset holder still needs to confirm execution. No on-chain action is initiated here.','资产方仍需确认执行；本次审核不会发起链上操作。'):L('The reason above will be shown in full to the asset holder. Other applications are unchanged.','以上原因将全文展示给资产方，其他申请不受影响。')}</p>${A.busy?'<p role="status">'+L('Saving decision…','正在保存结论…')+'</p>':''}</div>`,foot:b('Back','返回修改','edit','','',A.busy)+b('Confirm','确认提交','submit','','primary',A.busy)}),
    'pr-discard':()=>({title:L('Discard unsaved inputs?','放弃未提交内容？'),html:note(L('Files, notes and reasons will not be carried to another application.','未提交文件、备注及原因不会带入其他申请。')),foot:b('Keep editing','继续编辑','keep')+b('Discard','放弃内容','discard','','primary')}),
    'pr-preview':()=>({title:L('Agreement preview','协议预览'),html:previewHTML(),foot:b('Close','关闭','close')+b('Download','下载','download',A.previewIndex,'primary')})
  };
  function sampleURL(){const stream='BT /F1 18 Tf 40 150 Td (DEMONSTRATION AGREEMENT) Tj 0 -30 Td (Covers the DEMO tokens in the linked applications.) Tj ET';const objs=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 500 220] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n',offsets=[0];objs.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const x=pdf.length;pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return URL.createObjectURL(new Blob([pdf],{type:'application/pdf'}));}
  let sample;
  function fileURL(f){if(f.sample)return sample||(sample=sampleURL());return f.url;}
  function previewHTML(){if(!canRead())return note(L('Access denied.','无权查看。'));const f=row()?.files[A.previewIndex];if(!f)return note(L('File unavailable.','文件不可用。'));if(A.preview==='missing')return note(L('File could not be retrieved. Retry later.','文件暂时不可得，请稍后重试。'));if(A.preview==='fail')return note(L('Preview failed. Download the file to view it.','预览失败，请下载后查看。'));if(f.sample)return `<div class="pr-confirm"><h3>${L('Demonstration agreement','演示协议')}</h3><p>${E(row().batch)} · ${E(row().token)}</p><p>${L('This demonstration document covers all DEMO tokens in this batch.','此演示材料覆盖本批次全部 DEMO 代币。')}</p></div>`;return /image/.test(f.type)?`<img class="pr-preview" src="${E(fileURL(f))}" alt="${E(f.name)}">`:`<object class="pr-preview" type="application/pdf" data="${E(fileURL(f))}">${L('Download the PDF to view it.','请下载 PDF 查看。')}</object>`;}
  function download(i){if(!canRead())return deny();const f=row()?.files[i];if(!f||A.preview==='missing'){CF.toast(L('File unavailable. Try again later.','文件暂时不可得，请稍后重试。'));return;}const a=document.createElement('a');a.href=fileURL(f);a.download=f.name;a.click();}
  function demo(){return `<h3>${L('Review tools','演示工具')}</h3><p class="pr-meta">${L('Local demonstration only. No real submission or transfer.','仅本地演示，不产生真实提交或转移。')}</p><div class="pr-demo">${field(L('Permission','权限'),select('pr-role',A.role,[['review',L('Query + review','查询＋处置')],['read',L('Query only','仅查询')],['none',L('No access','无权限')],['writeonly',L('Review without query','仅处置无查询')],['expired',L('Session expired','登录失效')]]))}${field(L('Page state','页面状态'),select('pr-view',A.view,[['default',L('Default','默认')],['loading',L('Loading','加载')],['empty',L('Empty','空数据')],['noresult',L('No results','筛选无结果')],['error',L('Load failed','读取失败')],['denied',L('Access denied','无权限')]]))}${field(L('Submit response','提交反馈'),select('pr-response',A.response,[['success',L('Success','成功')],['fail',L('Failure','失败')],['unknown',L('Uncertain result','结果待确认')],['concurrent',L('Another reviewer wins','同笔已被他人审核')],['withdraw',L('Withdrawn before save','提交前资产方撤回')]]))}${field(L('Upload response','上传反馈'),select('pr-upload-state',A.upload,[['success',L('Success','成功')],['fail',L('Failure','失败')]]))}${field(L('Attachment response','附件反馈'),select('pr-preview-state',A.preview,[['success',L('Success','成功')],['fail',L('Preview fails','预览失败')],['missing',L('File unavailable','文件不可得')]]))}</div><div class="pr-demo">${b('47 h 59 min','47 小时 59 分','clock','before')}${b('At 48 h','恰满 48 小时','clock','deadline')}${b('Simulate expired-page write','模拟旧页越权提交','forbidden')}${b('Reset demonstration','重置演示','restart')}</div><h4>${L('Outcome events','结果事件')}</h4><p class="pr-meta">${A.events.map(e=>E(e.id+' · '+e.event)).join('<br>')||L('None','暂无')}</p>`;}
  function content(page){expire();S.st=A.view;if(!canRead())return title(L('Pledge reviews','代币质押审核'),'')+CF.empty(L('Access unavailable','无法访问'),A.role==='expired'?L('Your session has expired.','登录已失效。'):L('Query permission is required. Contact the platform administrator.','需要查询权限，请联系平台建设方。'),'');
    let out=page===D?detail():queue();if(A.uncertain)out=note(L('A submitted decision is awaiting confirmation. Do not submit another decision.','已提交结论的结果待确认，请勿重复裁定。')+' '+b('Check current result','查询当前结果','resolve'))+out;return out;}
  function onAct(act,v,e){if(e&&(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)&&['pr-view','pr-origin'].includes(act))return false;if(!act.startsWith('pr-')){if(act==='retry'){A.view='default';A.error='';CF.render();return true;}if(act==='clearfilter'){resetFilter();return true;}return false;}act=act.slice(3);
    if(act==='origin')navigateRoute(detailRoute(A.source,'related'));else if(act==='view')visit(v);else if(act==='back')visit(null);else if(act==='page'){A.page=+v;saveContext();CF.render();window.scrollTo(0,0);}
    else if(act==='search'){const f={...A.editFilter};if(f.from&&f.to&&f.from>f.to){A.filtersOpen=true;A.error=['Start date must not be later than end date.','开始日期不得晚于结束日期。'];CF.render();return true;}A.error='';A.filtersOpen=false;A.filter=f;A.page=1;A.view='default';saveContext();CF.render();}
    else if(act==='filters'){A.filtersOpen=!A.filtersOpen;CF.render();document.querySelector('[data-act=pr-filters]')?.focus();}else if(act==='tab'){A.tab=v;saveContext();CF.render();document.getElementById('pr-tab-'+v)?.focus();}else if(act==='reset')resetFilter();else if(act==='sort'){A.dir=A.sort===v?-A.dir:1;A.sort=v;saveContext();CF.render();}
    else if(act==='approve'||act==='reject'){if(A.uncertain?.id===row()?.id){CF.toast(L('Check the pending result first.','请先查询待确认结果。'));return true;}start(act);}
    else if(act==='confirm'){expire();if(!canWrite(row()))deny();else if(validate())open('confirm');else{CF.render();document.getElementById(A.draft.mode==='reject'?'pr-reason':'pr-upload')?.focus();}}
    else if(act==='edit')open('edit');else if(act==='submit')submit();
    else if(act==='remove'){A.draft.files.splice(+v,1);A.error='';CF.render();}
    else if(act==='cancel'){A.next=undefined;if(A.draft&&(A.draft.files.length||A.draft.reason||A.draft.remark))open('discard');else{A.draft=null;CF.closeLayer();}}
    else if(act==='keep')open('edit');else if(act==='discard'){A.draft=null;A.error='';if(A.next!==undefined){const target=A.next;A.next=undefined;navigateRoute(target);}else CF.closeLayer();}
    else if(act==='close')CF.closeLayer();else if(act==='preview'){if(!canRead())deny();else{A.previewIndex=+v;open('preview');}}else if(act==='download')download(+v);
    else if(act==='copy'){navigator.clipboard?.writeText(v).then(()=>CF.toast(L('Copied','已复制'))).catch(()=>CF.toast(L('Copy the visible value manually.','请手动复制显示值。')));}
    else if(act==='clock'){const r=row()||A.rows.find(x=>x.status==='pending');if(r){A.now=r.deadline-(v==='before'?60000:0);A.clock=Date.now();expire();CF.render();}}
    else if(act==='forbidden'){if(A.role==='review')CF.toast(L('Choose a restricted permission profile first.','请先选择受限权限。'));else deny();}
    else if(act==='resolve'){const u=A.uncertain,r=A.rows.find(x=>x.id===u?.id);if(!canRead())deny();else{if(r?.status==='pending'&&now()<r.deadline)applyDecision(r,u.d);A.uncertain=null;A.error='';CF.render();CF.toast(L('Current result retrieved.','已获取当前结果。'));}}
    else if(act==='restart'){A.epoch++;seed=CF.pledgeSeed();A.rows=seed.rows;A.now=seed.now;A.clock=Date.now();A.draft=null;A.uncertain=null;A.busy=false;A.role='review';A.response='success';A.upload='success';A.preview='success';A.events=[];resetFilter();navigate(null);}
    return true;
  }
  function resetFilter(){A.filter=fDefault();A.editFilter=fDefault();A.filtersOpen=false;A.page=1;A.sort='submitted';A.dir=1;A.error='';A.view='default';if(S.page===Q)saveContext();CF.render();}
  function onInput(e){const el=e.target,id=el.id;if(id.startsWith('pr-f-')){A.editFilter[id.slice(5)]=el.value;return;}if(A.draft){if(id==='pr-reason')A.draft.reason=el.value;if(id==='pr-remark')A.draft.remark=el.value;if(id==='pr-category')A.draft.category=el.value;if(id==='pr-ack')A.draft.ack=el.checked;if(id==='pr-reason'||id==='pr-remark'){const count=el.parentElement.querySelector('.pr-meta');if(count)count.textContent=Array.from(el.value.trim()).length+' / '+(id==='pr-reason'?'500':'200');el.setAttribute('aria-invalid','false');}}}
  document.addEventListener('submit',e=>{if(e.target.id==='pr-filter-form'){e.preventDefault();onAct('pr-search','');}});
  document.addEventListener('keydown',e=>{if(e.target.matches('[role=tab][data-act=pr-tab]')&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tabs=['overview','related','activity'],i=tabs.indexOf(A.tab);onAct('pr-tab',tabs[e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3]);}});
  document.addEventListener('input',onInput);
  document.addEventListener('change',e=>{onInput(e);const el=e.target,id=el.id;if(id==='pr-order'){const [sort,dir]=el.value.split(':');A.sort=sort;A.dir=+dir;saveContext();CF.render();}
    if(['pr-role','pr-view','pr-response','pr-upload-state','pr-preview-state'].includes(id)){const key={'pr-role':'role','pr-view':'view','pr-response':'response','pr-upload-state':'upload','pr-preview-state':'preview'}[id];A[key]=el.value;A.error='';if(key==='role'){A.epoch++;A.busy=false;S.layer=null;A.draft=null;}CF.render();}
    if(id==='pr-upload'&&A.draft){const d=A.draft,files=Array.from(el.files);A.error='';if(files.length+d.files.length>5){A.error=['At most 5 files per application.','每笔最多 5 个文件。'];CF.render();return;}
      files.forEach(f=>{const typeOK=['application/pdf','image/jpeg','image/png'].includes(f.type),extOK=/\.(pdf|jpe?g|png)$/i.test(f.name);if(!typeOK||!extOK||f.size>10*1024*1024||!f.size){A.error=[f.name+': use a non-empty PDF/JPG/PNG up to 10 MB.',f.name+'：请选择非空 PDF/JPG/PNG，单个不超过 10 MB。'];return;}const file={id:crypto.randomUUID(),name:f.name,type:f.type,size:f.size,state:'uploading',url:URL.createObjectURL(f)};d.files.push(file);setTimeout(()=>{file.state=A.upload==='fail'?'failed':'ready';if(A.draft===d)CF.render();},550);});CF.render();}
  });
  document.addEventListener('click',e=>{
    const a=e.target.closest('a[href^="#"]');
    if(!a||a.hasAttribute('data-act')||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;
    if(A.draft){e.preventDefault();A.next=a.hash.slice(1);open('discard');return;}
    remember();
  },true);
  const dict={en:{navGroupOps:'Operations',navPledgeReviews:'Pledge reviews',navPledgeReviewDetail:'Application detail'},zh:{navGroupOps:'运营管理',navPledgeReviews:'质押审核',navPledgeReviewDetail:'单笔审核详情'}};
  CF.define({id:'pledge-review',dict,content,layers,onAct,demoOnly:true,demo,
    allowNav:id=>id===Q&&canRead(),adminContext:()=>({name:L('Demo operator Lin','示例审核员林'),subtitle:A.role==='review'?L('Query + review','查询＋处置'):L('Restricted access','受限权限'),hideNotifications:true}),
    breadcrumbRoute:id=>id===Q?queueRoute():null,beforeRender(){S.toTop=false;syncContext();},afterRender:restoreView,
    onBeforeAct(act,v,e){if(act==='retry'||act==='clearfilter'){onAct(act,v);return true;}if(act==='closelayer'&&e?.type==='click'&&e.target.closest('[data-stop]'))return false;if(act==='closelayer'&&A.busy)return true;if(act==='closelayer'&&A.draft){onAct('pr-cancel','');return true;}return false;},
    onRoute(){A.epoch++;A.busy=false;A.draft=null;A.error='';A.view='default';restoreContext=true;},
  });
  S.end='admin';S.role='ops';if(!location.hash.startsWith('#'+ROOT))history.replaceState(null,'','#'+ROOT);CF.boot();
  setInterval(()=>{const previous=A.rows.filter(r=>r.status==='pending').length;expire();if(previous!==A.rows.filter(r=>r.status==='pending').length)CF.render();},1000);
})(window.CF);
