/* WS-351 · module views. Shared tokens/components/shell remain the only source. */
(function(CF){
  'use strict';
  const S=CF.S,D=CF.LS,L=CF.L,E=CF.esc;
  const LIST='P-LS-01',DETAIL='P-LS-02',NEW='P-LS-03';
  CF.PAGES[DETAIL]={end:'asset',layout:'portal',crumbKey:'lsDetail'};
  CF.PAGES[NEW]={end:'asset',layout:'portal',crumbKey:'lsNew',auth:true};
  CF.ENTRY[DETAIL]='/project/'+D.projects[0].id;CF.ENTRY[NEW]='/project/new';
  let selection=[],name='',kind='',error='',amount='',busy=false,appId=null,operation='deposit',pages={tokens:1,demands:1,select:1},filter={},pendingAction=null;
  try{fromConsole=sessionStorage.getItem('hc-ls-origin')==='console';}catch(_){}
  let outcome='success',executionGate='normal',submitFail=false,refocus=null,fromConsole=false;
  const stateNames={draft:['Draft','草稿'],raising:['Fundraising','募集中'],locked:['Locked','已锁定'],financing:['Financing','融资中'],closed:['Closed','已关闭'],settled:['Settled','已结清'],review:['Under review','审核中'],approved:['Approved · pending deposit','审核通过 · 待入池'],rejected:['Rejected','已驳回'],withdrawn:['Withdrawn','已撤回'],expired:['Approval expired','结论已失效'],void:['Approval voided','结论已作废'],timeout:['Timed out','超时失败'],executing:['Execution in progress','执行处理中'],recorded:['Results recorded','结果已回写'],processing:['Processing','处理中'],success:['Succeeded','成功'],failure:['Failed','失败'],noFee:['Failed','失败'],open:['Awaiting quotes','待报价'],quoted:['Quoted · awaiting confirmation','已报价待确认'],funding:['Funding in progress','放款中'],funded:['Funded','已放款'],ended:['Expired / closed','已失效／已关闭'],surplus:['Coverage surplus','覆盖有余'],balanced:['Coverage balanced','覆盖持平'],short:['Coverage shortfall','覆盖不足']};
  const reasons={reviewTimeout:['Operations did not complete the review within the time limit.','运营端未在时限内完成审核。'],rejected:['The selected receivables require a complete buyer acknowledgement. Please provide the missing evidence before submitting again.','所选应收账款缺少完整的买方确认，请补全确认材料后重新提交。'],recheck:['The token is no longer eligible. This approval has been voided; no execution was started and no fees were incurred.','代币已不满足入池条件，结论已作废；未发起链上执行，未产生任何费用。'],closed:['The project is closed.','项目已关闭。'],coverage:['Automatically expired · coverage shortfall','自动失效 · 覆盖不足'],withdrawn:['Withdrawn by asset holder','资产方撤下'],expiry:['Project term expired','有效期到期'],owner:['Closed by asset holder','资产方主动关闭']};
  const errors={permission:['You cannot perform this action for this entity.','你无权代表该企业执行此操作。'],selectionChanged:['The selection is no longer available. Select eligible tokens again.','所选代币已被占用或不再可质押，请重新选择。'],name:['Enter a project name of 1–60 characters.','请输入 1～60 字符的项目名称。'],reviewChanged:['This application already has a decision and cannot be withdrawn.','该申请已有结论，无法撤回。'],approvalChanged:['This approval is no longer available. Check the application history.','该审核结论已不可用，请查看审核历史。'],publishChanged:['The project cannot be published now. Refresh the amount and project status.','当前无法发布，请检查最新额度和项目状态。'],demandChanged:['The financing request has changed and cannot be edited.','融资需求状态已变化，当前不可修改。'],cannotClose:['Withdraw the open financing request and settle outstanding financing before closing.','请先撤下在途需求并结清存量融资业务，再关闭项目。'],amount:['Enter a positive USD amount with no more than 2 decimal places, within the available amount.','请输入大于 0、最多两位小数且不超过可融金额的 USD 金额。'],withdrawLimit:['The selected value exceeds the current withdrawal limit. Reduce the selection or wait for repayment.','拟撤回价值超过当前上限，请减少勾选或等待还款释放余额。']};
  const txt=a=>a?L(a[0],a[1]):'—',usd=n=>CF.fmtAmt(n)+' USD',time=v=>v?CF.fmtTime(v):'—',date=v=>v?CF.fmtDate(v):'—';
  const label=k=>txt(stateNames[k]||[k,k]);
  const tag=k=>CF.tag(['short','failure','timeout','rejected'].includes(k)?'danger':['approved','success','surplus'].includes(k)?'ok':['review','processing','executing'].includes(k)?'warn':'',label(k));
  const note=(s,t='accent')=>CF.note(t==='danger'?'red':t,s);
  const btn=(act,text,value='',primary=false,disabled=false)=>'<button type="button" class="btn'+(primary?' primary':'')+'" data-act="'+act+'" data-v="'+E(value)+'"'+(disabled?' disabled':'')+'>'+text+'</button>';
  const card=(title,body)=>'<section class="card"><div class="card-head"><h2 class="ls-subheading">'+title+'</h2></div><div class="card-b">'+body+'</div></section>';
  const small=s=>'<div class="cell-sub">'+s+'</div>';
  const err=()=>error?'<div class="ls-error" role="alert">'+note(error,'danger')+'</div>':'';
  const path=()=>location.hash.replace(/^#/,'');
  const viewCache={};
  let listRoute='/marketplace';
  function readFilters(route){const q=new URLSearchParams(route.split('?')[1]||'');const v={};['type','vmin','vmax','amin','amax','status','quote','expiry','coverage','sort'].forEach(k=>{if(q.has(k))v[k]=q.get(k);});return v;}
  function savePosition(){const box=document.querySelector('#content .listbox');if(S.page===LIST&&box)viewCache[listRoute]={shown:S.shown,top:box.scrollTop,y:window.scrollY};}
  function writeFilters(){const q=new URLSearchParams();Object.keys(filter).forEach(k=>{if(filter[k])q.set(k,filter[k]);});const target='/marketplace'+(q.size?'?'+q.toString():'');viewCache[target]={shown:20,top:0,y:0};CF.ENTRY[LIST]=target;listRoute=target;if(path()!==target)location.hash='#'+target;CF.resetList();setTimeout(()=>window.scrollTo(0,0),0);}
  function restorePosition(){const c=viewCache[listRoute]||{shown:20,top:0,y:0};S.shown=c.shown;S.toTop=false;CF.render();const box=document.querySelector('#content .listbox');if(box)box.scrollTop=c.top;window.scrollTo(0,c.y);}
  function project(){const m=path().match(/^\/project\/([^?]+)/);return m?D.project(decodeURIComponent(m[1])):null;}
  function syncRoute(){const h=path();if(h==='/project/new')return;if(/^\/project\/[^/?]+/.test(h))CF.ENTRY[DETAIL]=h;else if(/^\/marketplace(?:\?|$)/.test(h))CF.ENTRY[LIST]=h;}
  function goto(id){CF.ENTRY[DETAIL]='/project/'+id;location.hash='#'+CF.ENTRY[DETAIL];}
  function showError(ex){error=txt(errors[ex.message]||reasons[ex.message]||['The action could not be completed. Please retry.','操作未完成，请重试。']);}
  function publicMissing(){return CF.empty(L('Content not found or access denied','内容不存在或无权访问'),'',btn('ls-list',L('Back to marketplace','返回借贷广场')));}
  function owner(p){return p.owner==='entity-demo-a'?L('Demo Asset Company A','演示资产企业 A'):L('Demo Asset Company B','演示资产企业 B');}
  function twoSteps(){return note(L('1. Submit for review now. No on-chain operation or fees. 2. After approval, return to confirm the deposit and pay the blockchain fees.','① 现在提交审核，不发生链上操作、不产生费用。② 审核通过后，回来确认入池并承担链上费用。'));}
  function guestNotice(){return ''; }
  function pager(key,count){const total=Math.max(1,Math.ceil(count/5));pages[key]=Math.min(pages[key]||1,total);return '<div class="pager"><span class="total">'+L(count+' items · 5 per page','共 '+count+' 条 · 每页 5 条')+'</span>'+btn('ls-page','←',key+':'+(pages[key]-1),false,pages[key]===1)+'<span>'+pages[key]+' / '+total+'</span>'+btn('ls-page','→',key+':'+(pages[key]+1),false,pages[key]===total)+'</div>';}
  function field(id,en,zh,value='',type='text',extra=''){return '<div class="field"><label for="'+id+'">'+L(en,zh)+'</label><input class="inp" id="'+id+'" type="'+type+'" value="'+E(value)+'" '+extra+'></div>';}
  function select(id,en,zh,opts,value='',extra=''){return '<div class="field"><label for="'+id+'">'+L(en,zh)+'</label><select class="inp" id="'+id+'" '+extra+'>'+opts.map(o=>'<option value="'+o[0]+'"'+(o[0]===value?' selected':'')+(o[3]?' disabled':'')+'>'+L(o[1],o[2])+'</option>').join('')+'</select></div>';}
  function dataTable(heads,rows){return '<div class="tablewrap"><table class="tbl resp ls-table"><thead><tr>'+heads.map(h=>'<th scope="col">'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map((c,i)=>'<td data-label="'+E(heads[i])+'"><div class="cell-wrap">'+c+'</div></td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
  function tokenTable(list,mode='public',key='tokens'){
    const head=[L('Token','代币编号'),L('Quantity / currency','代币数量 / 币种'),L('Token value','代币价值'),L('Receivable term','底层应收账款账期'),L('Buyer','买方企业'),L('Status','状态')];
    if(mode==='select'||mode==='release')head.unshift(L('Select','选择'));
    if(mode==='own')head.push(L('On-chain execution','链上执行状态'));
    if(!list.length)return CF.empty(L('No tokens available','暂无代币'),mode==='select'?L('No eligible tokens for this entity.','本企业暂无符合条件的代币。'):L('There are no tokens in this list.','当前清单暂无代币。'));
    const tail=pager(key,list.length),start=(pages[key]-1)*5;
    return dataTable(head,list.slice(start,start+5).map(t=>{
      const status=!t.valid?L('Expired · excluded from coverage','已失效 · 不计入覆盖'):t.frozen?(mode==='own'?L('Reconciliation pending · excluded','对账处理中 · 不计入覆盖'):L('Excluded from coverage','不计入覆盖')):t.pledge==='released'?L('Released · awaiting collection','已释放 · 待提取'):L('Valid','有效');
      const row=['<span class="mono">'+E(t.id)+'</span>'+(t.tx?small('<span class="hash">'+t.tx.slice(0,8)+'…'+t.tx.slice(-6)+'</span> '+btn('ls-proof',L('View receipt','查看凭证'),t.id)):''),CF.fmtAmt(t.units)+' '+E(t.symbol),usd(t.value),date(t.from)+' → '+date(t.due),E(txt(t.buyer)),CF.tag(t.valid&&!t.frozen?'':'warn',status)];
      if(mode==='select'||mode==='release'){
        const off=mode==='select'?!D.selectable(t):!!(t.frozen||t.pending);
        row.unshift('<label class="ls-check"><input type="checkbox" data-token="'+E(t.id)+'" '+(selection.includes(t.id)?'checked ':'')+(off?'disabled ':'')+'aria-label="'+L('Select ','选择 ')+E(t.id)+'"><span>'+L('Select','选择')+'</span></label>'+(off?small(t.application?L('Reserved by ','已被申请占用 ')+E(t.application):t.pending?L('On-chain processing','链上处理中'):L('Reconciliation pending','对账处理中')):''));
      }
      if(mode==='own')row.push(tag(t.pending?'processing':'success'));
      return row;
    }))+tail;
  }
  function filters(){const all=['','All','全部'];return '<div class="ls-fields">'+
    select('ls-type','Asset type','资产类型',[all,['ar','Receivables','应收账款']],filter.type||'')+
    '<div class="field"><label>'+L('Pool asset value (USD)','池内资产价值（USD）')+'</label><div class="ls-range"><input aria-label="'+L('Minimum pool value','池值下限')+'" class="inp" id="ls-vmin" type="number" min="0" value="'+E(filter.vmin||'')+'"><input aria-label="'+L('Maximum pool value','池值上限')+'" class="inp" id="ls-vmax" type="number" min="0" value="'+E(filter.vmax||'')+'"></div></div>'+
    '<div class="field"><label>'+L('Demand amount (USD)','需求金额（USD）')+'</label><div class="ls-range"><input aria-label="'+L('Minimum demand','需求下限')+'" class="inp" id="ls-amin" type="number" min="0" value="'+E(filter.amin||'')+'"><input aria-label="'+L('Maximum demand','需求上限')+'" class="inp" id="ls-amax" type="number" min="0" value="'+E(filter.amax||'')+'"></div></div>'+
    select('ls-status','Project status','项目状态',[all,...['raising','locked','financing','closed','settled'].map(k=>[k,...stateNames[k]])],filter.status||'')+
    select('ls-quote','Open for quotes','是否可报价',[all,['yes','Yes','是'],['no','No','否']],filter.quote||'')+
    select('ls-expiry','Expiry','有效期临近程度',[all,['7','Within 7 days','7 天内'],['30','Within 30 days','30 天内'],['expired','Expired','已到期']],filter.expiry||'')+
    select('ls-coverage','Coverage shortfall','是否覆盖不足',[all,['yes','Yes','是'],['no','No','否']],filter.coverage||'')+
    select('ls-sort','Sort by','排序',[['newest','Newest first','发布时间倒序'],['amount','Demand: high to low','需求金额从高到低'],['value','Pool value: high to low','池内资产价值从高到低']],filter.sort||'newest')+
    '<div class="ls-row">'+btn('ls-filter',L('Apply filters','筛选'),'',true)+btn('ls-clear',L('Reset','重置'))+'</div></div>';}
  function matching(){return D.projects.filter(p=>p.state!=='draft').filter(p=>{
    const n=D.numbers(p),d=D.current(p)||p.demands.at(-1),amount=d?d.amount:0,open=d&&d.state==='open'&&!p.expired&&n.grade==='surplus';
    if(filter.status&&p.state!==filter.status)return false;
    if(filter.vmin&&n.value<+filter.vmin||filter.vmax&&n.value>+filter.vmax||filter.amin&&amount<+filter.amin||filter.amax&&amount>+filter.amax)return false;
    if(filter.quote&&(filter.quote==='yes')!==!!open)return false;
    if(filter.coverage&&(filter.coverage==='yes')!==(n.grade==='short'))return false;
    if(filter.expiry==='expired'&&!p.expired)return false;
    if(['7','30'].includes(filter.expiry)&&(Date.parse(p.expires)-D.now()>+filter.expiry*86400000||p.expired))return false;
    return true;
  }).sort((a,b)=>filter.sort==='value'?D.numbers(b).value-D.numbers(a).value:filter.sort==='amount'?((D.current(b)||b.demands.at(-1)||{}).amount||0)-((D.current(a)||a.demands.at(-1)||{}).amount||0):Date.parse(b.published)-Date.parse(a.published));}
  function quoteReason(p){const n=D.numbers(p),d=D.current(p);return S.role==='asset'?L('Asset holders cannot submit quotes.','资产方不可提交报价。'):n.grade==='short'?L('Coverage shortfall','覆盖不足'):p.expired?L('Project term expired','项目已到期'):d&&d.state==='quoted'?L('An active quote already exists','已有在途报价'):L('This request is not open for quotes','当前需求不可报价');}
  function projectCard(p){const n=D.numbers(p),d=D.current(p)||p.demands.at(-1),a=D.actions(p);return '<article class="ls-project"><div class="ls-row"><span class="tok-mark">AR</span><h2><a href="#/project/'+E(p.id)+'">'+E(txt(p.name))+'</a></h2><span class="mono muted">'+E(p.id)+'</span><span class="push">'+tag(p.state)+'</span></div><p class="page-desc">'+E(owner(p))+'</p><div class="ls-grid"><div class="ls-pool"><h3 class="ls-subheading">'+L('Pool assets','池内资产')+'</h3><dl class="ls-metrics"><div><dt>'+L('Pledged tokens','质押代币数量')+'</dt><dd>'+n.valid.length+'</dd></div><div><dt>'+L('Pledged token value','质押代币价值')+'</dt><dd>'+usd(n.value)+'</dd></div><div><dt>'+L('Asset type','资产类型')+'</dt><dd>'+L('Receivables','应收账款')+'</dd></div><div><dt>'+L('Nearest receivable maturity','底层资产最近到期日')+'</dt><dd>'+date(n.pool.filter(t=>t.valid).map(t=>t.due).sort()[0])+'</dd></div></dl></div><div><h3 class="ls-subheading">'+L('Financing','融资信息')+'</h3><dl class="ls-metrics"><div><dt>'+L('Financing request','融资需求金额')+'</dt><dd>'+usd(d?d.amount:0)+'</dd></div><div><dt>'+L('Outstanding financing','已融资余额')+'</dt><dd>'+usd(p.balance)+'</dd></div><div><dt>'+L('Valid until','有效期至')+'</dt><dd>'+date(p.expires)+'</dd></div><div><dt>'+L('Quotes received','已收到报价数')+'</dt><dd>'+(p.quotes||0)+'</dd></div></dl></div></div><div class="ls-row">'+tag(n.grade)+(p.expired?CF.tag('',L('Expired','已到期')):'')+'<span class="push"></span>'+btn('ls-detail',L('View details','查看详情'),p.id)+(S.role==='guest'?btn('signin',L('Sign in now','立即登录')):btn('ls-quote',L('Quote now','立即报价'),p.id,false,!a.quote))+'</div>'+(S.role!=='guest'&&!a.quote?'<p class="hint">'+quoteReason(p)+'</p>':'')+'</article>';}
  function listPage(){const rows=matching();let content=CF.surface({emptyTitle:L('No financing requests yet','暂无融资需求'),emptyDesc:L('Published projects will appear here.','融资项目发布后会出现在这里。'),backTo:'/marketplace'});if(content===null)content=rows.length?'<div class="tablewrap listbox" tabindex="0" role="region" aria-label="'+L('Financing projects','融资项目列表')+'">'+rows.slice(0,S.shown).map(projectCard).join('')+CF.moreFoot(rows.length)+'</div>':CF.empty(L('No results match these filters','筛选无结果'),L('Try widening or clearing the filters.','请放宽筛选条件或清空筛选。'),btn('ls-clear',L('Clear filters','清空筛选')));return '<div class="page-head"><div><h1 class="page-title">'+L('Lending marketplace','借贷广场')+'</h1><p class="page-desc">'+L('Explore financing requests backed by receivables.','浏览以应收账款代币为抵押的融资需求。')+'</p></div>'+(S.role==='asset'?'<div class="page-actions">'+btn('ls-new',L('Create project','创建融资项目'),'',true)+'</div>':'')+'</div>'+guestNotice()+'<section class="card">'+filters()+content+'</section>';}
  function stats(p){const n=D.numbers(p),d=D.current(p)||p.demands.at(-1);return '<div class="stat-row ls-stats">'+[[L('Pledged tokens','质押代币数量'),n.valid.length,L('tokens','张')],[L('Pledged token value','质押代币价值'),CF.fmtAmt(n.value),'USD'],[L('Financing request','融资需求'),CF.fmtAmt(d?d.amount:0),'USD'],[L('Outstanding financing','已融资余额'),CF.fmtAmt(p.balance),'USD'],[L('Pledge ratio','质押率'),'80%','']].map(v=>'<div class="stat"><div class="k">'+v[0]+'</div><div class="v">'+v[1]+'</div><div class="n">'+v[2]+'</div></div>').join('')+'</div>';}
  function demandTable(p){if(!p.demands.length)return CF.empty(L('No financing requests yet','尚未发布融资需求'),'');const tail=pager('demands',p.demands.length);return dataTable([L('Request ID','需求编号'),L('Amount / currency','融资金额 / 币种'),L('Status','状态'),L('Institution / quoted at','机构名称 / 报价时间')],[...p.demands].reverse().slice((pages.demands-1)*5,pages.demands*5).map(d=>[E(d.id),usd(d.amount),tag(d.state)+(d.reason?small(txt(reasons[d.reason])):''),d.institution?E(txt(d.institution))+small(time(d.quoteAt)):'—']))+tail;}
  function actions(p){if(S.role==='guest')return card(L('Actions','操作'),btn('signin',L('Sign in now','立即登录'),'',true));const a=D.actions(p),n=D.numbers(p),d=D.current(p);let global='';if(a.mine){global='<div class="ls-row">'+btn('ls-pledge',L('Add collateral','追加质押'),'',n.grade==='short',!a.pledge)+btn('ls-release',L('Release collateral','解除质押'),'',D.terminal(p),!a.withdraw)+btn('ls-close',L('Close project','关闭项目'),'',false,!a.close)+'</div>';
    if(D.terminal(p))global+='<p class="hint">'+L('This project is closed to new collateral. Released tokens must be collected to return to your wallet.','项目已终结，不能再追加质押；已释放代币需自行提取才会回到钱包。')+'</p>';
    if(!a.withdraw)global+='<p class="hint">'+L('No tokens can be released now. Current withdrawal limit: ','当前暂无可解除质押的代币。可撤回上限：')+usd(n.withdraw)+'</p>';
    const released=D.tokens.filter(t=>t.releasedFrom===p.id&&t.pledge==='released');if(released.length)global+=note(L(released.length+' tokens awaiting collection · ',released.length+' 张待提取 · ')+usd(released.reduce((v,t)=>v+t.value,0))+L('. Collect together; blockchain fees are paid by your company. There is no expiry.','。可批量一次提取，链上费用由本企业承担，无时间限制。'));
  }else global='<p class="muted">'+L('Project information is available for viewing.','可浏览本项目公开信息。')+'</p>';
    const step=d?d.state==='quoted'?2:d.state==='funding'?3:1:p.balance?3:0;
    const stepLabels=[L('Financing request','融资需求'),L('Financing quote','融资报价'),L('Quote confirmation','报价确认'),L('Funding','融资放款')];
    const flow='<div class="ls-steps">'+stepLabels.map((s,i)=>'<section class="ls-step" data-current="'+(i===step)+'"><span class="mono muted">0'+(i+1)+'</span><h3>'+s+'</h3>'+(i===step?(i===0&&a.mine?btn('ls-publish',L('Publish request','发布融资需求'),'',true,!a.publish)+(a.publish?'':'<p class="hint">'+L('No available amount or project term expired.','无可融金额或项目已到期。')+'</p>'):i===1?(a.mine?btn('ls-publish',L('Edit amount','修改金额'))+btn('ls-end-demand',L('Withdraw request','撤下需求')):btn('ls-quote',L('Quote now','立即报价'),p.id,true,!a.quote)+(!a.quote?small(quoteReason(p)):'')):btn('ls-handoff',i===2?L('Review quote','查看报价'):L('View funding','查看放款'),i===2?'quote':'funding',false,(i===2&&!a.mine)))+'':'')+'</section>').join('')+'</div>';
    let repay=p.balance?select('ls-repay','Financing request','需求编号',p.demands.filter(d=>d.state==='funded').map(d=>[d.id,d.id,d.id]))+'<p>'+L('Latest repayment: no repayment recorded. Outstanding financing: ','最近还款：暂无还款记录。已融资余额：')+usd(p.balance)+'</p>'+btn('ls-handoff',L('Repay now','立即还款'),'repay',false,!a.mine):'<p class="muted">'+L('No repayment due.','暂无待还款业务。')+'</p>';
    return card(L('Actions','操作'),'<div class="ls-stack"><section>'+global+'</section><section class="ls-actions">'+flow+'</section><section class="ls-actions"><h3 class="ls-subheading">'+L('Repayment','还款流程')+'</h3>'+repay+'</section></div>');
  }
  function waitLine(start,days){const elapsed=Math.max(0,Math.floor((D.now()-Date.parse(start))/60000));return '<p class="hint">'+L('Waiting: ','已等待：')+Math.floor(elapsed/60)+L(' h ',' 小时 ')+(elapsed%60)+L(' min. Automatic failure at: ',' 分钟。判失败时点：')+time(new Date(Date.parse(start)+days*86400000).toISOString())+'</p>';}
  function resultRows(p){const list=D.executions.filter(e=>e.project===p.id);if(!list.length)return '';return card(L('Per-token execution results','逐张执行结果'),dataTable([L('Token / operation','代币 / 操作'),L('Result','执行结果'),L('Blockchain fee','链上费用'),L('Next step','下一步')],[...list].reverse().map(e=>{
    const t=D.token(e.token),why=e.state==='timeout'?L('Execution results were not returned within the time limit.','链上执行结果未在时限内回写。'):['failure','noFee'].includes(e.state)?L('The transfer was not completed.','代币转移未完成。'):e.state==='processing'?L('The token issuance platform is executing the transfer. This page updates when results arrive.','代币发行平台正在执行，结果回写后本页更新。'):'';
    let next=e.state==='processing'?L('Wait for the result; no new action is available for this token.','请等待结果，该张代币暂不可发起新操作。'):e.late||t.frozen?L('Reconciliation pending. New actions are paused; excluded from coverage.','对账处理中，已暂停新操作，不计入覆盖。'):e.state==='success'?e.kind==='deposit'?L('Counted as collateral; manage in Release collateral.','已计入质押，可通过解除质押入口管理。'):L('Returned to the original holding address.','已转回质押前的原持有地址。'):e.kind==='deposit'?L('Available for a new application to this or another project.','可重新提交到本项目或其他项目。'):e.kind==='redeem'?L('Still awaiting collection. You may retry.','仍为待提取，可重新发起。'):L('Still in the pool. Reserved value restored; you may retry.','仍在池内，预扣已撤销，可重新发起。');
    return [E(e.token)+small(L({deposit:'Deposit',withdraw:'Withdraw',redeem:'Collect'}[e.kind],{deposit:'入池',withdraw:'撤回',redeem:'提取'}[e.kind])),tag(e.state)+(why?small(why):'')+(e.state==='processing'?waitLine(e.at,2):small(time(e.done))),e.fee===null?L('Awaiting fee result','费用待回写'):e.fee===0?L('No fees incurred','未产生费用'):Number(e.fee).toFixed(6)+' ETH'+small(L('Incurred fees are not refunded.','已产生的费用不退回。')),next+(['failure','noFee','timeout'].includes(e.state)&&!t.frozen?'<div class="ls-block">'+btn(e.kind==='deposit'?'ls-pledge':'ls-release',L('Select again','重新选择'))+'</div>':'')];
  })));
  }
  function applicationCard(a){const active=['review','approved','executing'].includes(a.state);return '<article class="ls-selected ls-stack"><div class="ls-row"><b class="mono">'+E(a.id)+'</b>'+tag(a.state)+'<span class="push">'+(a.type==='initial'?L('Initial deposit','建池首笔'):L('Additional collateral','追加质押'))+'</span></div><div class="tiny">'+L('Submitted: ','提交时间：')+time(a.submitted)+(a.decided?' · '+L('Decision: ','结论时间：')+time(a.decided):'')+'</div>'+dataTable([L('Token','代币编号'),L('Quantity / value','数量 / 代币价值'),L('Term / buyer','账期 / 买方')],a.tokens.map(id=>{const t=D.token(id);return [E(id),t.units+' '+E(t.symbol)+small(usd(t.value)),date(t.from)+' → '+date(t.due)+small(E(txt(t.buyer)))];}))+
    (a.state==='review'?waitLine(a.submitted,2)+btn('ls-cancel-app',L('Withdraw application','撤回申请'),a.id):a.state==='approved'?note(L('Approval does not mean the tokens are pledged. Confirm the deposit before the deposit window closes.','审核通过不等于质押成功，请在入池有效期内确认入池。'))+'<p>'+L('Deposit window ends: ','入池有效期至：')+time(new Date(Date.parse(a.decided)+7*86400000).toISOString())+' · '+L('Remaining ','剩余 ')+Math.max(0,Math.ceil((Date.parse(a.decided)+7*86400000-D.now())/3600000))+L(' hours',' 小时')+'</p>'+btn('ls-enter',L('Confirm deposit','确认入池'),a.id,true)+small(L('A decision has been issued; withdrawal is unavailable.','已作出审核结论，不能撤回申请。')):a.state==='executing'?'<p>'+L('See the per-token results below.','请查看逐张执行结果。')+'</p>':a.state==='recorded'?'':note(E(txt(reasons[a.reason]||[a.state==='expired'?'The deposit window has expired.':'Application withdrawn.',a.state==='expired'?'入池有效期已结束。':'申请已撤回。']))+' '+L('No on-chain operation took place and no fees were incurred.','全程未发生链上操作，未产生任何费用。'),a.state==='timeout'||a.state==='rejected'?'danger':'')+btn('ls-pledge',L('Submit a new application','重新提交')) )+'</article>';}
  function applications(p){const list=D.applications.filter(a=>a.project===p.id),active=list.filter(a=>['review','approved','executing'].includes(a.state)),past=list.filter(a=>!active.includes(a));return card(L('Pledge applications','质押审核'),'<div class="ls-stack">'+(active.length?active.map(applicationCard).join(''): '<p class="muted">'+L('No pending applications.','暂无在途申请。')+'</p>')+(past.length?'<details class="ls-history"><summary>'+L('Review history','审核历史')+' ('+past.length+')</summary><div class="ls-stack">'+[...past].reverse().map(applicationCard).join('')+'</div></details>':'')+'</div>')+resultRows(p);}
  function detailPage(){const p=project();if(!p||p.state==='draft'&&!D.mine(p))return publicMissing();const n=D.numbers(p);let surface=CF.surface({emptyTitle:L('No project data','暂无项目数据'),emptyDesc:'',backTo:'/marketplace'});if(surface!==null)return surface;
    let warning='';if(n.gap)warning=note(L('Coverage shortfall: ','覆盖缺口：')+usd(n.gap)+L(' · Additional asset value required: ',' · 需追加资产价值：')+usd(n.gap/0.8)+L('. Additional collateral requires review; submission does not restore coverage immediately.','. 追加质押需先经审核，提交不即时生效。')+'<br>'+L('Triggered: ','触发时间：')+time(p.coverageAt),'warn');
    if(p.state==='draft'&&!n.value&&D.mine(p))warning+=note(L('This project has no valid collateral. Submit a new pledge application before publishing.','本项目暂无有效质押，请重新提交质押申请后再发布。'),'warn');
    return '<div class="ls-stack"><div class="ls-row">'+btn('ls-list',L('← Marketplace','← 返回借贷广场'))+(fromConsole?btn('ls-handoff',L('Return to my console','返回我的控制台'),'console'):'')+'</div><div class="page-head"><div><h1 class="page-title">'+E(txt(p.name))+'</h1><p class="page-desc">'+E(owner(p))+' · <span class="mono">'+E(p.id)+'</span></p><p class="hint">'+L('Published: ','发布时间：')+time(p.published)+' · '+L('Valid until: ','有效期至：')+time(p.expires)+'</p></div><div class="page-actions">'+tag(p.state)+tag(n.grade)+(p.expired?CF.tag('',L('Expired · existing business continues','已到期 · 存量处理中')):'')+'</div></div>'+guestNotice()+warning+stats(p)+card(L('Pledged tokens','质押代币清单'),tokenTable(n.pool,D.mine(p)?'own':'public'))+card(L('Financing requests','融资信息清单'),demandTable(p))+actions(p)+(D.mine(p)?applications(p)+eventHistory(p):'')+'</div>';
  }
  function eventHistory(p){const ev=D.events.filter(e=>e.project===p.id);if(!ev.length)return '';const names={created:['Project created','项目已创建'],submitted:['Application submitted','申请已提交'],approved:['Review approved','审核通过'],rejected:['Review rejected','审核驳回'],applicationWithdrawn:['Application withdrawn','申请已撤回'],reviewTimeout:['Review timed out · no fees','审核超时失败 · 未产生费用'],approvalExpired:['Deposit window expired','入池结论已失效'],executionStarted:['Execution started','已发起执行'],executionSuccess:['Transfer completed','转移完成'],executionFailed:['Transfer failed','转移失败'],executionTimeout:['Execution result timed out','执行回写超时失败'],recheckFailed:['Pre-execution check failed','入池复核不通过'],reconciliation:['Reconciliation pending','对账处理中'],coverageShort:['Coverage shortfall triggered','覆盖不足提醒触发'],coverageRestored:['Coverage restored','覆盖不足提醒解除'],demandVoided:['Request expired due to coverage','融资需求因覆盖不足失效'],published:['Financing request published','融资需求已发布'],amountEdited:['Request amount changed','需求金额已修改'],demandWithdrawn:['Financing request withdrawn','融资需求已撤下'],businessRelease:['Collateral released · awaiting collection','已业务释放 · 待提取'],closed:['Project closed','项目已关闭'],projectExpired:['Project term expired','项目已到期']};return '<details class="ls-history card"><summary>'+L('Activity history','操作记录')+'</summary><div class="card-b">'+dataTable([L('Time','时间'),L('Event','事件'),L('Reference','关联记录')],ev.map(e=>[time(e.at),txt(names[e.key]||[e.key,e.key]),E(e.ref)||'—']))+'</div></details>';}
  function newPage(){if(S.role!=='asset')return publicMissing();const surface=CF.surface({emptyTitle:L('No eligible tokens','暂无可质押代币'),emptyDesc:L('There are no eligible receivables for your entity.','本企业暂无符合条件的应收账款代币。'),backTo:'/marketplace'});return '<div class="ls-form ls-stack"><div>'+btn('ls-list',L('← Marketplace','← 返回借贷广场'))+'</div><h1 class="page-title">'+L('Create financing project','创建融资项目')+'</h1>'+card(L('Project information','基本信息'),field('ls-name','Project name *','项目名称 *',name,'text','maxlength="60" required aria-describedby="ls-name-help"')+'<p class="hint" id="ls-name-help">'+L('1–60 characters','1～60 字符')+'</p>'+select('ls-kind','Token type *','代币类型 *',[['','Choose a type','请选择代币类型'],['ar','Receivables','应收账款'],['other','Other assets · unavailable','其他资产 · 暂不支持',true]],kind,'required')+'<p class="muted">ETH · USD</p>')+card(L('Select tokens','选择可质押代币'),surface!==null?surface:kind?tokenTable(D.candidates(),'select','select'):'<p class="muted">'+L('Choose a token type first.','请先选择代币类型。')+'</p>')+twoSteps()+selectionSummary()+err()+'<div class="ls-row">'+btn('ls-confirm-application',L('Submit pledge application','提交质押申请'),'',true,busy||!selection.length)+btn('ls-list',L('Cancel','取消'))+'</div></div>';}
  function selectionSummary(){const total=selection.map(D.token).filter(Boolean).reduce((v,t)=>v+t.value,0);return '<div class="ls-selected" role="status">'+L('Selected ','已选 ')+selection.length+L(' tokens · ',' 张 · ')+usd(total)+'</div>';}
  function fees(){return '<div class="ls-stack">'+selectionSummary()+dataTable([L('Token','代币'),L('Estimated blockchain fee','预估链上费用')],selection.map(id=>[E(id),'0.000400 ETH']))+note(L('Paid by: your company. Blockchain fees are charged by the blockchain. The platform charges no service fee, does not pay on your behalf and does not refund fees. Incurred fees for a failed token are also non-refundable.','承担方：本企业。链上费用由区块链收取；平台不收取服务费、不代付、不返还。执行失败的那一张，已产生的费用同样不退回。'),'warn')+(D.executions.filter(e=>D.now()-Date.parse(e.at)<86400000).length>5?note(L('Frequent on-chain operations incur more fees. Consider submitting tokens together.','频繁链上操作会产生较多费用，建议批量提交。'),'warn'):'')+'</div>';}
  function open(key,type='modal'){error='';CF.openLayer(type,key);}
  function guarded(p){if(!p||!D.mine(p)){CF.toast(txt(errors.permission));return false;}return true;}
  function openPublish(){const p=project();if(!guarded(p))return;const a=D.actions(p);if(!a.edit&&!a.publish){CF.toast(txt(errors.publishChanged));return;}amount=D.current(p)?String(D.current(p).amount):'';open('publish');}
  function openPledge(){const p=project();if(!guarded(p))return;if(!D.actions(p).pledge){CF.toast(txt(reasons.closed));return;}selection=[];pages.select=1;open('pledge');}
  function openRelease(){const p=project();if(!guarded(p))return;if(!D.actions(p).withdraw){CF.toast(L('Current withdrawal limit: ','当前可撤回上限：')+usd(D.numbers(p).withdraw));return;}selection=[];operation='release';pages.select=1;open('release');}
  function beginDeposit(id){const p=project();if(!guarded(p))return;appId=id;const a=D.applications.find(a=>a.id===id&&a.project===p.id);if(!a)return;try{D.recheck(a);selection=[...a.tokens];operation='deposit';open('fees');}catch(ex){showError(ex);CF.toast(error);}}
  async function commitApplication(){if(busy)return;busy=true;CF.render();await new Promise(r=>setTimeout(r,450));try{if(submitFail)throw Error('submitFailed');const p=D.submit(S.page===NEW?null:project(),selection,name);selection=[];name='';kind='';S.layer=null;goto(p.id);CF.toast(L('Application submitted. No fees incurred.','质押申请已提交，未产生费用。'));}catch(ex){showError(ex);}finally{busy=false;CF.render();}}
  const layers={
    pledge:()=>({title:L('Add collateral','追加质押'),html:'<div class="ls-wide ls-stack">'+twoSteps()+tokenTable(D.candidates(),'select','select')+selectionSummary()+err()+'</div>',foot:btn('closelayer',L('Cancel','取消'))+btn('ls-confirm-application',L('Submit pledge application','提交质押申请'),'',true,!selection.length)}),
    application:()=>({title:L('Confirm pledge application','确认质押申请'),html:'<div class="ls-medium ls-stack"><p>'+L('This submission is a pledge application. No on-chain operation takes place now and no fees are incurred.','本次提交的是质押申请，此刻不发生链上操作、不产生任何费用。')+'</p>'+twoSteps()+selectionSummary()+err()+'</div>',foot:btn('ls-application-back',L('Back','返回'),'',false,busy)+btn('ls-submit',busy?L('Submitting…','提交中…'):L('Confirm submission','确认提交'),'',true,busy)}),
    publish:()=>{const p=project(),d=D.current(p),max=D.numbers(p).free+(d?d.amount:0);return {title:d?L('Edit financing amount','修改融资需求金额'):L('Publish financing request','发布融资需求'),html:'<div class="ls-medium ls-stack"><p>'+L('Available amount: ','当前可融金额：')+'<b class="num">'+usd(max)+'</b></p>'+field('ls-amount','Financing request (USD) *','融资需求金额（USD）*',amount,'text','inputmode="decimal" aria-describedby="ls-amount-error" aria-invalid="'+!!error+'"')+'<div id="ls-amount-error">'+err()+'</div>'+note(L('Publishing makes this request public and reserves the amount. The project term is one year from first publication.','发布后融资需求将公开并占用额度，项目有效期为首次发布起一年。'))+'</div>',foot:btn('closelayer',L('Cancel','取消'))+btn('ls-publish-confirm',L('Confirm','确认'),'',true,busy)};},
    release:()=>{const p=project(),n=D.numbers(p),all=D.tokens.filter(t=>t.pool===p.id&&t.pledge==='pledged'||t.releasedFrom===p.id&&t.pledge==='released');const chosen=selection.map(D.token).filter(t=>t.pledge==='pledged'&&t.valid).reduce((v,t)=>v+t.value,0);return {title:L('Release collateral','解除质押'),html:'<div class="ls-wide ls-stack"><section><h3>'+L('Expired · withdraw at any time','已失效 · 可随时撤回')+'</h3>'+tokenTable(all.filter(t=>!t.valid&&t.pledge==='pledged'),'release','invalid')+'</section><section><h3>'+L('Valid collateral · subject to limit','有效抵押物 · 受额度限制')+'</h3>'+note(L('Current withdrawal limit: ','当前最多可撤回：')+usd(n.withdraw)) +tokenTable(all.filter(t=>t.valid&&t.pledge==='pledged'),'release','valid')+'<p role="status">'+L('Selected valid collateral: ','拟撤回有效抵押物价值：')+usd(chosen)+L(' · Difference: ',' · 超出差额：')+usd(Math.max(0,chosen-n.withdraw))+'</p>'+(chosen>n.withdraw?note(txt(errors.withdrawLimit),'danger'):'')+'</section><section><h3>'+L('Released · awaiting collection','已释放 · 待提取')+'</h3>'+tokenTable(all.filter(t=>t.pledge==='released'),'release','released')+'</section>'+note(L('Tokens are returned to their original holding address. You cannot change the destination.','代币将转回质押前的原持有地址，不能更改目的地址。'))+selectionSummary()+err()+'</div>',foot:btn('closelayer',L('Cancel','取消'))+btn('ls-release-fees',L('Continue','继续'),'',true,!selection.length)};},
    fees:()=>({title:L('Review operation and fees','核对操作与费用'),html:'<div class="ls-wide">'+fees()+err()+'</div>',foot:btn('closelayer',L('Cancel','取消'))+btn('ls-second-confirm',L('Continue','继续'),'',true)}),
    execute:()=>({title:L('Confirm blockchain fees','确认链上费用'),html:'<div class="ls-medium ls-stack">'+fees()+note(L('Confirm that your company will pay the estimated fees for these tokens.','请确认本企业承担本次代币操作的预估链上费用。'),'warn')+err()+'</div>',foot:btn('closelayer',L('Cancel','取消'))+btn('ls-execute',busy?L('Starting…','发起中…'):L('Confirm and start','确认并发起'),'',true,busy)}),
    close:()=>{const p=project(),n=D.numbers(p),a=D.actions(p);return {title:L('Close project','关闭项目'),html:'<div class="ls-medium">'+(a.canClose?note(L('The project will close and its collateral will be released without fees. Tokens remain in the contract until you collect them; collection incurs blockchain fees.','关闭后即时解除质押占用，不产生费用。代币仍在合约内，需自行提取；提取将产生链上费用。'),'warn'):note(txt(errors.cannotClose)+'<br>'+L('Outstanding financing: ','项目融资余额：')+usd(p.balance)+'<br>'+L('Committed demand: ','项目在途金额：')+usd(n.fly),'danger'))+err()+'</div>',foot:btn('closelayer',L('Cancel','取消'))+btn('ls-close-confirm',L('Confirm close','确认关闭'),'',true,!a.canClose)};},
    endDemand:()=>({title:L('Withdraw financing request','撤下融资需求'),html:note(L('The financing request will no longer accept quotes. Its reserved amount will be released. Existing collateral stays in the pool.','撤下后不再接受报价，释放该需求的在途占用，池内质押保留。'),'warn')+err(),foot:btn('closelayer',L('Cancel','取消'))+btn('ls-end-confirm',L('Confirm withdrawal','确认撤下'),'',true)}),
    cancelApp:()=>({title:L('Withdraw pledge application','撤回质押申请'),html:note(L('Tokens will become available for a new application. No on-chain operation or fees have occurred.','撤回后代币可重新提交质押。未发生链上操作，未产生任何费用。'))+err(),foot:btn('closelayer',L('Cancel','取消'))+btn('ls-cancel-confirm',L('Confirm withdrawal','确认撤回'),'',true)}),
    proof:data=>{const t=D.token(data);return {title:L('On-chain receipt','链上凭证'),html:'<p class="ls-raw mono">'+E(t.tx)+'</p><a class="btn-link" target="_blank" rel="noopener noreferrer" href="https://etherscan.io/tx/'+E(t.tx)+'">'+L('View on explorer ↗','在区块浏览器查看 ↗')+'</a><p>'+L('Platform has not verified this transaction.','平台未核验该交易。')+'</p>'+btn('ls-copy',L('Copy','复制'),t.tx),foot:btn('closelayer',L('Close','关闭'))};},
    handoff:data=>({title:L('Continue to the next step','继续办理'),html:'<p>'+L('This action continues in the '+({quote:'quotation',funding:'funding',repay:'repayment',console:'my console'}[data]||'related')+' module.','此操作由'+({quote:'融资报价',funding:'融资放款',repay:'还款',console:'我的控制台'}[data]||'相关')+'模块承接。')+'</p>',foot:btn('closelayer',L('Return','返回'))})
  };
  function footer(){document.getElementById('foot').innerHTML='<div class="ft-in"><p class="ft-mark">Harbour Credit</p><p class="ft-tag">'+L('Cross-border receivables financing on tokenised assets.','基于代币化资产的跨境应收账款融资。')+'</p><nav class="ft-links">'+['Terms','Privacy','Risk disclosure','Contact'].map((t,i)=>'<a href="#" data-act="ls-handoff">'+L(t,['服务协议','隐私声明','风险揭示','联系我们'][i])+'</a>').join('')+'</nav><div class="ft-meta"><span>'+L('Demonstration data — no real companies, amounts or transactions','演示数据 —— 非真实企业、金额或链上交易')+'</span><span>'+E(S.tz||'UTC')+'</span></div></div>';}
  function tools(){if(!S.demo)return;const el=document.getElementById('demoPanel');if(el.querySelector('.ls-review'))return;const end=el.querySelector('.grp');if(end)end.remove();let box=document.createElement('div');box.className='ls-review';box.innerHTML='<h5>'+L('External events · review only','外部事件 · 仅供评审')+'</h5>'+select('ls-demo-project','Open project','打开项目',D.projects.filter(p=>p.state!=='draft'||D.mine(p)).map(p=>[p.id,p.name[0],p.name[1]]),project()?.id||D.projects[0].id)+btn('ls-demo-project',L('Open','打开'))+'<div class="ls-block ls-row">'+btn('ls-demo-event',L('Approve','审核通过'),'approve')+btn('ls-demo-event',L('Reject','驳回'),'reject')+btn('ls-demo-event',L('+2 days','推进 2 天'),'twoDays')+btn('ls-demo-event',L('+8 days','推进 8 天'),'eightDays')+'</div>'+select('ls-outcome','Execution result','执行结果',[['success','All return success','逐张成功'],['mixed','Two success, one failure','2 成 1 败'],['failure','Execution failed · charged','执行失败 · 已产生费用'],['noFee','Execution failed · no fee','执行失败 · 零费用'],['wait','Await results','等待回写']],outcome)+btn('ls-demo-event',L('Return results','回写结果'),'results')+select('ls-gate','Next execution attempt','下次发起执行',[['normal','Available','正常'],['unavailable','Execution entry unavailable','执行入口不可用'],['nogas','Insufficient fee balance','费用余额不足'],['recheck','Recheck failed','复核不通过']],executionGate)+'<div class="ls-row">'+btn('ls-demo-event',L('Late success','迟到成功回写'),'late')+btn('ls-demo-event',L('Token expires','代币失效'),'expire')+btn('ls-demo-event',L('Amount changes','额度变化'),'amountChange')+btn('ls-demo-event',L('Permission rejection','越权写入反馈'),'deniedWrite')+btn('ls-demo-event',L('From my console','从控制台进入'),'fromConsole')+'</div><label class="ls-check"><input id="ls-submit-fail" type="checkbox" '+(submitFail?'checked':'')+'>'+L('Submission failure','提交失败')+'</label><p class="why">'+L('Simulated events and fees. Wallet/signature hosting and real cross-platform connections are not implemented. +2 days advances the demo clock; the deadline check runs automatically.','演示事件与费用，未实现钱包签名及真实跨平台连接。推进 2 天只改变演示时钟，到期判定自动运行。')+'</p>'+btn('ls-demo-event',L('Reset demonstration','重置演示数据'),'reset');el.appendChild(box);}
  function enhance(){footer();tools();document.querySelectorAll('.nav-item').forEach(a=>{if(a.getAttribute('href')==='#/marketplace'&&[LIST,DETAIL,NEW].includes(S.page))a.setAttribute('aria-current','page');});if(!document.querySelector('.ls-demo-mark')){const el=document.createElement('p');el.className='ls-demo-mark';el.textContent=L('Demonstration data','演示数据');document.getElementById('content').prepend(el);}if(refocus){document.getElementById(refocus)?.focus();refocus=null;}}
  function externalEvent(value){const p=project()||D.projects[0];if(value==='reset'){D.seed();S.layer=null;selection=[];location.hash='#/marketplace';return;}
    if(value==='approve'||value==='reject'){if(!D.review(p,value))CF.toast(L('No pending application in this project.','本项目暂无待审核申请。'));}
    if(value==='twoDays'||value==='eightDays')D.offset+=(value==='twoDays'?2:8)*86400000;
    if(value==='results'){D.executions.filter(e=>e.project===p.id&&e.state==='processing').forEach((e,i)=>{if(outcome!=='wait')D.result(e,outcome==='mixed'?(i%3===2?'failure':'success'):outcome);});}
    if(value==='late'){const e=[...D.executions].reverse().find(e=>e.project===p.id&&e.state==='timeout');if(e)D.result(e,'late');else CF.toast(L('First demonstrate an execution timeout.','请先演示执行超时。'));}
    if(value==='expire'||value==='amountChange'){const t=D.numbers(p).valid.at(-1);if(t){t.valid=false;D.recompute(p);}if(value==='amountChange')CF.toast(L('Available amounts have been refreshed.','额度已变化，请核对最新数值。'));}
    if(value==='fromConsole'){fromConsole=true;try{sessionStorage.setItem('hc-ls-origin','console');}catch(_){}goto(p.id);}
    if(value==='deniedWrite')CF.toast(txt(errors.permission));D.sweep();D.save();
  }
  CF.define({id:'lending-marketplace',dict:{en:{navHome:'Home',navAssets:'Asset marketplace',navPlaza:'Lending marketplace',navConsole:'My console',lsDetail:'Financing request',lsNew:'Create project'},zh:{navHome:'首页',navAssets:'资产广场',navPlaza:'借贷广场',navConsole:'我的控制台',lsDetail:'融资需求详情',lsNew:'创建融资项目'}},layers,content(id){D.sweep();setTimeout(enhance,0);if(id===NEW)return newPage();if(id===DETAIL)return detailPage();return listPage();},onAct(act,v){
    const p=project();
    try{
      if(act==='ls-list'){S.layer=null;location.hash='#'+CF.ENTRY[LIST];return true;}
      if(act==='ls-new'){if(S.role!=='asset')throw Error('permission');selection=[];name='';kind='';error='';pages.select=1;location.hash='#/project/new';return true;}
      if(act==='ls-detail'){pages.tokens=pages.demands=1;goto(v);return true;}
      if(act==='ls-filter'){['type','vmin','vmax','amin','amax','status','quote','expiry','coverage','sort'].forEach(k=>filter[k]=document.getElementById('ls-'+k).value);writeFilters();return true;}
      if(act==='ls-clear'){filter={};S.st='default';writeFilters();return true;}
      if(act==='ls-page'){const [k,n]=v.split(':');pages[k]=Math.max(1,+n);return true;}
      if(act==='ls-pledge'){openPledge();return true;}
      if(act==='ls-confirm-application'){
        if(S.page===NEW&&(!name.trim()||[...name.trim()].length>60||kind!=='ar')){error=txt(errors.name);refocus='ls-name';return true;}
        if(!selection.length)throw Error('selectionChanged');open('application');return true;
      }
      if(act==='ls-application-back'){S.layer=S.page===NEW?null:{type:'modal',key:'pledge'};error='';return true;}
      if(act==='ls-submit'){commitApplication();return true;}
      if(act==='ls-publish'){openPublish();return true;}
      if(act==='ls-publish-confirm'){const max=D.numbers(p).free+(D.current(p)?.amount||0),n=Number(amount);if(!/^\d+(\.\d{1,2})?$/.test(amount)||n<=0||n>max){error=txt(errors.amount)+' '+L('Available: ','可融金额：')+usd(max)+L(' · Excess: ',' · 超出差额：')+usd(Math.max(0,n-max)||0);refocus='ls-amount';return true;}D.publish(p,n,!!D.current(p));CF.closeLayer();CF.toast(L('Financing request saved.','融资需求已保存。'));return true;}
      if(act==='ls-release'){openRelease();return true;}
      if(act==='ls-release-fees'){const n=D.numbers(p),total=selection.map(D.token).filter(t=>t.valid&&t.pledge==='pledged').reduce((v,t)=>v+t.value,0);if(total>n.withdraw)throw Error('withdrawLimit');operation='release';open('fees');return true;}
      if(act==='ls-enter'){beginDeposit(v);return true;}
      if(act==='ls-second-confirm'){open('execute');return true;}
      if(act==='ls-execute'){
        if(busy)return true;if(executionGate==='unavailable'||executionGate==='nogas'){error=executionGate==='unavailable'?L('Unable to start now. No fees incurred. Please try again later.','当前无法发起，本次未产生任何费用，可稍后重试。'):L('Insufficient balance for blockchain fees. No execution was started and no fees were incurred.','费用余额不足，未发起执行，未产生任何费用。');return true;}
        if(executionGate==='recheck'&&operation==='deposit'){D.token(selection[0]).valid=false;D.recheck(D.applications.find(a=>a.id===appId));}
        D.execute(p,operation==='deposit'?'deposit':'release',selection,operation==='deposit'?appId:null);S.layer=null;selection=[];CF.toast(L('Execution started. Results will appear per token.','已发起执行，结果将逐张更新。'));return true;
      }
      if(act==='ls-close'){if(guarded(p))open('close');return true;}
      if(act==='ls-close-confirm'){D.close(p);CF.closeLayer();return true;}
      if(act==='ls-end-demand'){if(guarded(p))open('endDemand');return true;}
      if(act==='ls-end-confirm'){D.endDemand(p);CF.closeLayer();return true;}
      if(act==='ls-cancel-app'){if(!guarded(p))return true;appId=v;open('cancelApp');return true;}
      if(act==='ls-cancel-confirm'){D.cancelApplication(D.applications.find(a=>a.id===appId));CF.closeLayer();return true;}
      if(act==='ls-proof'){CF.openLayer('modal','proof',v);return true;}
      if(act==='ls-copy'){if(navigator.clipboard)navigator.clipboard.writeText(v).then(()=>CF.toast(L('Copied.','已复制。'))).catch(()=>CF.toast(L('Select the value and copy it.','请选中凭证手动复制。')));else CF.toast(L('Select the value and copy it.','请选中凭证手动复制。'));return true;}
      if(act==='ls-quote'){const q=D.project(v);if(!D.actions(q).quote){CF.toast(quoteReason(q));return true;}CF.openLayer('modal','handoff','quote');return true;}
      if(act==='ls-handoff'){CF.openLayer('modal','handoff',v);return true;}
      if(act==='ls-demo-project'){const id=document.getElementById('ls-demo-project').value;S.demo=false;S.st='default';goto(id);return true;}
      if(act==='ls-demo-event'){externalEvent(v);return true;}
    }catch(ex){showError(ex);if(!S.layer)CF.toast(error);return true;}
    return false;
  }});
  document.addEventListener('input',e=>{if(e.target.id==='ls-name')name=e.target.value;if(e.target.id==='ls-amount')amount=e.target.value;});
  document.addEventListener('change',e=>{
    const el=e.target;if(el.id==='ls-kind'){kind=el.value;selection=[];pages.select=1;refocus=el.id;CF.render();}
    if(el.dataset.token){const id=el.dataset.token;selection=el.checked?[...new Set([...selection,id])]:selection.filter(x=>x!==id);CF.render();setTimeout(()=>document.querySelector('[data-token="'+id+'"]')?.focus(),0);}
    if(el.id==='ls-outcome')outcome=el.value;if(el.id==='ls-gate')executionGate=el.value;if(el.id==='ls-submit-fail')submitFail=el.checked;
    if(el.id==='ls-sort'){filter.sort=el.value;writeFilters();refocus=el.id;CF.render();}
  });
  document.addEventListener('click',e=>{
    savePosition();const a=e.target.closest('a');if(a&&['#/','#/assets','#/console'].includes(a.getAttribute('href'))){e.preventDefault();if(a.getAttribute('href')==='#/assets'&&document.querySelector('script[src]')){location.href='../资产广场/资产广场.html#/assets';return;}CF.openLayer('modal','handoff',a.getAttribute('href')==='#/console'?'console':'other');}
    const el=e.target.closest('[data-act]');if(el&&el.dataset.act==='clearfilter')filter={};
    if(el&&el.dataset.act==='role'){S.layer=null;error='';selection=[];}
    if(el&&el.dataset.act==='closelayer'&&busy){e.stopImmediatePropagation();return;}
  });
  document.addEventListener('keydown',e=>{
    const dialog=document.querySelector('#layers [role="dialog"]');if(!dialog)return;
    if(e.key==='Escape'&&busy){e.stopImmediatePropagation();return;}
  });
  window.addEventListener('hashchange',()=>{savePosition();syncRoute();error='';pages.tokens=pages.demands=1;const isList=/^\/marketplace(?:\?|$)/.test(path());if(isList){listRoute=path();filter=readFilters(listRoute);}pendingAction=new URLSearchParams(path().split('?')[1]||'').get('action');setTimeout(()=>{if(isList)restorePosition();else{deepAction();window.scrollTo(0,0);}},0);});
  function deepAction(){if(!pendingAction)return;const action=pendingAction;pendingAction=null;const p=project();if(!p||!D.mine(p))return;if(action==='pledge')openPledge();else if(action==='publish')openPublish();else if(action==='withdraw'||action==='redeem')openRelease();else if(action==='enter_pool'){const a=D.applications.find(a=>a.project===p.id&&a.state==='approved');if(a)beginDeposit(a.id);else CF.toast(txt(errors.approvalChanged));}}
  // The timer only updates simulated deadline outcomes. It never performs network work.
  setInterval(()=>{if(D.sweep())CF.render();},1000);
  if(!path()||path()==='/')location.hash='#/marketplace';syncRoute();if(/^\/marketplace(?:\?|$)/.test(path())){listRoute=path();filter=readFilters(listRoute);}pendingAction=new URLSearchParams(path().split('?')[1]||'').get('action');CF.boot();setTimeout(()=>{deepAction();window.scrollTo(0,0);},0);
})(window.CF);
