/* WS-354 / L8. Reuses accepted quotes and L7 receipts; all execution is local demonstration. */
(function(CF){
  'use strict';
  ['P-LS-09','P-LS-10','P-LS-91'].forEach(id=>CF.PAGES[id]={end:'asset',layout:'portal',parent:'P-LS-02',presentation:'drawer'});
  const S=CF.S,L=CF.L,E=CF.esc,D=CF.LS,Q=CF.CQ,V=CF.LSView,DAY=86400000,H=3600000;
  const b=(act,text,v='',primary=false,off=false)=>'<button type="button" class="btn'+(primary?' primary':'')+'" data-act="rp-'+act+'" data-v="'+E(v)+'"'+(off?' disabled':'')+'>'+text+'</button>';
  const dl=rows=>'<dl class="dl">'+rows.map(([k,v])=>'<dt>'+k+'</dt><dd>'+v+'</dd>').join('')+'</dl>';
  const section=(title,body)=>'<section class="rp-section"><h3>'+title+'</h3>'+body+'</section>';
  const amount=(n,c='USD')=>CF.fmtAmt(n)+' '+c;
  const iso=n=>new Date(n).toISOString(),day=n=>iso(n).slice(0,10),date=s=>CF.fmtDate(s),time=s=>s?CF.fmtTime(s):'—';
  const round=n=>Math.round((n+Number.EPSILON)*100)/100;
  let selected='',seq=1,form={},errors={},busy=false,epoch=0,origin=null,back=null,askKind='',agree=false,returnUI=null,errorFocus='',lastRole=S.role,lastHash=location.hash,clockOverride=Number(Q.data().repaymentClock)||0,fail=false,load='ready',uploadFail=false;
  let activeKey='',serial=0,filter='',previewFile=null,savedUI=null,confirmReturn=null,discardReturn=null,externalReturn=null,resultNotice='';
  const listViews=new Map();
  const expanded=new Set();
  const drafts=new Map(),files=new Map();let events=Q.data().repaymentEvents||(Q.data().repaymentEvents=[]);
  const now=()=>clockOverride||CF.L7.now();
  const quote=id=>Q.data().quotes.find(q=>q.id===id),deal=id=>CF.L7.deals.find(x=>x.id===(id||selected)),plan=()=>quote(selected)?.l8,period=()=>plan()?.periods.find(p=>p.seq===seq);
  const party=x=>!!x&&Q.related(quote(x.id));
  const funder=x=>x.fund==='fund-b'?L('Demo Capital B','演示资金机构 B'):L('Demo Capital A','演示资金机构 A');
  const status=p=>L(...{due:['Awaiting repayment','待还款'],pending:['Awaiting confirmation','待还款确认'],settled:['Settled','已结清']}[p.state]);
  const badge=p=>CF.tag(p.state==='settled'?'ok':p.state==='pending'?'accent':'',status(p));
  const overdue=p=>p.record?p.record.overdue:Math.max(0,Math.floor((Date.parse(day(now()))-Date.parse(p.due))/DAY));
  const confirmed=x=>!!x&&['confirmed','settled'].includes(x.state)&&x.record;
  const available=p=>CF.L7.deals.filter(x=>x.project===p.id&&confirmed(x));
  const ref=x=>E(x.request)+'<br><span class="hint mono">'+E(x.id)+' · '+E(x.record?.id||'—')+'</span>';
  function addMonths(s,n){const [y,m,d]=s.split('-').map(Number),first=new Date(Date.UTC(y,m-1+n,1)),last=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate();return day(Date.UTC(first.getUTCFullYear(),first.getUTCMonth(),Math.min(d,last)));}
  function build(start,end,principal,rate,fx){
    if(!start||!end||end<=start||!Number.isFinite(+fx)||+fx<=0)return [];
    const marks=[];for(let k=1;k<500;k++){const t=addMonths(start,3*k);if(t>=end)break;marks.push(t);}
    if(marks.length&&addMonths(marks.at(-1),3)>end)marks.pop();
    const bounds=[start,...marks,end];return bounds.slice(1).map((due,i)=>{const days=(Date.parse(due)-Date.parse(bounds[i]))/DAY,interest=round(principal*(+rate/100)*days/360),capital=i===bounds.length-2?principal:0;return {seq:i+1,from:bounds[i],due,days,principal:capital,interest,total:round(capital+interest),settlement:round((capital+interest)/fx),open:Date.parse(due)-3*DAY,state:'due',record:null};});
  }
  function event(kind,x,p,owners){owners.forEach(owner=>{const id=[kind,x.id,p?.id||'',owner].join('|');if(events.some(e=>e.id===id))return;events.push({id,kind,deal:x.id,seq:p?.seq,owner,at:iso(now())});Q.save();});}
  function ensure(){events=Q.data().repaymentEvents||(Q.data().repaymentEvents=[]);let changed=false;CF.L7.deals.filter(confirmed).forEach(x=>{const q=quote(x.id);if(!q.l8&&x.plan!=='waiting'){
    const start=day(Date.parse(x.record.at)),end=day(Date.parse(q.repay));const periods=build(start,end,x.amount,x.rate,x.fx.value);
    if(!periods.length)return;
    periods.forEach(p=>p.id='RP'+day(Date.parse(x.confirmedAt)).replaceAll('-','')+String(++serial).padStart(6,'0'));
    q.l8={start,end,at:x.confirmedAt,periods,settledAt:null};event('final',x,null,['asset']);changed=true;
  }});if(changed)Q.save();}
  function nearest(x){const ps=[...(quote(x.id)?.l8?.periods||[])].sort((a,b)=>a.due.localeCompare(b.due)||a.seq-b.seq);return ps.find(p=>p.state==='due')||ps.find(p=>p.state==='pending')||ps.at(-1);}
  function choose(id,n){const x=deal(id);if(!x||!confirmed(x))return false;selected=id;seq=n||nearest(x)?.seq||1;return true;}
  function can(kind){const x=deal(),p=period();return !!(x&&p&&party(x)&&(kind==='pay'?S.role==='asset'&&p.state==='due'&&now()>=p.open:S.role==='fund'&&p.state==='pending'));}
  function denied(){CF.toast(L('This action is not available for your account.','当前账号无权办理此操作。'));}
  function ids(){return deal().request+' · '+selected+' · '+(period()?.id||'');}
  function support(){return '<div class="rp-support"><b>'+L('Need help?','需要帮助？')+'</b><p>'+L('Contact your counterparty if funds have not arrived. Customer support email is currently unavailable.','款项尚未到账时请先联系对方。客服邮箱暂不可用。')+'</p><p class="mono">'+E(ids())+'</p>'+b('copy',L('Copy reference numbers','复制业务编号'),ids())+'</div>';}
  function clock(p){if(p.state!=='pending')return '';const due=Date.parse(p.record.at)+168*H,left=Math.max(0,due-now()),label=left?L('Remaining: ','剩余：')+(left<24*H?Math.ceil(left/60000)+L(' minutes',' 分钟'):Math.ceil(left/H)+L(' hours',' 小时')):L('Confirmation overdue: ','已超过还款确认时限：')+Math.floor((now()-due)/DAY)+L(' days',' 天');return CF.note(left&&left<24*H?'warn':'',label+'<br>'+L('Confirmation due: ','确认截止：')+time(iso(due)))+(!left?'<p class="hint">'+L('Overdue days remain frozen. Confirmation is still available; the platform will not confirm automatically.','逾期天数保持冻结；仍可确认，平台不会自动或代为确认。')+'</p>':'');}
  function periodInfo(p){return '<div class="rp-period"><div class="rp-row"><b>'+L('Instalment ','第 ')+p.seq+' / '+plan().periods.length+L('',' 期')+'</b>'+badge(p)+'</div><p class="hint">'+L('Due ','应还日 ')+date(p.due)+'</p><div class="rp-amount mono">'+amount(p.total)+'</div><div>'+L('Settlement amount','结算金额')+' <b class="mono">'+amount(p.settlement,deal().ccy)+'</b></div>'+(overdue(p)?'<p class="rp-overdue">'+L('Overdue ','逾期 ')+overdue(p)+L(' days',' 天')+(p.record?L(' · Frozen',' · 已冻结'):L(' · Stops increasing when submission succeeds',' · 提交成功后停止累加'))+'</p>':'')+'</div>';}
  function panel(p){ensure();const list=available(p);if(!list.length)return {body:CF.empty(L('No repayments yet','暂无还款信息'),L('Repayment schedules and actions become available after receipt is confirmed.','确认到账后可查看还款计划和办理还款。')),primary:S.role==='guest'?'<button class="btn primary" data-act="signin">'+L('Sign in now','立即登录')+'</button>':'',secondary:''};if(!list.some(x=>x.id===selected))choose(list[0].id);const x=deal(),r=nearest(x),p8=plan();
    const selection=list.length===1?'<div class="rp-reference">'+ref(x)+'</div>':'<div class="field"><label for="rp-search">'+L('Find a business by any reference number','按申请、业务或放款编号查找')+'</label><input id="rp-search" class="inp" value="'+E(filter)+'"><div id="rp-options" class="rp-options">'+options(list)+'</div></div>';
    const body='<section id="repayment" class="rp-panel"><h3>'+L('Repayment','还款流程')+'</h3>'+selection+'<p>'+E(funder(x))+' · '+x.ccy+'</p>'+(!p8?CF.note('',L('Repayment plan is being generated.','还款计划生成中。')):p8.settledAt?CF.note('ok',L('This financing business is settled.','本笔融资业务已结清。'))+(dl([[L('Settled at','结清时间'),time(p8.settledAt)],[L('Principal repaid','累计已还本金'),amount(x.amount)],[L('Interest repaid','累计已还利息'),amount(p8.periods.reduce((n,p)=>n+p.interest,0))]])):r?periodInfo(r)+clock(r):'')+(p8?.periods.some(p=>p.state==='pending')?support():'')+(p8?.settledAt?'<p class="hint">'+L('Collateral release follows the project result. Review the project’s collateral status.','质押释放以项目结果为准，请查看项目质押状态。')+'</p>':'')+(p.l8ReleasePending?CF.note('',L('Collateral release result is not yet available.','质押释放结果暂未取得。')):'')+'</section>';
    let primary='',secondary='';secondary=b('detail',L('View repayment details','查看还款详情'),x.id);if(S.role==='guest')primary='<button class="btn primary" data-act="signin">'+L('Sign in now','立即登录')+'</button>';else if(p8){secondary=b('detail',L('View repayment details','查看还款详情'),x.id);if(party(x)&&S.role==='asset'&&p8.periods.some(p=>p.state==='due'))primary=b('open',L('Record repayment','立即还款'),'pay',true);else if(party(x)&&S.role==='fund'&&p8.periods.some(p=>p.state==='pending'))primary=b('open',L('Confirm repayment received','确认收到还款'),'confirm',true);else if(party(x)&&p8.periods.some(p=>p.record)&&!p8.settledAt)primary=b('open',L('View repayment record','查看还款记录'),'record');}
    return {body,primary,secondary};
  }
  function options(list){const found=list.filter(x=>[x.id,x.request,x.record.id].some(s=>s.toLowerCase().includes(filter.toLowerCase())));return found.length?found.map(x=>'<button type="button" class="rp-option" data-act="rp-select" data-v="'+E(x.id)+'" aria-pressed="'+(x.id===selected)+'">'+ref(x)+'</button>').join(''):'<p role="status">'+L('No matching business','没有匹配业务')+'</p>'+b('clear',L('Clear search','清空搜索'));}
  function repaymentState(x){const p8=quote(x.id)?.l8;return !p8?CF.tag('',L('Plan generating','计划生成中')):p8.settledAt?CF.tag('ok',L('Settled','已结清')):CF.tag('accent',L('Repaying','还款中'));}
  function recordTable(project){ensure();if(!listViews.has(project.id))listViews.set(project.id,{query:'',page:1});const view=listViews.get(project.id),all=available(project).filter(x=>[x.request,x.id,x.record?.id,funder(x)].some(v=>String(v||'').toLowerCase().includes(view.query.toLowerCase()))).sort((a,b)=>Date.parse(b.confirmedAt)-Date.parse(a.confirmedAt)||b.id.localeCompare(a.id)),pages=Math.max(1,Math.ceil(all.length/5));view.page=Math.min(view.page,pages);const rows=all.slice((view.page-1)*5,view.page*5),heads=[L('Application / funder','融资申请 / 出资机构'),L('Current instalment','本期应还'),L('Due date','应还日'),L('Status','业务状态'),L('Receipt confirmed','到账确认时间')];
    return '<div class="rp-list-filters"><label class="sr-only" for="rp-list-query-'+E(project.id)+'">'+L('Find application, business or loan','搜索申请、业务或放款编号')+'</label><input class="inp" id="rp-list-query-'+E(project.id)+'" placeholder="'+L('Application / business / disbursement reference','申请 / 业务 / 放款编号')+'" value="'+E(view.query)+'">'+b('table-filter',L('Search','筛选'),project.id)+b('table-reset',L('Reset','重置'),project.id)+'</div><div class="rp-record-scroll"><table class="tbl rp-record-table"><thead><tr>'+heads.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(x=>{const p8=quote(x.id)?.l8,p=p8?.periods.filter(p=>p.state==='due').sort((a,b)=>a.due.localeCompare(b.due)||a.seq-b.seq)[0],pending=p8?.periods.filter(p=>p.state==='pending')||[];return '<tr data-act="rp-detail" data-v="'+E(x.id)+'" tabindex="0" role="button" aria-label="'+L('View repayment ','查看还款 ')+E(x.request)+'"><td><strong>'+E(x.request)+'</strong><div class="hint">'+E(funder(x))+'</div></td><td>'+(p?'<b class="mono">'+amount(p.settlement,x.ccy)+'</b>'+(x.ccy!=='USD'?'<div class="hint">'+amount(p.total)+'</div>':'')+'<div class="hint">'+L('Instalment ','第 ')+p.seq+' / '+p8.periods.length+L('',' 期')+'</div>':p8?L('No instalments awaiting repayment','暂无待还期次'):'—')+'</td><td>'+(p?date(p.due)+(now()<p.open?'<div class="hint">'+L('Opens ','开启于 ')+date(iso(p.open))+'</div>':overdue(p)?'<div class="rp-overdue">'+L('Overdue ','逾期 ')+overdue(p)+L(' days',' 天')+'</div>':''):'—')+'</td><td>'+repaymentState(x)+(pending.length?'<div class="hint">'+pending.length+L(' awaiting confirmation',' 期待还款确认')+'</div>':'')+'</td><td>'+time(x.confirmedAt)+'</td></tr>';}).join('')+'</tbody></table></div>'+(!rows.length?CF.empty(L('No repayment information','暂无还款信息'),view.query?L('Try another reference number.','请尝试其他编号。'):L('Confirmed disbursements appear here, including plans being generated.','确认到账后可查看还款计划和办理还款。')):'')+'<div class="rp-pagination"><span class="hint">'+all.length+L(' businesses',' 笔业务')+' · '+L('5 per page','每页 5 条')+'</span><div>'+b('table-page',L('Previous','上一页'),project.id+'|'+(view.page-1),false,view.page===1)+' <span>'+view.page+' / '+pages+'</span> '+b('table-page',L('Next','下一页'),project.id+'|'+(view.page+1),false,view.page===pages)+'</div></div>';
  }
  function detail(){const x=deal(),p8=plan();if(!x)return {title:L('Repayment unavailable','还款业务不可用'),html:CF.empty(L('Business not found','未找到业务'),''),foot:b('back',L('Close','关闭'))};
    let body=(resultNotice?CF.note('ok',E(resultNotice)):'')+'<header class="rp-detail-heading"><b class="mono">'+E(x.request)+'</b>'+repaymentState(x)+'<p>'+E(funder(x))+' · '+E(x.ccy)+'</p><p class="hint mono">'+E(x.id)+' · '+E(x.record.id)+'</p></header>';
    let foot=b('back',externalReturn?L('Back','返回'):L('Close','关闭'));
    if(load==='loading')body+='<p role="status">'+L('Loading repayment information…','正在加载还款信息…')+'</p>';else if(load==='error')body+=CF.empty(L('Unable to load repayment information','还款信息加载失败'),'',b('retry',L('Retry','重试')));else if(!p8){body+=CF.note('',L('Receipt is confirmed. The repayment schedule is being generated.','已确认到账，还款计划生成中。'))+dl([[L('Confirmed at','到账确认时间'),time(x.confirmedAt)],[L('Disbursed amount','放款金额'),amount(x.settlement,x.ccy)]]);if(party(x))body+=section(L('Funder’s repayment account','资金方还款收款账户'),account());}
    else{const due=p8.periods.filter(p=>p.state==='due').sort((a,b)=>a.due.localeCompare(b.due)||a.seq-b.seq)[0],pending=p8.periods.filter(p=>p.state==='pending');body+=section(L('Current repayment','本期还款'),p8.settledAt?CF.note('ok',L('All instalments are settled.','本笔全部期次已结清。'))+dl([[L('Settled at','结清时间'),time(p8.settledAt)]]):due?periodInfo(due)+(now()<due.open?CF.note('',L('Repayment opens ','还款入口开启时间：')+time(iso(due.open))):''):CF.note('',L('No instalments awaiting repayment.','暂无待还期次。')));
      if(pending.length)body+=section(L('Awaiting confirmation','待还款确认'),pending.map(p=>'<div class="rp-pending-item"><div class="rp-row"><b>'+L('Instalment ','第 ')+p.seq+L('',' 期')+' · '+amount(p.settlement,x.ccy)+'</b>'+badge(p)+'</div>'+clock(p)+(party(x)?b('period-action',S.role==='fund'?L('Review and confirm','核对并确认还款'):L('View submitted record','查看已提交记录'),(S.role==='fund'?'confirm':'record')+'|'+p.seq,S.role==='fund'):'')+'</div>').join(''));
      body+=section(L('Repayment schedule','还款计划'),schedule());if(party(x))body+=section(L('Funder’s repayment account','资金方还款收款账户'),account())+section(L('Repayment records','还款记录'),p8.periods.some(p=>p.record)?p8.periods.filter(p=>p.record).map(p=>'<div class="rp-history-item"><div><b>'+L('Instalment ','第 ')+p.seq+L('',' 期')+'</b> · '+amount(p.settlement,x.ccy)+'<p class="hint">'+time(p.record.at)+'</p>'+badge(p)+'</div>'+b('record',L('View record','查看记录'),p.seq)+'</div>').join(''):CF.empty(L('No repayment records','暂无还款记录'),''));
      if(party(x)&&S.role==='asset'&&due)foot+=b('period-action',L('Record repayment','立即还款'),'pay|'+due.seq,true,now()<due.open);else if(party(x)&&S.role==='fund'&&pending.length)foot+=b('period-action',L('Confirm repayment received','确认收到还款'),'confirm|'+pending[0].seq,true);if(p8.settledAt)body+='<p class="hint">'+L('Collateral release follows the project status. Released tokens must still be collected.','质押释放以项目状态为准；已释放代币仍需提取。')+'</p>';
    }
    body+=section(L('Related business','关联业务'),'<div class="rp-row">'+b('related',L('Financing application','融资申请'),'application')+b('related',L('Disbursement details','融资放款'),'loan')+'</div>');if(S.role==='guest')foot+='<button class="btn primary" data-act="signin">'+L('Sign in now','立即登录')+'</button>';else if(!party(x))body+='<p class="hint">'+L('Account, payment records and documents are visible only to the financing parties.','收款账户、还款记录和凭证仅本业务双方可见。')+'</p>';
    return {title:L('Repayment details','还款详情'),html:'<div class="rp-drawer" data-kind="detail">'+body+'</div>',foot};
  }
  function schedule(){const x=deal(),p8=plan(),current=period(),headers=[L('Instalment','期次'),L('Due date','应还日'),L('Total due (USD)','应还合计（USD）'),L('Settlement amount','结算金额'),L('Status','期次状态'),L('Overdue days','逾期天数')];
    return '<div class="rp-plan-title"><b>'+E(x.request)+' · '+E(funder(x))+'</b><p class="mono hint">'+E(x.id)+' · '+E(x.record.id)+' · '+x.ccy+'</p><p class="hint">'+L('Finalized ','定稿时间 ')+time(p8.at)+'</p></div><p>'+L('Annual interest rate: ','年化利率：')+x.rate+'% · ACT/360</p><p class="hint">'+L('Simple interest; actual days ÷ 360. Start included, due date excluded. Interest starts ','年化单利，实际天数 ÷ 360；算头不算尾。起息日 ')+date(p8.start)+'</p><div class="rp-plan-scroll" role="region" tabindex="0" aria-label="'+L('Final repayment schedule','定稿还款计划')+'"><table class="tbl rp-plan"><thead><tr>'+headers.map(h=>'<th scope="col">'+h+'</th>').join('')+'</tr></thead><tbody>'+p8.periods.map(p=>'<tr '+(p===current?'class="rp-current" aria-current="true"':'')+'><th scope="row"><button class="btn ghost sm" data-act="rp-expand" data-v="'+p.seq+'" aria-expanded="'+expanded.has(selected+':'+p.seq)+'" aria-controls="rp-breakdown-'+p.seq+'">'+p.seq+' / '+p8.periods.length+' ＋</button></th><td>'+date(p.due)+'</td><td class="mono">'+CF.fmtAmt(p.total)+'</td><td class="mono">'+amount(p.settlement,x.ccy)+'</td><td>'+badge(p)+(p.record&&party(x)?'<br>'+b('record',L('View record','查看记录'),p.seq):'')+'</td><td>'+overdue(p)+'</td></tr><tr id="rp-breakdown-'+p.seq+'"'+(expanded.has(selected+':'+p.seq)?'':' hidden')+'><td colspan="6">'+dl([[L('Plan ID','还款计划编号'),E(p.id)],[L('Principal / interest (USD)','本金 / 利息（USD）'),CF.fmtAmt(p.principal)+' / '+CF.fmtAmt(p.interest)],[L('Accrual period','计息区间'),date(p.from)+' → '+date(p.due)+' · '+p.days+L(' days',' 天')],[L('Settled at','结清时间'),time(p.record?.confirmedAt)]])+(p.principal?'<p>'+L('Final instalment includes principal','末期含本金')+(p.days>93?L(' and the merged final period.','及合并尾段。'):'')+'</p>':'')+'</td></tr>').join('')+'</tbody></table></div>'+dl([[L('Total principal (USD)','本金合计（USD）'),CF.fmtAmt(x.amount)],[L('Total interest (USD)','利息合计（USD）'),CF.fmtAmt(p8.periods.reduce((n,p)=>n+p.interest,0))],[L('Total due (USD)','应还合计（USD）'),CF.fmtAmt(p8.periods.reduce((n,p)=>n+p.total,0))]]);
  }
  function account(snapshot){const x=deal(),f=snapshot||x.record.form;if(x.ccy!=='USD')return dl([[L('Recipient','收款人'),E(funder(x))],[L('Repayment address','还款收款地址'),'<span class="hash">'+E(f.repayWallet||x.repayWallet||'—')+'</span>'],[L('Network','链'),'ETH · ERC-20']]);return dl([['repayName',L('Account name','户名')],['repayNumber',L('Account number','账号')],['repaySwift','SWIFT / BIC'],['repayBank',L('Bank','开户行')],['repayIntermediary',L('Intermediary bank','中转行')]].map(([k,t])=>[t,'<span class="mono">'+E(f[k]||'—')+'</span>']));}
  const err=k=>'<span id="rp-'+k+'-error" class="err-msg" role="alert">'+E(errors[k]||'')+'</span>';
  function field(k,title,type='text'){return '<div class="field"><label for="rp-'+k+'">'+title+'</label><input class="inp" id="rp-'+k+'" data-rp-field="'+k+'" type="'+type+'" value="'+E(form[k]||'')+'" aria-describedby="rp-'+k+'-error"'+(errors[k]?' aria-invalid="true"':'')+'>'+err(k)+'</div>';}
  function inputForm(){const x=deal();return field('paidAt',L('Repayment time (UTC) *','还款时间（UTC）*'),'datetime-local')+(x.ccy==='USD'?'':field('hash',L('Transaction hash *','交易哈希 *')))+'<div class="field"><label for="rp-files">'+(x.ccy==='USD'?L('Bank payment proof *','银行支付凭证 *'):L('Supplementary documents (optional)','补充材料（选填）'))+'</label><input id="rp-files" type="file" accept=".pdf,.jpg,.jpeg,.png" multiple><p class="hint">PDF / JPG / PNG · '+L('Up to 5 files, 10 MB each','最多 5 个，每个不超过 10 MB')+'</p>'+err('files')+'<div class="rp-files">'+(form.files||[]).map((f,i)=>'<div>'+E(f.name)+' '+b('remove',L('Remove','移除'),i)+'</div>').join('')+'</div></div><div class="field"><label for="rp-note">'+L('Note (optional, up to 200 characters)','还款备注（选填，最多 200 字）')+'</label><textarea class="inp" id="rp-note" data-rp-field="note" maxlength="200">'+E(form.note||'')+'</textarea>'+err('note')+'</div>';
  }
  function choosePeriod(kind){const ps=plan().periods,choices=kind==='pay'?ps.filter(p=>p.state==='due'):kind==='confirm'?ps.filter(p=>p.state==='pending'):ps.filter(p=>p.record);return '<div class="field"><label for="rp-period">'+L('Instalment','期次')+'</label><select class="inp" id="rp-period">'+choices.map(p=>'<option value="'+p.seq+'"'+(p.seq===seq?' selected':'')+'>'+p.seq+' / '+ps.length+' · '+date(p.due)+' · '+status(p)+'</option>').join('')+'</select></div>';}
  function record(p){const r=p.record;if(!r)return CF.note('',L('No repayment record has been submitted.','尚未提交还款记录。'));return section(L('Repayment record','还款记录'),dl([[L('Record ID','还款记录编号'),E(r.id)],[L('Repayment time','还款时间'),time(r.paidAt)],[L('Submitted at','提交时间'),time(r.at)],[L('Repayment nature','还款性质'),r.overdue?L('Overdue repayment','逾期还款'):L('Normal repayment','正常还款')],[L('Submitted by','提交人与企业'),E(r.by)],[L('Confirmed at','确认时间'),time(r.confirmedAt)],[L('Note','备注'),E(r.note||'—')]])+(r.hash?'<p class="hash">'+E(r.hash)+'</p><p>ETH · ERC-20</p><a target="_blank" rel="noopener noreferrer" href="https://etherscan.io/tx/'+E(r.hash)+'">'+L('Open block explorer','查看区块浏览器')+'</a><p class="hint">'+L('The platform has not verified this transaction. The link is for your own checks.','平台未核验该交易，链接仅供自行查验。')+'</p>':'')+(r.files||[]).map((f,i)=>'<div class="rp-file">'+E(f.name)+'<div class="rp-row">'+b('preview',L('Preview','预览'),i,false,!files.has(f.id))+b('download',L('Download','下载'),i,false,!files.has(f.id))+'</div>'+(!files.has(f.id)?'<span class="hint">'+L('Local file unavailable after reload','页面重载后本地文件不可用')+'</span>':'')+'</div>').join(''));
  }
  function drawer(kind){if(kind==='detail')return detail();const x=deal(),p=period();if(!x||!plan())return {title:L('Repayment','还款'),html:CF.note('',L('The plan is not available yet.','还款计划暂不可用。')),foot:b('back',L('Close','关闭'))};
    if(!['plan','detail'].includes(kind)&&!party(x))return {title:L('Access denied','无访问权限'),html:CF.note('warn',L('Private repayment details are available only to the parties.','还款私有资料仅本业务双方可见。')),foot:b('back',L('Close','关闭'))};
    let body='',foot=b('back',back?L('Back','返回'):L('Close','关闭'));
    if(load==='loading')body='<div role="status">'+L('Loading repayment information…','正在加载还款信息…')+'</div>';else if(load==='error')body=CF.empty(L('Unable to load repayment information','还款信息加载失败'),'',b('retry',L('Retry','重试')));else if(kind==='plan')body=schedule();
    else {body=choosePeriod(kind)+periodInfo(p)+clock(p);if(kind==='pay'&&p.state==='due'){
      const opened=now()>=p.open;body+=(!opened?CF.note('',L('Repayment opens ','还款入口开启时间：')+time(iso(p.open))):'')+b('plan',L('View full repayment schedule','查看完整还款计划'))+section(L('Funder’s repayment account','资金方收款账户'),account())+(S.role==='asset'&&opened?section(L('Payment details','填写还款记录'),inputForm()):'')+'<p class="hint">'+L('You bear cross-border fees, which may reduce the amount received. The platform records repayment only; it does not transfer funds or charge gas for this submission.','跨境手续费由付款方承担，可能造成到账差额。平台仅登记还款，不代为转账；提交记录不收取 gas。')+'</p>';foot+=b('ask',L('Submit repayment','提交还款'),'pay',true,!can('pay'));
    }else{body+=b('plan',L('View full repayment schedule','查看完整还款计划'))+record(p)+section(L('Funder’s repayment account','资金方收款账户'),account(p.record?.account))+support();if(kind==='confirm')foot+=b('ask',L('Confirm repayment received','确认收到还款'),'confirm',true,!can('confirm'));}
    }
    return {title:kind==='plan'?L('Repayment schedule','还款计划'):kind==='pay'?L('Record repayment','立即还款'):kind==='confirm'?L('Confirm repayment received','确认收到还款'):L('Repayment record','还款记录'),html:'<div class="rp-drawer" data-kind="'+kind+'">'+body+'</div>',foot};
  }
  function confirmation(){const p=period(),pay=askKind==='pay',willSettle=!pay&&plan().periods.every(r=>r===p||r.state==='settled');return {title:pay?L('Submit this repayment record?','确认提交还款记录？'):L('Confirm that repayment has arrived?','确认还款已实际到账？'),html:'<div class="rp-confirm">'+periodInfo(p)+'<p>'+L('Application: ','申请编号：')+E(deal().request)+'</p>'+CF.note('warn',pay?L('After submission, this record cannot be edited or withdrawn. Overdue days stop increasing. The funder has 168 hours to confirm; expiry does not confirm repayment automatically. The platform does not verify payment authenticity.','提交后记录不可修改或撤回，逾期天数停止累加；资金方有 168 小时确认，到期不会自动确认。平台不核验转账真实性。'):L('I have independently verified receipt. The platform has not verified it. Confirmation cannot be revoked.','本人已自行核实到账，平台未核验；确认不可撤销。'))+(!pay&&p.principal?'<p>'+L('Principal occupancy will decrease by ','本次本金对应占用将减少 ')+amount(p.principal)+'</p>':'')+(willSettle?'<p>'+L('This financing business will be settled.','本笔融资业务将结清。')+'</p>':'')+'<label class="rp-agree"><input id="rp-agree" type="checkbox"'+(agree?' checked':'')+'>'+L('I understand and confirm','我已了解并确认')+'</label>'+err('submit')+'</div>',foot:b('cancel',L('Cancel','取消'),'',false,busy)+b('commit',busy?L('Submitting…','提交中…'):L('Continue','继续'),'',true,busy||!agree)};}
  function remember(){const a=document.activeElement;return {back,seq,selected,pageTop:window.scrollY,layer:S.layer?{...S.layer}:null,top:document.querySelector('#layers [role=dialog]:not([inert]) .drawer-b')?.scrollTop||document.querySelector('#layers .modal-b')?.scrollTop||0,focus:{id:a?.id,act:a?.dataset.act,v:a?.dataset.v}};}
  function restore(ctx){if(ctx?.selected)selected=ctx.selected;if(ctx?.seq)seq=ctx.seq;returnUI=ctx;S.layer=ctx?.layer||null;CF.render();if(!ctx?.layer){setTimeout(()=>{window.scrollTo(0,ctx?.pageTop||0);const f=ctx?.focus;const el=f?.id?document.getElementById(f.id):[...document.querySelectorAll('[data-act]')].find(e=>e.dataset.act===f?.act&&e.dataset.v===f?.v);el?.focus({preventScroll:true});returnUI=null;},0);}}
  function key(){return [selected,seq,S.role].join('|');}
  function stash(){if(activeKey)drafts.set(activeKey,form);}
  function useForm(){activeKey=key();form=drafts.get(activeKey)||{paidAt:'',hash:'',note:'',files:[]};errors={};}
  function dirty(){return !!(form.paidAt||form.hash||form.note||form.files?.length);}
  function openDetail(id,options={}){ensure();if(!choose(id)){CF.toast(L('This repayment business is unavailable.','本笔还款业务不可用。'));return;}origin=remember();origin.layer=null;externalReturn=typeof options==='function'?options:options.onReturn||null;back=null;askKind='';resultNotice='';useForm();CF.openLayer('drawer','rp-detail');}
  function open(kind,id,n){ensure();if(id&&!choose(id,n))return;const x=deal();if(!x)return;if(!['plan','detail'].includes(kind)&&!party(x))kind='detail';if(!S.layer?.key.startsWith('rp-')){origin=remember();origin.layer=null;externalReturn=null;back=null;resultNotice='';}else back=remember();if(n)seq=n;else if(plan())seq=(kind==='confirm'||kind==='record'?plan().periods.find(p=>p.state==='pending')||plan().periods.find(p=>p.record):nearest(x))?.seq||1;useForm();if(!plan())kind='detail';if(kind!=='detail'&&!back)back={...remember(),layer:{type:'drawer',key:'rp-detail'},back:null};CF.openLayer('drawer','rp-'+kind);}
  function exitDetail(all=false){epoch++;busy=false;askKind='';back=null;const prev=origin;origin=null;const callback=externalReturn;externalReturn=null;if(callback&&!all)callback();else restore(prev);}
  function close(all=false){if(busy)return;if(dirty()&&(all||!back)){discardReturn=remember();CF.openLayer('drawer','rp-discard');return;}if(all){exitDetail(true);return;}stash();epoch++;busy=false;askKind='';if(back){const prev=back;back=prev.back;seq=prev.seq;restore(prev);}else exitDetail();}
  function discard(){drafts.delete(activeKey);form={};activeKey='';discardReturn=null;exitDetail(true);}
  function validate(){errors={};const ms=Date.parse(form.paidAt+'Z');if(!form.paidAt||!Number.isFinite(ms)||ms>now())errors.paidAt=L('Enter a repayment time no later than now.','请输入不晚于当前时刻的还款时间。');if(deal().ccy==='USD'&&!(form.files||[]).length)errors.files=L('Upload at least one bank payment proof.','请上传至少一份银行支付凭证。');if(deal().ccy!=='USD'&&!/^0x[\da-f]{64}$/i.test(form.hash||''))errors.hash=L('Use 0x followed by 64 hexadecimal characters.','请输入 0x 开头的 64 位十六进制字符。');if([...form.note||''].length>200)errors.note=L('Use up to 200 characters.','最多填写 200 字。');errorFocus=Object.keys(errors)[0]||'';return !errorFocus;}
  function ask(kind){if(!can(kind)){CF.toast(L('The instalment or permissions have changed. Review the current details.','期次状态或权限已变化，请查看当前详情。'));return;}if(kind==='pay'&&!validate()){CF.render();return;}stash();askKind=kind;agree=false;errors={};confirmReturn=remember();CF.openLayer('drawer','rp-confirmation');}
  function cancel(){if(busy)return;askKind='';agree=false;restore(confirmReturn);confirmReturn=null;}
  async function commit(){if(busy||!agree||!can(askKind))return;const x=deal(),p=period(),kind=askKind,stamp=epoch,role=S.role,hash=location.hash;busy=true;CF.render();await new Promise(r=>setTimeout(r,450));if(stamp!==epoch||role!==S.role||hash!==location.hash||deal()!==x||period()!==p||S.layer?.key!=='rp-confirmation'){return;}
    busy=false;if(!can(kind)){cancel();CF.toast(L('This instalment has already changed.','本期状态已变化。'));return;}if(fail){errors.submit=L('Submission failed. Your entries are preserved; retry when ready.','提交失败，已保留填写内容，请重试。');CF.render();return;}
    if(kind==='pay'){if(!validate()){cancel();return;}const at=iso(now());p.record={...form,files:[...form.files],id:'RM'+day(now()).replaceAll('-','')+String(++serial).padStart(6,'0'),at,paidAt:iso(Date.parse(form.paidAt+'Z')),overdue:overdue(p),account:{...x.record.form,files:undefined},by:x.owner==='entity-demo-a'?'Demo employee A · Demo Asset Company A':'Demo employee B · Demo Asset Company B',confirmedAt:null};p.state='pending';event('submitted',x,p,['fund']);}
    else {p.record.confirmedAt=iso(now());p.state='settled';const project=D.project(x.project),credit=Q.data().credits.find(c=>c.owner===x.owner&&c.fund===x.fund);project.balance=round(Math.max(0,project.balance-p.principal));if(credit)credit.principal=round(Math.max(0,credit.principal-p.principal));x.principalBalance=round(Math.max(0,x.principalBalance-p.principal));x.creditUsed=round(Math.max(0,x.creditUsed-p.principal));event('confirmed',x,p,['asset']);if(plan().periods.every(r=>r.state==='settled')){plan().settledAt=iso(now());event('settled',x,null,['asset','fund']);}
      // L5 owns project terminal decisions. Do not equate zero principal with all instalments settled.
      if(project.expired&&!D.numbers(project).fly&&!project.balance&&available(project).every(a=>quote(a.id).l8?.settledAt)){project.state='settled';D.releasePool(project);}
    }
    Q.save();drafts.delete(activeKey);activeKey='';form={};askKind='';agree=false;back=null;confirmReturn=null;resultNotice=kind==='pay'?L('Repayment submitted · awaiting funder confirmation','还款已提交 · 等待资金方确认'):L('Repayment confirmed','还款已确认');CF.openLayer('drawer','rp-detail');CF.toast(kind==='pay'?L('Repayment submitted. Awaiting funder confirmation.','还款已提交，等待资金方确认。'):L('Repayment confirmed.','还款已确认。'));
  }
  function sweep(){ensure();CF.L7.deals.filter(confirmed).forEach(x=>(quote(x.id).l8?.periods||[]).forEach(p=>{if(p.state==='due'){if(now()>=p.open)event('due',x,p,['asset']);if(overdue(p))event('overdue',x,p,['asset','fund']);}if(p.state==='pending'){const remaining=Date.parse(p.record.at)+168*H-now();if(remaining<=0)event('late',x,p,['asset','fund']);else if(remaining<=24*H)event('soon',x,p,['fund']);}}));}
  const names={final:['Repayment schedule finalized','还款计划已定稿'],due:['Repayment due soon','还款临近'],overdue:['Repayment overdue','还款逾期'],submitted:['Repayment submitted','还款已提交'],soon:['Confirmation due soon','还款确认临近到期'],late:['Repayment confirmation overdue','还款确认超期'],confirmed:['Repayment confirmed','还款已确认'],settled:['Financing business settled','融资业务已结清']};
  function eventBody(){return events.filter(e=>e.owner===S.role&&party(deal(e.deal))).map(e=>{const x=deal(e.deal),p8=quote(x.id).l8,p=p8.periods.find(p=>p.seq===e.seq);return section(L(...names[e.kind]),'<p class="mono">'+E(x.request)+' · '+E(x.id)+(p?' · '+E(p.id):'')+'</p><p>'+time(e.at)+'</p>'+(e.kind==='late'?'<p>'+L('Overdue days remain frozen. There is no automatic confirmation; principal stays occupied until confirmed. Support email unavailable.','逾期天数保持冻结，不自动确认；本金待确认期间继续占用。客服邮箱暂不可用。')+'</p>':'')+(e.kind==='final'?comparison(x):'')+b('event',L('View business','查看业务'),e.id));}).join('')||CF.empty(L('No notification events','暂无通知事件'),'');}
  function comparison(x){const p8=quote(x.id).l8,initial=build(day(x.at),p8.end,x.amount,x.rate,x.fx.value);return '<p>'+L('Expected / actual interest start: ','预计 / 实际起息日：')+date(day(x.at))+' / '+date(p8.start)+'</p><p>'+L('Expected / final instalments: ','预计 / 定稿期数：')+initial.length+' / '+p8.periods.length+'</p><div class="rp-plan-scroll"><table class="tbl"><thead><tr><th>'+L('Instalment','期次')+'</th><th>'+L('Expected date / USD','预计日期 / USD')+'</th><th>'+L('Final date / USD','定稿日期 / USD')+'</th></tr></thead><tbody>'+Array.from({length:Math.max(initial.length,p8.periods.length)},(_,i)=>'<tr><td>'+(i+1)+'</td><td>'+(initial[i]?date(initial[i].due)+' / '+CF.fmtAmt(initial[i].total):'—')+'</td><td>'+(p8.periods[i]?date(p8.periods[i].due)+' / '+CF.fmtAmt(p8.periods[i].total):'—')+'</td></tr>').join('')+'</tbody></table></div>';}
  function initial(q){if(!['waiting','funding'].includes(q.state))return '';const ps=build(day(q.at),day(Date.parse(q.repay)),q.amount,q.rate,q.fx.value);return '<details class="ls-history"><summary>'+L('Initial repayment schedule · estimated, not effective','初始还款计划 · 预计，未生效')+'</summary><p class="hint">'+L('Dates will be recalculated after receipt confirmation using the actual disbursement date.','放款确认后将按实际放款日期重新计算还款安排。')+'</p><div class="rp-plan-scroll"><table class="tbl"><thead><tr><th>'+L('Instalment','期次')+'</th><th>'+L('Expected repayment date','预计还款日')+'</th><th>'+L('Total (USD)','应还合计（USD）')+'</th></tr></thead><tbody>'+ps.map(p=>'<tr><td>'+p.seq+'</td><td>'+date(p.due)+'</td><td>'+CF.fmtAmt(p.total)+'</td></tr>').join('')+'</tbody></table></div></details>';}
  function tools(){return '<div class="rp-demo"><h5>'+L('6 · Repayment scenarios','6 · 还款场景')+'</h5><p class="hint">'+L('Scenario buttons reset the local example. Date calculations use UTC and settlement amounts use 2 decimals for demonstration only.','场景按钮重置本地示例。日期按 UTC、结算金额按两位小数演示，不裁定正式口径。')+'</p>'+[['USD','USD repayment','法币还款'],['USDT','USDT repayment','USDT 还款'],['USDC','USDC repayment','USDC 还款'],['multi','Multiple businesses','多笔业务'],['waiting','Plan generating','计划生成中'],['overdue','Repayment overdue','还款逾期'],['pending','Awaiting confirmation','待还款确认'],['late','Confirmation overdue','确认超期'],['final','Final principal','末期本金'],['outoforder','Principal confirmed first','本金先确认，仍有未还利息']].map(([v,en,zh])=>b('scenario',L(en,zh),v)).join('')+b('ready',L('Complete plan generation','完成计划生成'))+b('advance',L('Advance 30 days','推进 30 天'))+'<label><input type="checkbox" id="rp-fail"'+(fail?' checked':'')+'> '+L('Submission fails','提交失败')+'</label><label><input type="checkbox" id="rp-upload-fail"'+(uploadFail?' checked':'')+'> '+L('Upload fails','上传失败')+'</label><label for="rp-load">'+L('Drawer state','抽屉状态')+'</label><select class="inp" id="rp-load">'+[['ready','Ready','正常'],['loading','Loading','加载中'],['error','Load failed','加载失败']].map(([v,en,zh])=>'<option value="'+v+'"'+(load===v?' selected':'')+'>'+L(en,zh)+'</option>').join('')+'</select>'+b('events',L('Notification event preview','通知事件预览'))+b('release-known',L('Known released fact / repeat release','可信已释放事实 / 重复释放'))+'</div>';}
  function scenario(kind){epoch++;busy=false;clockOverride=0;fail=false;load='ready';drafts.clear();events.length=0;CF.L7.scenario('confirmed');const x=CF.L7.deals.find(confirmed),q=quote(x.id);selected=x.id;delete q.l8;x.plan=kind==='waiting'?'waiting':'handoff';if(['USDT','USDC'].includes(kind)){x.ccy=q.ccy=kind;x.fx=q.fx={...q.fx,value:1};x.settlement=q.settlement=x.amount;}ensure();const p8=q.l8;if(p8){seq=1;clockOverride=Date.parse(p8.periods[0].due)+(kind==='overdue'?5*DAY:0);if(kind==='multi'){const second=JSON.parse(JSON.stringify(q));second.id=q.id+'-B';second.demand=q.demand+'-B';second.fund='fund-b';second.l7.id=second.id;second.l7.fund='fund-b';second.l7.request=second.demand;second.l7.record.id+='B';delete second.l8;Q.data().quotes.push(second);D.project(x.project).demands.push({...D.project(x.project).demands.find(d=>d.id===q.demand),id:second.demand});D.project(x.project).balance+=x.amount;ensure();}
      if(['pending','late','final','outoforder'].includes(kind)){if(kind==='final'){p8.periods.slice(0,-1).forEach(p=>{p.state='settled';p.record=demoRecord(p,x);p.record.confirmedAt=iso(now());});seq=p8.periods.length;clockOverride=Date.parse(p8.periods.at(-1).due);}
      const p=p8.periods[seq-1];p.record=demoRecord(p,x);p.state='pending';if(kind==='late')clockOverride+=30*DAY;
      if(kind==='outoforder'){const last=p8.periods.at(-1);last.state='settled';last.record=demoRecord(last,x);last.record.confirmedAt=iso(now());x.principalBalance=x.creditUsed=0;D.project(x.project).balance=0;const credit=Q.data().credits.find(c=>c.owner===x.owner&&c.fund===x.fund);if(credit)credit.principal=Math.max(0,credit.principal-x.amount);clockOverride=Date.parse(last.due)+DAY;}
      }}if(['final','outoforder'].includes(kind))D.project(x.project).expired=true;S.role=['pending','late','final','outoforder'].includes(kind)?'fund':'asset';S.layer=null;S.demo=false;Q.data().repaymentClock=clockOverride;Q.save();setTimeout(()=>{V.onAct('ls-tab','repay');CF.render();},20);}
  function demoRecord(p,x){return {id:'RM-DEMO-'+p.seq,at:iso(now()),paidAt:iso(now()-H),hash:x.ccy==='USD'?'':'0x'+'b'.repeat(64),files:[],note:'',account:{...x.record.form,files:undefined},by:'Demo employee A · Demo Asset Company A',overdue:overdue(p),confirmedAt:null};}
  function resetContext(){epoch++;busy=false;stash();form={};errors={};activeKey='';origin=back=null;askKind='';agree=false;lastRole=S.role;lastHash=location.hash;}
  function deepLink(){if(!location.hash.startsWith('#/project/'))return;const u=new URLSearchParams(location.hash.split('?')[1]||''),id=u.get('business'),n=u.get('instalment'),action=u.get('repayment')||(n?'detail':null);if(!action)return;ensure();const x=deal(id),project=location.hash.split('?')[0].split('/')[2];if(!x||x.project!==project||!confirmed(x)||(n&&!quote(x.id).l8?.periods.some(p=>p.seq===+n||p.id===n))){CF.toast(L('The repayment target is unavailable.','指定还款业务或期次不可用。'));return;}choose(id,n?quote(id).l8.periods.find(p=>p.seq===+n||p.id===n).seq:undefined);V.onAct('ls-tab','repay');CF.render();if(['detail','plan','pay','confirm','record'].includes(action)){const target=period();open((action==='pay'&&target?.state!=='due')||(action==='confirm'&&target?.state!=='pending')?'detail':action,id,seq);}}
  function act(a,v){if(!a.startsWith('rp-'))return false;if(busy)return true;const k=a.slice(3);if(k==='detail'){openDetail(v);}else if(k==='table-page'){const [id,n]=v.split('|');const f=listViews.get(id);if(f)f.page=+n;}else if(k==='table-filter'){const f=listViews.get(v);f.query=document.getElementById('rp-list-query-'+v).value.trim();f.page=1;}else if(k==='table-reset'){listViews.set(v,{query:'',page:1});}else if(k==='discard'){discard();}else if(k==='keep'){restore(discardReturn);discardReturn=null;}else if(k==='related'){const ctx=remember(),id=selected,n=seq;const onReturn=()=>{selected=id;seq=n;restore(ctx);};if(v==='loan')CF.L7.openDetail?.(selected,{onReturn});else CF.CQ.openRequest?.(deal().request,{selected,onReturn});}else if(k==='period-action'){const [kind,n]=v.split('|');back=remember();seq=+n;useForm();CF.openLayer('drawer','rp-'+kind);}else if(k==='business-plan'){open('plan',v);}else if(k==='select'){stash();choose(v);filter='';useForm();}else if(k==='clear')filter='';else if(k==='open')open(v);else if(k==='plan'){stash();back=remember();CF.openLayer('drawer','rp-plan');}else if(k==='record'){back=remember();seq=+v;CF.openLayer('drawer','rp-record');}else if(k==='back')close();else if(k==='ask')ask(v);else if(k==='cancel')cancel();else if(k==='commit')commit();else if(k==='remove'){form.files.splice(+v,1);stash();}else if(k==='retry')load='ready';else if(k==='scenario')scenario(v);else if(k==='ready'){if(deal()){deal().plan='handoff';ensure();Q.save();}}else if(k==='advance'){clockOverride=now()+30*DAY;Q.data().repaymentClock=clockOverride;sweep();Q.save();}else if(k==='events')CF.openLayer('modal','rp-events');else if(k==='copy'){navigator.clipboard?.writeText(v).then(()=>CF.toast(L('Copied','已复制')),()=>CF.toast(L('Select the reference numbers to copy.','请选中业务编号复制。')));}else if(k==='event'){const e=events.find(e=>e.id===v&&e.owner===S.role&&party(deal(e.deal)));if(e){S.layer=null;choose(e.deal,e.seq);V.onAct('ls-tab','repay');open(e.seq?(S.role==='fund'&&period()?.state==='pending'?'confirm':period()?.record?'record':'pay'):'plan',e.deal,e.seq);}}
    else if(k==='expand'){const key=selected+':'+v;expanded.has(key)?expanded.delete(key):expanded.add(key);}
    else if(k==='preview'||k==='download'){if(!party(deal())){denied();return true;}const f=period()?.record?.files[+v],data=f&&files.get(f.id);if(data){if(k==='download'){const a=document.createElement('a');a.href=data.url;a.download=f.name;a.click();}else{previewFile=f;back=remember();CF.openLayer('drawer','rp-preview');}}}
    else if(k==='release-known'){const p=deal()&&D.project(deal().project);if(!p||!D.terminal(p)||available(p).some(x=>!quote(x.id).l8?.settledAt)){CF.toast(L('A terminal project with all businesses settled is required.','须为项目终态且所有业务均已结清。'));return true;}if(p.l8ReleaseKnown)CF.toast(L('Already released','已释放'));else{releasePool(p);p.l8ReleaseKnown=true;p.l8ReleasePending=false;Q.save();CF.toast(L('Already released · tokens await collection','已释放 · 代币待提取'));}}
    CF.render();return true;
  }
  const oldAct=V.onAct,oldBefore=V.beforeRender,oldGuard=V.onBeforeAct,oldDemo=V.demo,organize=Q.organizeTools;
  V.onAct=(a,v,e)=>act(a,v)||oldAct(a,v,e);
  V.beforeRender=()=>{if(S.layer?.key.startsWith('rp-'))savedUI=remember();oldBefore?.();if(S.role!==lastRole||location.hash!==lastHash){if(S.layer?.key.startsWith('rp-'))S.layer=null;resetContext();}sweep();};
  V.demo=()=>oldDemo()+tools();Q.organizeTools=()=>{const node=document.querySelector('#demoPanel .rp-demo');if(document.querySelector('#demoPanel .cq-guide'))return;organize();if(node){const root=document.querySelector('#demoPanel .cq-guide');if(root){const group=document.createElement('details');group.className='cq-demo-group';group.innerHTML='<summary>'+L('6 · Repayment & confirmation','6 · 还款与确认')+'</summary>';group.append(node);root.append(group);}}};
  V.onBeforeAct=(a,v,e)=>{if(S.layer?.key.startsWith('rp-')&&a==='closelayer'){if(e.type==='click'&&e.target.closest('[data-stop]')&&e.target.closest('[data-act]')?.classList.contains('modal-mask'))return false;if(busy)return true;if(S.layer.key==='rp-discard'){restore(discardReturn);discardReturn=null;}else close(true);return true;}if(busy&&['role','signout'].includes(a))return true;return oldGuard?.(a,v,e)||false;};
  Object.assign(V.layers,{'rp-detail':()=>drawer('detail'),'rp-discard':()=>({title:L('Discard unsaved repayment details?','放弃未提交的还款信息？'),html:'<div class="rp-drawer">'+CF.note('warn',L('Your entered information will be discarded. No repayment record has been submitted.','已填写内容将被丢弃，尚未提交还款记录。'))+'</div>',foot:b('keep',L('Keep editing','继续填写'))+b('discard',L('Discard and close','放弃并关闭'),'',true)}),'rp-plan':()=>drawer('plan'),'rp-pay':()=>drawer('pay'),'rp-confirm':()=>drawer('confirm'),'rp-record':()=>drawer('record'),'rp-confirmation':confirmation,'rp-events':()=>({title:L('Notification event preview','通知事件预览'),html:eventBody(),foot:b('back',L('Close','关闭'))}),'rp-preview':()=>({title:previewFile?.name||'',html:'<div class="rp-drawer">'+(party(deal())&&files.has(previewFile?.id)?previewFile.type.startsWith('image/')?'<img class="rp-document" src="'+E(files.get(previewFile.id).url)+'" alt="'+E(previewFile.name)+'">':'<object class="rp-document" data="'+E(files.get(previewFile.id).url)+'" type="application/pdf"><p>'+L('Preview unavailable; return to download the file.','无法预览，请返回记录下载原件。')+'</p></object>':L('File unavailable','文件不可用'))+'</div>',foot:b('back',L('Back to record','返回记录'))})});
  document.addEventListener('input',e=>{const el=e.target;if(el.dataset.rpField){form[el.dataset.rpField]=el.value;delete errors[el.dataset.rpField];el.removeAttribute('aria-invalid');const error=document.getElementById(el.id+'-error');if(error)error.textContent='';stash();}if(el.id==='rp-search'){filter=el.value;document.getElementById('rp-options').innerHTML=options(available(D.project(deal().project)));}});
  document.addEventListener('change',e=>{const el=e.target;if(el.id==='rp-period'){stash();seq=+el.value;useForm();CF.render();}if(el.id==='rp-agree'){agree=el.checked;const button=document.querySelector('[data-act=rp-commit]');if(button)button.disabled=!agree;}
    if(el.id==='rp-files'){errors.files='';for(const f of el.files){if(uploadFail){errors.files=L('Upload failed. Please choose the file again.','上传失败，请重新选择文件。');continue;}if(!/\.(pdf|jpe?g|png)$/i.test(f.name)||!['application/pdf','image/jpeg','image/png'].includes(f.type)||f.size>10*1024*1024||f.size===0){errors.files=L('Choose a non-empty PDF, JPG or PNG no larger than 10 MB.','请选择非空 PDF/JPG/PNG，单文件不超过 10 MB。');continue;}if(form.files.length>=5){errors.files=L('A maximum of 5 files is allowed.','最多上传 5 个文件。');break;}const id='local-'+(++serial);files.set(id,{file:f,url:URL.createObjectURL(f)});form.files.push({id,name:f.name,type:f.type,size:f.size});}stash();CF.render();}
    if(el.id==='rp-fail')fail=el.checked;if(el.id==='rp-upload-fail')uploadFail=el.checked;if(el.id==='rp-load')load=el.value;
  });
  let previousLayer='';new MutationObserver(()=>{if(!S.layer?.key.startsWith('rp-')){previousLayer='';return;}const dialogs=[...document.querySelectorAll('#layers [role=dialog]')],dialog=dialogs.find(d=>!d.closest('[inert]'));if(!dialog)return;dialog.classList.add('wide');const body=dialog.querySelector('.drawer-b,.modal-b');if(previousLayer!==S.layer.key){const heading=dialog.querySelector('.drawer-h b,.modal-h');heading.tabIndex=-1;heading.focus({preventScroll:true});if(S.layer.key==='rp-plan')document.querySelector('.rp-current')?.scrollIntoView({block:'nearest'});}previousLayer=S.layer.key;const context=returnUI?.layer?.key===S.layer.key?returnUI:savedUI?.layer?.key===S.layer.key?savedUI:null;if(context){const c=context;if(c===returnUI)returnUI=null;body.scrollTop=c.top;const el=c.focus.id?document.getElementById(c.focus.id):[...dialog.querySelectorAll('[data-act]')].find(e=>e.dataset.act===c.focus.act&&e.dataset.v===c.focus.v);el?.focus({preventScroll:true});}if(errorFocus){const el=document.getElementById('rp-'+errorFocus);el?.setAttribute('aria-invalid','true');el?.focus();errorFocus='';}if(busy)dialog.querySelectorAll('button,input,select,textarea').forEach(el=>el.disabled=true);}).observe(document.getElementById('layers'),{childList:true});
  document.addEventListener('keydown',e=>{const row=e.target.closest?.('.rp-record-table tr[data-act]');if(row&&['Enter',' '].includes(e.key)){e.preventDefault();row.click();}});
  document.addEventListener('keydown',e=>{if(e.key!=='Tab'||!S.layer?.key.startsWith('rp-'))return;const nodes=[...document.querySelectorAll('#layers button:not(:disabled),#layers a[href],#layers input:not(:disabled),#layers select,#layers textarea,#layers [tabindex="0"]')].filter(el=>el.getClientRects().length&&!el.closest('[inert]'));if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();e.stopImmediatePropagation();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();e.stopImmediatePropagation();nodes[0]?.focus();}},true);
  // Preserve the unresolved cross-platform boundary: no synthetic release on project terminal state.
  const releasePool=D.releasePool;
  // Terminal business release is synchronous; collection on chain is a separate fact.
  D.projects?.forEach?.(p=>{if(D.terminal(p)){p.l8ReleasePending=false;releasePool(p);}});
  const actions=D.actions;D.actions=p=>{const a=actions(p);if(available(p).some(x=>!quote(x.id).l8?.settledAt))a.canClose=false;return a;};
  Q.data().quotes.forEach(q=>q.l8?.periods.forEach(p=>{serial=Math.max(serial,Number(p.id?.slice(-6))||0,Number(p.record?.id?.slice(-6))||0);}));
  CF.L8={build,initial,panel,available,recordTable,openDetail,hasUnsettled:p=>available(p).some(x=>!quote(x.id).l8?.settledAt),ensure,scenario,get selected(){return selected;},get seq(){return seq;},get now(){return now();},get events(){return events;},open};
  setInterval(()=>{sweep();if(['rp-confirm','rp-record'].includes(S.layer?.key))CF.render();},60000);
  window.addEventListener('hashchange',()=>setTimeout(deepLink,30));ensure();if(!CF.portalConnected)CF.render();setTimeout(deepLink,40);
})(window.CF);
