/* Local interactive prototype. All identities, delivery events and credentials are fictional.
   No authentication, email or permission server is contacted. */
(function(CF){
'use strict';
const S=CF.S, L=CF.L, esc=CF.esc, $=id=>document.getElementById(id);
const P={login:'P-O-AL-01',first:'P-O-AL-03',forgot:'P-O-AL-04',reset:'P-O-AL-05',account:'P-O-AL-06',overview:'P-O-AL-07'};
const R=id=>CF.ENTRY[id];
const fresh=()=>({email:'operator@example.com',name:['Demo Operator','演示操作员'],role:'specialist',first:true,expired:false,password:'Start1234',initial:'Start1234',fail:0,lockUntil:0,lockTier:0,lastLock:0,created:'2026-09-18T02:00:00Z',lastLogin:null});
let a=fresh(), session=false, V={}, E={}, notice=null, busy=false, mode='',verifiedUntil=0, recovery=false, code=null,seq=0,sendHistory=[],captchaErrors=0,captchaUntil=0,sendPurpose='',showLock=false,returnTo=P.overview,accountTab='info',failNext='',events=[],sessionEnd=0,lastActivity=0,warned=false,asyncVersion=0;
const visible={};
const read=k=>{try{return localStorage.getItem(k)}catch(e){return null}};
const save=(k,v)=>{try{localStorage.setItem(k,v)}catch(e){}};
// Local demonstration only: real challenges, tickets and quotas belong on the server.
const loadJSON=(k,fallback)=>{try{return JSON.parse(read(k))||fallback}catch(e){return fallback}};
const gateKey='hc.ops.code-gate',source={network:'demo-network',device:'demo-device'};
let puzzle=null,ticket=null,puzzleVersion=0,puzzleSerial=0,puzzleHelp=false,puzzlePointer=false,mailFailures={};
function loadGate(){const g=loadJSON(gateKey,{});sendHistory=(g.sent||[]).filter(x=>Date.now()-x.at<86400000);captchaErrors=g.errors||0;captchaUntil=g.until||0;mailFailures=g.mailFailures||{}}
function saveGate(){save(gateKey,JSON.stringify({sent:sendHistory,errors:captchaErrors,until:captchaUntil,mailFailures}))}
loadGate();
S.end='admin'; S.lang=read('hc.ops.language')||'en';
const role=()=>a.role==='admin'?L('Operations Administrator','运营管理员'):L('Operations Specialist','运营专员');
const permissionGroups=()=>[
 ['cert',L('Institution certification','机构认证'),[[5,L('View applications and documents','申请与材料查询')],[6,L('Review applications','认证审核处置')]]],
 ['pledge',L('Token pledges','代币质押'),[[7,L('View pledge applications','质押申请查询')],[8,L('Review pledge applications','质押审核处置')]]],
 ['agreement',L('Agreements','协议管理'),[[9,L('View content and versions','内容与版本查询')],[10,L('Maintain content and versions','内容与版本维护')],[11,L('Publish versions','版本发布')]]],
 ['general',L('General','通用功能'),[[12,L('View operations messages','运营端消息查看')],[13,L('Query operations data','运营业务数据查询')],[14,L('Personal account settings','本人账户设置')]]]
];
function can(n){return !(n===12&&CF.opsNotifications?.blocked)&&!!session&&!a.first&&!locked()&&(a.role==='admin'||n>=12)}
function locked(){return a.lockUntil>Date.now()}
function jump(id){S.page=id;location.hash='#'+R(id)}
function clean(){V={};E={};notice=null;Object.keys(visible).forEach(k=>delete visible[k])}
function msg(en,zh){return [en,zh]}
function text(m){return m==='locked'?lockCopy():(m?L(m[0],m[1]):'')}
function err(id,en,zh){E[id]=msg(en,zh)}
function feedback(){return `<div class="ops-feedback" role="alert">${esc(text(notice))}</div>`}
function focusError(){const input=Array.from(document.querySelectorAll('[data-field][aria-invalid="true"]')).find(el=>el.getClientRects().length&&!el.closest('[inert]'));input?.focus()}
function capture(){document.querySelectorAll('[data-field]').forEach(el=>V[el.dataset.field]=el.value)}
function passwordIcon(shown){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">${shown?'<path d="m3 3 18 18M10.6 10.6a2 2 0 0 0 2.8 2.8M9.9 5.2A11 11 0 0 1 12 5c7 0 10 7 10 7a17 17 0 0 1-3.2 4.2M6.5 6.5C3.5 8.5 2 12 2 12s3 7 10 7a11 11 0 0 0 5.5-1.5"/>':'<path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>'}</svg>`}
function field(id,en,zh,type='text',opts='',trail=''){
 const pw=type==='password',val=V[id]||'',error=E[id];
 return `<div class="field"><label for="${id}">${L(en,zh)}</label><div class="${pw?'ops-secret':trail?'ops-code-row':''}"><input class="inp" id="${id}" data-field="${id}" type="${pw&&visible[id]?'text':type}" value="${esc(val)}" aria-required="true" aria-invalid="${!!error}" aria-describedby="${id}-error" ${busy?'readonly':''} ${opts}>${pw?`<button type="button" data-act="ops-show" data-v="${id}" aria-controls="${id}" aria-label="${visible[id]?L('Hide password','隐藏密码'):L('Show password','显示密码')}">${passwordIcon(visible[id])}</button>`:''}${trail}</div><span class="ops-error" id="${id}-error" aria-live="polite">${esc(text(error))}</span></div>`;
}
function button(act,en,zh,primary=true,disabled=false){return `<button type="button" class="btn ${primary?'primary':''}" data-act="${act}" ${disabled||busy?'disabled':''}>${busy&&primary?'<span class="spinner" aria-hidden="true"></span>'+L('Please wait…','处理中…'):L(en,zh)}</button>`}
function sendWait(act){loadGate();let target=(V[act==='ops-send-email'?'newEmail':'recoveryEmail']||'').trim().toLowerCase(),last=sendHistory.filter(x=>x.target===target).at(-1);return Math.max(0,Math.ceil((Math.max(last?last.at+60000:0,mailFailures[target]?.until||0)-Date.now())/1000))}
function sendLabel(wait){return wait?L('Resend in '+wait+'s',wait+' 秒后重发'):L('Send code','获取验证码')}
function refreshSendButtons(){['ops-send-email','ops-send-recovery'].forEach(act=>{const el=document.querySelector('button[data-act="'+act+'"]');if(!el)return;const wait=sendWait(act);el.disabled=busy||wait>0;if(!busy)el.textContent=sendLabel(wait)})}
function codeField(act){const waiting=sendWait(act);return field('code','Verification code','验证码','text','inputmode="numeric" autocomplete="one-time-code"',`<button type="button" class="btn" data-act="${act}" ${busy||waiting>0?'disabled':''}>${busy?L('Sending…','发送中…'):sendLabel(waiting)}</button>`)}
function form(act,body,btn){return `<form class="ops-form" data-submit="${act}" novalidate aria-busy="${busy}">${feedback()}${body}<button type="submit" class="btn primary block" ${busy||(act==='ops-login'&&showLock&&locked())||(body.includes('id="newPassword"')&&!passwordReady())?'disabled':''}>${busy?'<span class="spinner" aria-hidden="true"></span>'+L('Please wait…','处理中…'):btn}</button></form>`}
function heading(en,zh,subEn,subZh){return `<div class="ops-flow"><p class="ops-eyebrow">${L('OPERATIONS CONSOLE','运营管理平台')}</p><h1>${L(en,zh)}</h1><p class="ops-sub">${L(subEn,subZh)}</p>`}
function passwordReady(){const p=(V.newPassword||'').trim();return p.length>=8&&p.length<=20&&/[a-z]/i.test(p)&&/\d/.test(p)&&! /\s/.test(p)&&p===(V.confirmPassword||'').trim()}
function rules(){const p=(V.newPassword||'').trim();return `<ul class="ops-rules" aria-live="polite">${[[p.length>=8&&p.length<=20,L('8–20 characters','8～20 个字符')],[/[a-z]/i.test(p)&&/\d/.test(p),L('At least one letter and one number','至少包含一个字母与一个数字')],[p.length>0&&!/\s/.test(p),L('No spaces within the password','密码中间不含空格')]].map(x=>`<li class="${x[0]?'met':''}">${x[1]}</li>`).join('')}</ul>`}
function passwordFields(){return field('newPassword','New password','新密码','password','autocomplete="new-password"')+rules()+field('confirmPassword','Confirm new password','确认新密码','password','autocomplete="new-password"')}
function support(){return `<p class="hint">${L('Cannot access your email? Contact your platform provider or operations support to reinitialize your account.','无法访问工作邮箱？请联系平台建设方或运维重新初始化账号。')}</p>`}
function lockCopy(){const seconds=Math.max(0,Math.ceil((a.lockUntil-Date.now())/1000));return L('Account locked. Try again in ','账号已锁定，请在 ')+`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`+L('.',' 后重试。')+(a.lockTier===1?L(' Another lock will last longer.','再次触发时锁定时间会更长。'):'')}
function login(){return heading('Sign in','登录','Use your work email to access the operations console.','使用工作邮箱登录运营管理平台。')+(showLock&&locked()?`<div class="note warn" role="status" id="lockText">${lockCopy()}</div>`:'')+form('ops-login',field('email','Work email','工作邮箱','email','autocomplete="username" maxlength="254"')+field('password','Password','密码','password','autocomplete="current-password"'),L('Sign in','登录'))+`<div class="ops-actions"><a class="btn-link" href="#${R(P.forgot)}">${L('Forgot password?','忘记密码？')}</a></div></div>`}
function first(){return heading('Set a new password','首次登录 · 设置新密码','Change your initial password before accessing your account.','请先修改初始密码，再使用账户功能。')+form('ops-first',passwordFields()+`<p class="hint">${L('You will need to sign in again after changing your password.','修改后需要重新登录。')}</p>`,L('Save password','保存密码'))+'</div>'}
function forgot(){return heading('Reset your password','找回密码','Verify your work email to continue.','验证工作邮箱后设置新密码。')+`<div class="ops-step"><strong>${L('1 · Verify email','1 · 验证邮箱')}</strong><span>—</span><span>${L('2 · New password','2 · 设置新密码')}</span></div>`+form('ops-verify-recovery',field('recoveryEmail','Work email','工作邮箱','email','autocomplete="email" maxlength="254"')+codeField('ops-send-recovery')+(code&&code.purpose==='recovery'?`<p class="hint" role="status">${L('If this email belongs to an operations account, a code has been sent.','若该邮箱为运营端账号，验证码已发送。')}</p>`:''),L('Verify and continue','验证并继续'))+`<div class="ops-actions"><a class="btn-link" href="#${R(P.login)}">${L('Back to sign in','返回登录')}</a></div>`+support()+'</div>'}
function reset(){return heading('Choose a new password','设置新密码','Your email has been verified.','工作邮箱已验证。')+`<div class="ops-step"><span>${L('1 · Email verified','1 · 邮箱已验证')}</span><span>—</span><strong>${L('2 · New password','2 · 设置新密码')}</strong></div>`+form('ops-reset',passwordFields()+`<p class="hint">${L('All sessions will end. Sign in again with your new password.','所有设备将退出登录，请使用新密码重新登录。')}</p>`,L('Reset password','重置密码'))+`<div class="ops-actions"><a class="btn-link" href="#${R(P.login)}">${L('Back to sign in','返回登录')}</a></div></div>`}
function row(label,value,act){return `<div><dt>${label}</dt><dd>${value}</dd>${act?`<button class="btn-link" data-act="${act}">${L('Change','修改')}</button>`:''}</div>`}
function settings(){let surface=CF.surface({skelRows:4,deniedDesc:L('You do not have permission to view this page. Contact your platform provider.','您没有访问此页面的权限，请联系平台建设方。'),backTo:R(P.overview),backLabel:L('Back to overview','返回总览'),errorTitle:L('Could not load account information','账号信息加载失败'),emptyTitle:L('Account information is unavailable','暂无账号信息'),emptyDesc:L('Reload your account information.','请重新加载账号信息。')});return `<div class="page-head"><div><h1 class="page-title">${L('Account settings','账户设置')}</h1><p class="page-desc">${L('Manage your sign-in details and display preferences.','管理登录信息与显示偏好。')}</p></div></div>`+(surface||`<nav class="ops-tabs" aria-label="${L('Account sections','账户分区')}"><button data-act="ops-tab" data-v="info" aria-current="${accountTab==='info'}">${L('Account information','账号信息')}</button><button data-act="ops-tab" data-v="preferences" aria-current="${accountTab==='preferences'}">${L('Preferences','偏好信息')}</button></nav><div class="ops-settings"><section class="card ops-section" id="ops-info" tabindex="-1" aria-labelledby="ops-info-title"><h2 id="ops-info-title">${L('Account information','账号信息')}</h2><dl class="ops-details">${row(L('Work email','工作邮箱'),esc(a.email),'ops-email')}${row(L('Name','姓名'),esc(text(a.name)))}${row(L('Role','角色'),role())}${row(L('Status','账号状态'),CF.tag('ok',L('Active','正常')))}${row(L('Password','登录密码'),'••••••••','ops-password')}${row(L('Last sign-in','最近登录'),a.lastLogin?CF.fmtTime(a.lastLogin):'—')}${row(L('Created','创建时间'),CF.fmtTime(a.created))}</dl></section><section class="card ops-section" id="ops-preferences" tabindex="-1" aria-labelledby="ops-preferences-title"><h2 id="ops-preferences-title">${L('Preferences','偏好信息')}</h2><div class="ops-preferences"><div class="field"><label for="ops-language">${L('Interface language','界面语言')}</label><select class="inp" id="ops-language"><option value="en" ${S.lang==='en'?'selected':''}>English</option><option value="zh" ${S.lang==='zh'?'selected':''}>简体中文</option></select></div><div class="field"><label for="ops-timezone">${L('Time zone','时区')}</label><select class="inp" id="ops-timezone">${Array.from(new Set([S.tz,'UTC','Asia/Shanghai','Asia/Hong_Kong','Asia/Singapore','Europe/London','America/New_York'])).map(z=>`<option ${S.tz===z?'selected':''}>${esc(z)}</option>`).join('')}</select><p class="hint">${L('Times are displayed in your selected time zone.','页面时间按所选时区展示。')}</p></div></div></section></div><p class="ops-sample">${L('Demonstration data','演示数据')}</p>`)}
function overview(){return `<div class="page-head"><div><h1 class="page-title">${L('Overview','总览')}</h1><p class="page-desc">${L('Welcome to the operations console.','欢迎使用运营管理平台。')}</p></div></div>`+CF.empty(L('Your account is ready','账户已就绪'),L('Available operations appear in the navigation. You can manage your account and preferences from the account menu.','已开放的运营功能将显示在导航中。您可以通过账号菜单管理账户及偏好。'),button('ops-settings','Account settings','账户设置',false))}
function accountMenu(){return `<div class="dd"><button class="dd-btn" data-act="menu" data-v="ops-account" aria-haspopup="menu" aria-expanded="${S.menu==='ops-account'}"><span class="op-avatar xs">OP</span>${L('Account','我的账户')} ▾</button>${S.menu==='ops-account'?`<div class="dd-list" role="menu"><div class="ops-account-email">${esc(a.email)}<br>${CF.tag('ok',L('Active','正常'))}</div>${!CF.opsNotifications&&CF.AdminMenu?CF.AdminMenu.link('messages'):''}${CF.opsNotifications&&can(12)?`<button role="menuitem" data-act="ops-notifications">${L('Notifications','消息中心')}</button>`:''}<button role="menuitem" data-act="ops-settings">${L('Account settings','账户设置')}</button><button role="menuitem" data-act="ops-logout">${L('Sign out','退出登录')}</button></div>`:''}</div>`}

function emailEditor(){if(mode==='reauth')return {title:L('Verify your identity','验证身份'),html:form('ops-reauth',field('currentPassword','Current password','当前密码','password','autocomplete="current-password"'),L('Continue','继续')),foot:button('ops-cancel','Cancel','取消',false)};
return {title:L('Change work email','修改工作邮箱'),html:`<p class="ops-sub">${L('Your new email will become your sign-in and recovery address.','新邮箱将用于登录与找回密码。')}</p><p class="hint">${L('Current email: ','当前邮箱：')}${esc(a.email)}</p>`+form('ops-save-email',field('newEmail','New work email','新工作邮箱','email','autocomplete="email" maxlength="254"')+codeField('ops-send-email')+(code&&code.purpose==='email'?`<p class="hint" role="status">${L('Code sent to ','验证码已发送至 ')}${esc(code.target)}</p>`:''),L('Confirm email change','确认修改邮箱')),foot:button('ops-cancel','Cancel','取消',false)}}
function passwordEditor(){if(mode==='reauth')return {title:L('Verify your identity','验证身份'),html:form('ops-reauth',field('currentPassword','Current password','当前密码','password','autocomplete="current-password"'),L('Continue','继续')),foot:button('ops-cancel','Cancel','取消',false)};return {title:L('Change password','修改密码'),html:form('ops-save-password',passwordFields()+`<p class="hint">${L('All devices will be signed out after this change.','修改后所有设备将退出登录。')}</p>`,L('Save password','保存密码')),foot:button('ops-cancel','Cancel','取消',false)}}
function puzzleRemaining(){return Math.max(0,Math.ceil((captchaUntil-Date.now())/1000))}
function puzzleCopy(){if(puzzleRemaining())return L('Try again in '+puzzleRemaining()+'s',puzzleRemaining()+' 秒后重试');return ({loading:L('Loading puzzle…','正在加载拼图…'),checking:L('Verifying…','正在验证…'),passed:L('Verified','验证通过'),failed:L('Verification failed. Please try again.','验证失败，请重试。'),'load-error':L('Failed to load. Tap to retry.','加载失败，点击重试。')})[puzzle?.status]||(puzzle?.failed?L('Verification failed. Please try again.','验证失败，请重试。'):L('Drag to align, then release','拖动拼图对齐缺口，松手验证'))}
function puzzleScene(){const p=puzzle,shape='M0 0H14C8 -14 32 -14 26 0H40V14C54 8 54 32 40 26V40H26C32 26 8 26 14 40H0Z';return `<svg class="ops-puzzle-scene" viewBox="0 0 320 156" role="img" aria-label="${L('Move the puzzle piece into the matching gap.','将拼图移至对应缺口。')}"><defs><path id="puzzle-shape" d="${shape}"/><clipPath id="puzzle-clip"><use href="#puzzle-shape"/></clipPath><g id="puzzle-landscape"><path fill="var(--card-2)" d="M0 0H320V156H0Z"/><circle cx="${62+p.variant*34}" cy="35" r="21" fill="var(--accent-border)"/><path fill="var(--border-strong)" d="M0 133L${70+p.variant*17} 28L188 139L252 55L320 108V156H0Z"/><path fill="var(--accent)" opacity=".7" d="M0 153L117 57L213 141L282 84L320 111V156H0Z"/><path fill="none" stroke="var(--on-accent)" stroke-width="3" d="M0 ${115+p.variant*6}Q90 60 179 118T320 103"/><path fill="var(--accent-strong)" d="M0 145Q105 111 209 148T320 125V156H0Z"/></g></defs><use href="#puzzle-landscape"/><use href="#puzzle-shape" transform="translate(${p.target+8} ${p.y})" fill="var(--overlay)" stroke="var(--on-accent)" stroke-width="2"/><g id="puzzle-piece" transform="translate(${Number(V.captcha||0)+8} ${p.y})"><g clip-path="url(#puzzle-clip)"><use href="#puzzle-landscape" transform="translate(${-p.target-8} ${-p.y})"/></g><use href="#puzzle-shape" fill="none" stroke="var(--accent-strong)" stroke-width="2"/></g></svg>`}
function captcha(){const p=puzzle||{status:'loading'},cool=puzzleRemaining(),disabled=cool||p.status!=='ready';return {title:L('Security verification','安全验证'),html:`<div class="ops-puzzle" data-status="${cool?'cooldown':p.status}"><div class="ops-puzzle-heading"><label for="captcha">${L('Align the puzzle piece with the gap','请将拼图对齐缺口')}</label><button type="button" class="btn sm" data-act="ops-puzzle-refresh" aria-label="${L('Refresh puzzle','刷新拼图')}" ${cool||['checking','passed','loading'].includes(p.status)?'disabled':''}>↻</button></div>${['loading','load-error'].includes(p.status)?`<div class="ops-puzzle-placeholder">${p.status==='loading'?'<span class="spinner" aria-hidden="true"></span>':button('ops-puzzle-refresh','Failed to load. Tap to retry.','加载失败，点击重试。',false)}</div>`:puzzleScene()}<div class="ops-puzzle-track"><input id="captcha" class="ops-captcha" data-field="captcha" type="range" min="0" max="260" step="1" value="${V.captcha||0}" aria-label="${L('Puzzle position','拼图位置')}" aria-describedby="puzzle-status puzzle-keys" ${disabled?'disabled':''}></div><p id="puzzle-status" class="ops-puzzle-status" role="status" aria-live="polite">${puzzleCopy()}</p>${captchaErrors>=3&&!cool?`<p class="hint">${L('Having trouble? Use the refresh button at the top right for a new puzzle.','遇到困难？点击右上角刷新换一张。')}</p>`:''}<p class="hint" id="puzzle-keys">${L('Keyboard: use arrow keys to move, then press Enter.','键盘操作：方向键移动，Enter 提交。')}</p><button class="btn-link" data-act="ops-puzzle-help" aria-expanded="${puzzleHelp}">${L('Need help?','需要帮助？')}</button>${puzzleHelp?`<p class="hint" role="status">${L('If you cannot complete verification, contact your platform provider or operations support.','如无法完成验证，请联系平台建设方或运维获取帮助。')}</p>`:''}</div>`,foot:button('ops-cancel-captcha','Cancel','取消',false)}}
function renderPuzzle(focus=false){CF.render();if(focus)queueMicrotask(()=>$('captcha')?.focus())}
function loadPuzzle(failed=false){loadGate();ticket=null;V.captcha='0';const version=++puzzleVersion;if(puzzleRemaining()){puzzle={status:'cooldown',target:170,y:62,variant:0};return}if(captchaUntil){captchaUntil=0;captchaErrors=0;saveGate()}const n=++puzzleSerial;puzzle={status:'loading',failed,target:110+(n*37%113),y:50+(n*13%38),variant:n%4};setTimeout(()=>{if(version!==puzzleVersion||S.layer?.key!=='ops-captcha')return;puzzle.status=failNext==='image'?'load-error':'ready';if(failNext==='image')failNext='';renderPuzzle(true)},300)}
function cancelPuzzle(){puzzleVersion++;ticket=null;puzzle=null;notice=null;restoreEditor();queueMicrotask(()=>{CF.render();document.querySelector('[data-act="ops-send-'+(sendPurpose==='email'?'email':'recovery')+'"]')?.focus()})}
function verifyPuzzle(){loadGate();if(!puzzle||puzzle.status!=='ready'||puzzleRemaining())return;const version=puzzleVersion,position=Number(V.captcha||0),context={target:V[sendPurpose==='email'?'newEmail':'recoveryEmail'],purpose:sendPurpose,source:JSON.stringify(source)};puzzle.status='checking';renderPuzzle();setTimeout(()=>{if(version!==puzzleVersion||S.layer?.key!=='ops-captcha')return;
 if(Math.abs(position-puzzle.target)>3){captchaErrors++;captchaUntil=captchaErrors>=5?Date.now()+60000:0;saveGate();puzzle.status='failed';V.captcha='0';renderPuzzle();setTimeout(()=>{if(version!==puzzleVersion||S.layer?.key!=='ops-captcha')return;loadPuzzle(true);renderPuzzle()},650);return}
 captchaErrors=0;saveGate();ticket={...context,expires:Date.now()+120000,used:false};puzzle.status='passed';renderPuzzle();setTimeout(()=>{if(version!==puzzleVersion||S.layer?.key!=='ops-captcha')return;restoreEditor();startAsync(sendCode)},700);
 },450)}
function sessionLayer(){return {title:L('Your session is expiring','登录即将到期'),html:`<p>${L('Continue working to stay signed in, or sign out now.','您可以继续保持登录，或立即退出。')}</p>`,foot:button('ops-logout','Sign out','退出登录',false)+button('ops-renew','Stay signed in','保持登录')}}
function expire(reason,broadcast=true){puzzleVersion++;ticket=null;puzzle=null;asyncVersion++;busy=false;session=false;verifiedUntil=0;recovery=false;code=null;S.layer=null;S.menu=null;mode='';clean();showLock=false;if(broadcast)save('hc.ops.invalidate',String(Date.now()));jump(P.login);if(reason)CF.toast(text(reason))}
function failPassword(id,unknown=false){a.fail++;if(a.fail>=5){if(Date.now()-a.lastLock>86400000)a.lockTier=0;a.lockTier=Math.min(2,a.lockTier+1);a.lastLock=Date.now();a.lockUntil=Date.now()+(a.lockTier===1?600000:1800000);a.fail=0;if(session){expire(msg('Account locked. Wait before signing in again.','账号已锁定，请稍后重新登录。'));showLock=true;return}}err(id,'Email or password is incorrect.','邮箱或密码不正确。');if(a.fail>=3)E[id]=msg(`Email or password is incorrect. ${5-a.fail} attempts remaining.`,`邮箱或密码不正确，还可尝试 ${5-a.fail} 次。`)}
function emailValue(id){let v=(V[id]||'').trim().toLowerCase();V[id]=v;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)||v.length>254){err(id,'Enter a valid work email (up to 254 characters).','请输入有效工作邮箱，最长 254 个字符。');return null}return v}
function validPassword(){const p=(V.newPassword||'').trim();V.newPassword=p;V.confirmPassword=(V.confirmPassword||'').trim();if(p.length<8||p.length>20||!/[a-z]/i.test(p)||!/\d/.test(p)||/\s/.test(p)){err('newPassword','Use 8–20 characters with a letter, a number, and no spaces.','请输入 8～20 位密码，包含字母和数字，中间不能有空格。');return false}if(p!==V.confirmPassword){err('confirmPassword','The passwords do not match.','两次输入的密码不一致。');return false}if(p===a.password||p===a.initial){err('newPassword','Use a password different from your current and initial passwords.','新密码不能与当前密码或初始密码相同。');return false}return true}
function reauthValid(){if(verifiedUntil>Date.now())return true;mode='reauth';code=null;notice=msg('Verification expired. Enter your current password again.','身份验证已过期，请重新输入当前密码。');return false}
function changePassword(kind){a.password=V.newPassword;if(kind==='first')a.first=false;events.push({event:'password-'+kind,channels:['email','in-app'],to:a.email,at:new Date().toISOString()});expire(msg('Password saved. Please sign in again.','密码已保存，请重新登录。'))}
function startAsync(fn){if(busy)return;busy=true;let version=asyncVersion;CF.render();setTimeout(()=>{if(version!==asyncVersion)return;busy=false;if(failNext==='network'){failNext='';notice=msg('Request timed out. Your input is saved; please retry.','请求超时，已保留输入，请重试。')}else fn();CF.render();focusError()},450)}
function requestCode(purpose){if(purpose==='email'&&!reauthValid())return;const id=purpose==='email'?'newEmail':'recoveryEmail',target=emailValue(id);if(!target)return;if(purpose==='email'&&(target===a.email||target==='taken@example.com')){err(id,target===a.email?'Enter a different email.':'This email is unavailable.',target===a.email?'请输入不同的新邮箱。':'此邮箱不可用。');return}if(sendWait(purpose==='email'?'ops-send-email':'ops-send-recovery'))return;sendPurpose=purpose;S.layer={type:'modal',key:'ops-captcha'};notice=null;puzzleHelp=false;loadPuzzle()}
function sendCode(){loadGate();const now=Date.now(),target=V[sendPurpose==='email'?'newEmail':'recoveryEmail'];
 if(failNext==='ticket-expired'){if(ticket)ticket.expires=0;failNext=''}
 if(failNext==='ticket-source'){if(ticket)ticket.source='different-source';failNext=''}
 if(!ticket||ticket.used||ticket.expires<=now||ticket.target!==target||ticket.purpose!==sendPurpose||ticket.source!==JSON.stringify(source)){ticket=null;notice=msg('Verification expired. Please request a code and verify again.','验证已失效，请重新获取验证码并完成安全验证。');restoreEditor();return}
 ticket.used=true;
 if(sendPurpose==='email'&&(!authenticated()||!reauthValid())){if(session)restoreEditor();return}
 const same=sendHistory.filter(s=>s.target===target),last=same.at(-1),hour=same.filter(s=>now-s.at<3600000),day=same.filter(s=>now-s.at<86400000),network=sendHistory.filter(s=>s.network===source.network),device=sendHistory.filter(s=>s.device===source.device);
 const until=Math.max(last?last.at+60000:0,hour.length>=5?hour[hour.length-5].at+3600000:0,day.length>=10?day[day.length-10].at+86400000:0,mailFailures[target]?.until||0);
 if(until>now){const minutes=Math.max(1,Math.ceil((until-now)/60000)),durationEn=minutes<60?minutes+' minutes':Math.ceil(minutes/60)+' hours',durationZh=minutes<60?minutes+' 分钟':Math.ceil(minutes/60)+' 小时';notice=msg('You have requested too many codes. Try again in '+durationEn+'.','验证码请求过于频繁，请在 '+durationZh+' 后重试。');restoreEditor();return}
 if(failNext==='rate'||network.filter(s=>now-s.at<3600000).length>=20||network.length>=100){failNext='';notice=msg('Too many requests from your network. Please try again later.','当前网络请求过于频繁，请稍后重试。');restoreEditor();return}
 if(source.device&&(device.filter(s=>now-s.at<3600000).length>=10||device.length>=30)){notice=msg('Too many requests from this device. Please try again later.','当前设备请求过于频繁，请稍后重试。');restoreEditor();return}
 if(failNext==='mail'){failNext='';const previous=mailFailures[target];const count=previous&&now-previous.at<60000?previous.count+1:1;mailFailures[target]={count,at:now,until:count>=2?now+60000:0};saveGate();notice=count===1?msg('Email could not be sent. Please request a code to retry.','邮件发送失败，请重新获取验证码。'):msg('Email could not be sent. Wait 60 seconds before trying again.','邮件发送失败，请等待 60 秒后重试。');restoreEditor();return}
 delete mailFailures[target];sendHistory.push({target,at:now,...source});saveGate();seq++;code={value:String(410000+seq),target,purpose:sendPurpose,expires:now+600000,tries:0,used:false};V.code='';notice=null;restoreEditor();}
function restoreEditor(){S.layer=sendPurpose==='email'?{type:'modal',key:'ops-email'}:null}
function checkCode(purpose){const normalized=(V.code||'').replace(/[\s-]/g,'');V.code=normalized;
const target=(V[purpose==='email'?'newEmail':'recoveryEmail']||'').trim().toLowerCase();
if(!code||code.used||code.expires<Date.now()||code.purpose!==purpose||code.target!==target||code.tries>=5||normalized!==code.value||(purpose==='recovery'&&target!==a.email)){if(code){code.tries++;if(code.tries>=5)code.used=true}err('code','The code is invalid or expired. Request a new code if needed.','验证码错误或已失效，请核对或重新获取。');return false}return true}
function authenticated(){if(!session){expire(msg('Your session has ended. Sign in again.','登录已失效，请重新登录。'));return false}if(locked()){expire(msg('Account locked. Please try again later.','账号已锁定，请稍后再试。'));showLock=true;return false}return true}
function submit(act){capture();E={};notice=null;if(busy)return;
if(['ops-save-email','ops-save-password','ops-reauth','ops-send-email','ops-first'].includes(act)&&!authenticated())return;
if(act==='ops-login'){
 const mail=emailValue('email');if(!V.password)err('password','Enter your password.','请输入密码。');if(!mail||!V.password)return;
 startAsync(()=>{if(mail!==a.email||V.password.trim()!==a.password){failPassword('password',mail!==a.email);return}if(locked()){showLock=true;notice=null;return}if(a.first&&a.expired){notice=msg('Your initial password has expired. Contact your platform provider or operations support.','初始密码已过期，请联系平台建设方或运维重新初始化。');return}a.fail=0;session=true;lastActivity=Date.now();sessionEnd=Date.now()+7200000;warned=false;a.lastLogin=new Date().toISOString();S.tz=read('hc.ops.timezone')||S.tz;clean();jump(a.first?P.first:returnTo)});return;
}
if(act==='ops-first'){if(validPassword())startAsync(()=>changePassword('first'));return}
if(act==='ops-send-recovery'){requestCode('recovery');return}
if(act==='ops-send-email'){requestCode('email');return}
if(act==='ops-verify-recovery'){if(!checkCode('recovery'))return;if(locked()){code.used=true;recovery=false;notice='locked';return}if(a.first&&a.expired){notice=msg('Initial password expired. Contact your platform provider or operations support.','初始密码已过期，请联系平台建设方或运维重新初始化。');return}code.used=true;recovery=true;V.newPassword='';V.confirmPassword='';jump(P.reset);return}
if(act==='ops-reset'){if(!recovery){jump(P.forgot);return}if(validPassword())startAsync(()=>changePassword('reset'));return}
if(act==='ops-reauth'){if((V.currentPassword||'').trim()!==a.password){failPassword('currentPassword');return}a.fail=0;verifiedUntil=Date.now()+600000;mode='edit';V.currentPassword='';return}
if(act==='ops-save-password'){if(reauthValid()&&validPassword())startAsync(()=>{if(authenticated()&&reauthValid())changePassword('change')});return}
if(act==='ops-save-email'){if(!reauthValid()||!emailValue('newEmail')||!checkCode('email'))return;startAsync(()=>{if(!authenticated()||!reauthValid())return;if(failNext==='taken'||V.newEmail==='taken@example.com'||V.newEmail===a.email){failNext='';err('newEmail','This email is unavailable. Try another email.','此邮箱不可用，请更换邮箱。');return}const old=a.email;a.email=V.newEmail;code.used=true;events.push({event:'email-changed',channels:['email'],to:[old,a.email],at:new Date().toISOString(),delivery:failNext==='notice'?'one-address-failed':'queued'});failNext='';code=null;mode='';verifiedUntil=0;clean();CF.closeLayer();CF.toast(L('Work email updated.','工作邮箱已修改。'))});return}
}
function beforeRender(){S.end='admin';S.role=session?'ops':'guest';if(session&&locked()){expire(msg('Account locked. Please wait before trying again.','账号已锁定，请稍后再试。'));showLock=true}
if(session&&a.first&&S.page!==P.first)jump(P.first);
if(!session&&![P.login,P.forgot,P.reset].includes(S.page)){if([P.account,P.overview].includes(S.page))returnTo=S.page;jump(P.login)}
if(S.page===P.reset&&!recovery)jump(P.forgot);
S.tz=read('hc.ops.timezone')||S.tz;
}
function afterRender(){document.querySelectorAll('.sidebar .brand-sub').forEach(el=>el.textContent=L('Operations','运营管理'));document.querySelectorAll('#anav').forEach(el=>el.setAttribute('aria-label',L('Main navigation','主导航')));if($('focusTools')&&S.page===P.first)$('focusTools').innerHTML+=button('ops-logout','Sign out','退出登录',false);
document.querySelectorAll('#app,#focus').forEach(el=>el.inert=!!S.layer);
}
function demoButton(act,en,zh,value=''){return `<button class="btn sm" data-act="${act}" data-v="${value}">${L(en,zh)}</button>`}
function demo(){return `<h5>${L('Local demonstration · fictional data','本地演示 · 虚构数据')}</h5><p class="hint">${L('Use the buttons below to load a fictional account. Credentials are filled only in the sign-in form. No real emails are sent.','以下按钮载入演示账号，凭据仅填入登录表单，不发送真实邮件。')}</p><div class="ops-demo-actions">${demoButton('ops-seed','First sign-in','首次登录','first')}${demoButton('ops-seed','Administrator','运营管理员','admin')}${demoButton('ops-seed','Specialist','运营专员','specialist')}${demoButton('ops-seed','Expired initial password','初始密码过期','expired')}${demoButton('ops-seed','Locked · 10 seconds left','锁定剩余 10 秒','locked')}</div><h5>${L('Next request','下次请求')}</h5><div class="ops-demo-actions">${demoButton('ops-fault','Puzzle image fails','拼图加载失败','image')}${demoButton('ops-fault','Verification expires','滑块结果过期','ticket-expired')}${demoButton('ops-fault','Request source changes','请求来源改变','ticket-source')}${demoButton('ops-device',source.device?'Disable device identification':'Restore device identification',source.device?'设备识别不可用':'恢复设备识别')}${demoButton('ops-fault','Timeout','请求超时','network')}${demoButton('ops-fault','Email delivery fails','验证码发送失败','mail')}${demoButton('ops-fault','Rate limited','发送限频','rate')}${demoButton('ops-fault','Email taken at submit','提交时邮箱被占用','taken')}${demoButton('ops-fault','Security notice fails','安全通知失败','notice')}</div><p class="hint">${L('Pending fault: ','待触发异常：')}${esc(failNext||'—')}</p><h5>${L('Verification and session','验证与会话')}</h5><div class="ops-demo-actions">${demoButton('ops-fill-code','Fill demo code','填入演示验证码')}${demoButton('ops-expire-code','Expire code','验证码过期')}${demoButton('ops-expire-auth','Expire reauthentication','再认证过期')}${demoButton('ops-session-warning','Session expiry warning','会话到期提醒')}${demoButton('ops-session-expire','Session invalidated','会话失效')}${demoButton('ops-probe','Try unauthorized action','尝试未授权动作')}</div>${code?`<p class="hint">${L('Demo code','演示验证码')} (${esc(code.target)}): <strong>${code.value}</strong> · ${esc(code.purpose)}</p>`:''}<h5>${L('Account page','账户页')}</h5><div class="ops-demo-actions">${['default','loading','error','denied'].map(v=>demoButton('ops-state',({default:'Default',loading:'Loading',error:'Load failed',denied:'No access'})[v],({default:'默认',loading:'加载中',error:'加载失败',denied:'无权限'})[v],v)).join('')}</div><p class="hint">${L('Simulated notification events: ','模拟通知事件：')}${events.length}</p>${events.map(e=>`<p class="hint">${esc(e.event)} · ${esc(String(e.to))} · ${CF.fmtTime(e.at)}</p>`).join('')}`}

const accountModule={id:'ops-account',demoOnly:true,reviewToolsInLayer:true,dict:{en:{navOpsLogin:'Sign in',navOpsFirst:'Set a new password',navOpsForgot:'Reset your password',navOpsReset:'New password',navOpsAccount:'Account settings',navOverview:'Overview',navGroupOps:'Operations',opsCrumb:'Operations'},zh:{navOpsLogin:'登录',navOpsFirst:'首次登录 · 设置新密码',navOpsForgot:'找回密码',navOpsReset:'设置新密码',navOpsAccount:'账户设置',navOverview:'总览',navGroupOps:'运营管理',opsCrumb:'运营管理'}},beforeRender,afterRender,adminTools:accountMenu,adminNotifications:()=>CF.opsNotifications&&can(12)?CF.opsNotifications.bell():'',allowNav:id=>id===P.overview||!!(CF.PAGES[id].permission&&can(CF.PAGES[id].permission)),content:id=>({[P.login]:login,[P.first]:first,[P.forgot]:forgot,[P.reset]:reset,[P.account]:settings,[P.overview]:overview}[id]||overview)(),layers:{'ops-email':emailEditor,'ops-password':passwordEditor,'ops-captcha':captcha,'ops-session':sessionLayer},demo,
onBeforeAct(act,v,event){capture();if(act==='closelayer'&&event.type==='click'&&event.target.closest('[data-stop]')&&!event.target.closest('button[data-act="closelayer"]'))return false;if(act==='lang'){S.lang=v;save('hc.ops.language',v);S.menu=null;return true}if(busy&&act!=='ops-show'&&act!=='demo')return true;if(act==='closelayer'){if(S.layer&&S.layer.key==='ops-session'){return true}if(S.layer&&S.layer.key==='ops-captcha'){cancelPuzzle();return true}mode='';verifiedUntil=0;code=null;clean();return false}return false},
onAct(act,v){
 if(act==='ops-send-email'||act==='ops-send-recovery'){submit(act);queueMicrotask(focusError);return true}
 if(act==='ops-show'){visible[v]=!visible[v];queueMicrotask(()=>document.querySelector('[data-act="ops-show"][data-v="'+v+'"]')?.focus({preventScroll:true}));return true}
 if(act==='ops-login'||act==='ops-first'||act==='ops-reset'||act==='ops-reauth'){submit(act);return true}
 if(act==='ops-settings'){clean();S.menu=null;jump(P.account);return true}
 if(act==='ops-notifications'){if(CF.opsNotifications&&can(12))CF.opsNotifications.open();return true}
 if(act==='ops-logout'){expire(msg('Signed out on all devices.','已退出所有设备上的登录。'));return true}
 if(act==='ops-email'||act==='ops-password'){if(!can(14)){CF.toast(L('You do not have permission.','您没有操作权限。'));return true}clean();mode='reauth';verifiedUntil=0;code=null;CF.openLayer('modal',act);return true}
 if(act==='ops-cancel'){mode='';verifiedUntil=0;code=null;clean();CF.closeLayer();return true}
 if(act==='ops-cancel-captcha'){cancelPuzzle();return true}
 if(act==='ops-puzzle-refresh'){if(!puzzleRemaining()&&!['checking','passed','loading'].includes(puzzle?.status))loadPuzzle();return true}
 if(act==='ops-puzzle-help'){puzzleHelp=!puzzleHelp;return true}
 if(act==='ops-captcha'){verifyPuzzle();return true}
 if(act==='ops-tab'){accountTab=v;queueMicrotask(()=>{const section=$('ops-'+v);section?.focus({preventScroll:true});section?.scrollIntoView({block:'start'})});return true}
 if(act==='ops-renew'){sessionEnd=Date.now()+7200000;lastActivity=Date.now();warned=false;CF.closeLayer();return true}
 if(act==='ops-seed'){asyncVersion++;busy=false;a=fresh();if(v==='admin'||v==='specialist'||v==='locked'){a.first=false;a.password='Harbour123';a.role=v==='admin'?'admin':'specialist'}a.expired=v==='expired';if(v==='locked'){a.lockUntil=Date.now()+10000;a.lockTier=1}expire(null,false);returnTo=P.overview;V.email=a.email;V.password=a.password;V.recoveryEmail=a.email;showLock=false;sendHistory=[];captchaErrors=0;captchaUntil=0;mailFailures={};source.device='demo-device';saveGate();failNext='';events=[];return true}
 if(act==='ops-fault'){failNext=v;return true}
 if(act==='ops-device'){source.device=source.device?null:'demo-device';return true}
 if(act==='ops-fill-code'){if(code)V.code=code.value;return true}
 if(act==='ops-expire-code'){if(code)code.expires=0;return true}
 if(act==='ops-expire-auth'){verifiedUntil=0;return true}
 if(act==='ops-session-warning'){if(session){sessionEnd=Date.now()+60000;warned=true;CF.openLayer('modal','ops-session')}else CF.toast(L('Sign in first.','请先登录。'));return true}
 if(act==='ops-session-expire'){returnTo=S.page===P.account?P.account:P.overview;expire(msg('Session expired. Sign in again.','登录已失效，请重新登录。'));return true}
 if(act==='ops-probe'){CF.toast(can(6)?L('Permission granted. Review work belongs to the certification module.','权限校验通过，审核业务由认证模块承接。'):L('You do not have permission to perform this action.','您没有执行此操作的权限。'));return true}
 if(act==='ops-state'){S.st=v;return true}
 return false;
},onRoute(prev,id){if(S.layer?.key==='ops-captcha'){puzzleVersion++;ticket=null;puzzle=null;S.layer=null}capture();E={};notice=null;if(!session&&[P.account,P.overview].includes(id))returnTo=id;if(prev===P.first&&!session)returnTo=P.overview;}
};
CF.opsAccountModule=accountModule;
CF.define(accountModule);
document.addEventListener('submit',e=>{if(e.target.dataset.submit){e.preventDefault();submit(e.target.dataset.submit);CF.render();focusError()}});
document.addEventListener('input',e=>{const id=e.target.dataset.field;if(!id)return;V[id]=e.target.value;if(id==='captcha'){puzzle.failed=false;$('puzzle-piece')?.setAttribute('transform','translate('+(Number(V.captcha)+8)+' '+puzzle.y+')');return}refreshSendButtons();
 if(E[id]){delete E[id];e.target.setAttribute('aria-invalid','false');if($(id+'-error'))$(id+'-error').textContent=''}
 if(id==='newPassword'||id==='confirmPassword'){
  const confirmation=(V.confirmPassword||'').trim(),mismatch=confirmation.length>0&&confirmation!==(V.newPassword||'').trim();
  if(mismatch)err('confirmPassword','The passwords do not match.','两次输入的密码不一致。');else delete E.confirmPassword;
  $('confirmPassword')?.setAttribute('aria-invalid',String(mismatch));
  if($('confirmPassword-error'))$('confirmPassword-error').textContent=text(E.confirmPassword);
  document.querySelectorAll('.ops-rules').forEach(el=>el.outerHTML=rules());const f=e.target.closest('form');if(f)f.querySelector('button[type=submit]').disabled=busy||!passwordReady();
 }
});
document.addEventListener('pointerdown',e=>{puzzlePointer=e.target.id==='captcha'});
document.addEventListener('pointerup',()=>{if(puzzlePointer){puzzlePointer=false;if($('captcha'))V.captcha=$('captcha').value;verifyPuzzle()}});
document.addEventListener('pointercancel',()=>{if(puzzlePointer){puzzlePointer=false;V.captcha='0';renderPuzzle(true)}});
document.addEventListener('keydown',e=>{if(e.target.id==='captcha'&&e.key==='Enter'){e.preventDefault();V.captcha=e.target.value;verifyPuzzle()}});
document.addEventListener('change',e=>{if(e.target.id==='ops-language'){S.lang=e.target.value;save('hc.ops.language',S.lang);CF.render()}if(e.target.id==='ops-timezone'){S.tz=e.target.value;save('hc.ops.timezone',S.tz);CF.render();CF.toast(L('Time zone updated.','时区已更新。'))}});
['click','keydown','submit'].forEach(type=>document.addEventListener(type,e=>{if(e.isTrusted&&session)lastActivity=Date.now()}));
window.addEventListener('storage',e=>{if(e.key===gateKey){loadGate();if(S.layer?.key==='ops-captcha'&&puzzleRemaining()){puzzleVersion++;ticket=null;puzzle.status='cooldown';renderPuzzle()}refreshSendButtons()}if(e.key==='hc.ops.invalidate'&&session){expire(msg('Session ended on another tab. Sign in again.','其他标签页已退出登录，请重新登录。'),false);CF.render()}});
CF.opsAuth={can,seedDemo(role='admin'){asyncVersion++;busy=false;a=fresh();a.role=role;a.first=false;a.password='Harbour123';session=true;sessionEnd=Date.now()+7200000;lastActivity=Date.now();warned=false;clean();},getIdentity:()=>({email:a.email,name:text(a.name),role:a.role,permissions:permissionGroups().flatMap(g=>g[2].filter(p=>can(p[0])).map(p=>'PM-AL-'+String(p[0]).padStart(2,'0'))),language:S.lang,timezone:S.tz})};
if(!CF.deferOpsBoot&&!Object.values(P).some(id=>location.hash.split('?')[0]==='#'+R(id)))location.hash='#'+R(P.login);
if(!CF.deferOpsBoot)CF.boot();
setInterval(()=>{refreshSendButtons();if(a.lockUntil&&a.lockUntil<=Date.now()){a.lockUntil=0;a.fail=0;showLock=false;capture();CF.render()}if($('lockText'))$('lockText').textContent=lockCopy();if(captchaUntil&&captchaUntil<=Date.now()){captchaUntil=0;captchaErrors=0;saveGate();if(S.layer?.key==='ops-captcha'){loadPuzzle();renderPuzzle()}}if($('puzzle-status'))$('puzzle-status').textContent=puzzleCopy();if(session){if(Date.now()>=sessionEnd||Date.now()-lastActivity>=1800000){returnTo=S.page===P.account?P.account:P.overview;expire(msg('Your session expired. Please sign in again.','登录已到期，请重新登录。'));CF.render()}else if(sessionEnd-Date.now()<60000&&!warned&&!S.layer){warned=true;capture();CF.openLayer('modal','ops-session')}}},1000);
})(window.CF);
