/* Local interactive prototype. All identities, delivery events and credentials are fictional.
   No authentication, email or permission server is contacted. */
(function(CF){
'use strict';
const S=CF.S, L=CF.L, esc=CF.esc, $=id=>document.getElementById(id);
const P={login:'P-O-AL-01',first:'P-O-AL-03',forgot:'P-O-AL-04',reset:'P-O-AL-05',account:'P-O-AL-06',overview:'P-O-AL-07'};
const R=id=>CF.ENTRY[id];
const fresh=()=>({email:'operator@example.com',name:['Demo Operator','演示操作员'],role:'specialist',first:true,expired:false,password:'Start1234',initial:'Start1234',fail:0,lockUntil:0,lockTier:0,lastLock:0,created:'2026-09-18T02:00:00Z',lastLogin:null});
let a=fresh(), session=false, V={}, E={}, notice=null, busy=false, mode='',verifiedUntil=0, recovery=false, code=null,seq=0,sendHistory=[],captchaErrors=0,captchaUntil=0,sendPurpose='',showLock=false,returnTo=P.overview,accountTab='info',failNext='',events=[],sessionEnd=0,lastActivity=0,warned=false,asyncVersion=0;
const visible={};
const read=k=>{try{return localStorage.getItem(k)}catch(e){return null}};
const save=(k,v)=>{try{localStorage.setItem(k,v)}catch(e){}};
S.end='admin'; S.lang=read('hc.ops.language')||'en';
const role=()=>a.role==='admin'?L('Operations Administrator','运营管理员'):L('Operations Specialist','运营专员');
const permissionGroups=()=>[
 ['cert',L('Institution certification','机构认证'),[[5,L('View applications and documents','申请与材料查询')],[6,L('Review applications','认证审核处置')]]],
 ['pledge',L('Token pledges','代币质押'),[[7,L('View pledge applications','质押申请查询')],[8,L('Review pledge applications','质押审核处置')]]],
 ['agreement',L('Agreements','协议管理'),[[9,L('View content and versions','内容与版本查询')],[10,L('Maintain content and versions','内容与版本维护')],[11,L('Publish versions','版本发布')]]],
 ['general',L('General','通用功能'),[[12,L('View operations messages','运营端消息查看')],[13,L('Query operations data','运营业务数据查询')],[14,L('Personal account settings','本人账户设置')]]]
];
function can(n){return !!session&&!a.first&&!locked()&&(a.role==='admin'||n>=12)}
function locked(){return a.lockUntil>Date.now()}
function jump(id){S.page=id;location.hash='#'+R(id)}
function clean(){V={};E={};notice=null;Object.keys(visible).forEach(k=>delete visible[k])}
function msg(en,zh){return [en,zh]}
function text(m){return m==='locked'?lockCopy():(m?L(m[0],m[1]):'')}
function err(id,en,zh){E[id]=msg(en,zh)}
function feedback(){return `<div class="ops-feedback" role="alert">${esc(text(notice))}</div>`}
function capture(){document.querySelectorAll('[data-field]').forEach(el=>V[el.dataset.field]=el.value)}
function field(id,en,zh,type='text',opts='',trail=''){
 const pw=type==='password',val=V[id]||'',error=E[id];
 return `<div class="field"><label for="${id}">${L(en,zh)}</label><div class="${pw?'ops-secret':trail?'ops-code-row':''}"><input class="inp" id="${id}" data-field="${id}" type="${pw&&visible[id]?'text':type}" value="${esc(val)}" aria-required="true" aria-invalid="${!!error}" aria-describedby="${id}-error" ${busy?'readonly':''} ${opts}>${pw?`<button type="button" data-act="ops-show" data-v="${id}" aria-label="${L('Show or hide password','显示或隐藏密码')}">${visible[id]?L('Hide','隐藏'):L('Show','显示')}</button>`:''}${trail}</div><span class="ops-error" id="${id}-error">${esc(text(error))}</span></div>`;
}
function button(act,en,zh,primary=true,disabled=false){return `<button type="button" class="btn ${primary?'primary':''}" data-act="${act}" ${disabled||busy?'disabled':''}>${busy&&primary?'<span class="spinner" aria-hidden="true"></span>'+L('Please wait…','处理中…'):L(en,zh)}</button>`}
function sendWait(act){let target=(V[act==='ops-send-email'?'newEmail':'recoveryEmail']||'').trim().toLowerCase(),last=sendHistory.filter(x=>x.target===target).at(-1);return last?Math.max(0,Math.ceil((last.at+60000-Date.now())/1000)):0}
function sendLabel(wait){return wait?L('Resend in '+wait+'s',wait+' 秒后重发'):L('Send code','获取验证码')}
function refreshSendButtons(){['ops-send-email','ops-send-recovery'].forEach(act=>{const el=document.querySelector('button[data-act="'+act+'"]');if(!el)return;const wait=sendWait(act);el.disabled=busy||wait>0;if(!busy)el.textContent=sendLabel(wait)})}
function codeField(act){const waiting=sendWait(act);return field('code','Verification code','验证码','text','inputmode="numeric" autocomplete="one-time-code"',`<button type="button" class="btn" data-act="${act}" ${busy||waiting>0?'disabled':''}>${busy?L('Sending…','发送中…'):sendLabel(waiting)}</button>`)}
function form(act,body,btn){return `<form class="ops-form" data-submit="${act}" novalidate aria-busy="${busy}">${feedback()}${body}<button type="submit" class="btn primary block" ${busy||(act==='ops-login'&&showLock&&locked())||(body.includes('id="newPassword"')&&!passwordReady())?'disabled':''}>${busy?'<span class="spinner" aria-hidden="true"></span>'+L('Please wait…','处理中…'):btn}</button></form>`}
function heading(en,zh,subEn,subZh){return `<div class="ops-flow"><p class="ops-eyebrow">${L('OPERATIONS CONSOLE','运营管理平台')}</p><h1>${L(en,zh)}</h1><p class="ops-sub">${L(subEn,subZh)}</p>`}
function passwordReady(){const p=(V.newPassword||'').trim();return p.length>=8&&p.length<=20&&/[a-z]/i.test(p)&&/\d/.test(p)&&! /\s/.test(p)&&p===(V.confirmPassword||'').trim()}
function rules(){const p=(V.newPassword||'').trim();return `<ul class="ops-rules" aria-live="polite">${[[p.length>=8&&p.length<=20,L('8–20 characters','8～20 个字符')],[/[a-z]/i.test(p)&&/\d/.test(p),L('At least one letter and one number','至少包含一个字母与一个数字')],[p.length>0&&!/\s/.test(p),L('No spaces within the password','密码中间不含空格')]].map(x=>`<li class="${x[0]?'met':''}">${x[1]}</li>`).join('')}</ul>`}
function passwordFields(){return field('newPassword','New password','新密码','password','autocomplete="new-password"')+rules()+field('confirmPassword','Confirm new password','确认新密码','password','autocomplete="new-password"')}
function support(){return `<p class="hint">${L('Cannot access your email? Contact your platform provider or operations support to reinitialize your account.','无法访问工作邮箱？请联系平台建设方或运维重新初始化账号。')}</p>`}
function lockCopy(){const seconds=Math.max(0,Math.ceil((a.lockUntil-Date.now())/1000));return L('Account locked. Try again in ','账号已锁定，请在 ')+`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`+L('.',' 后重试。')+(a.lockTier===1?L(' Another lock will last longer.','再次触发时锁定时间会更长。'):'')}
function login(){return heading('Sign in','登录','Use your work email to access the operations console.','使用工作邮箱登录运营管理平台。')+(showLock&&locked()?`<div class="note warn" role="status" id="lockText">${lockCopy()}</div>`:'')+form('ops-login',field('email','Work email','工作邮箱','email','autocomplete="username" maxlength="254"')+field('password','Password','密码','password','autocomplete="current-password"'),L('Sign in','登录'))+`<div class="ops-actions"><a class="btn-link" href="#${R(P.forgot)}">${L('Forgot password?','忘记密码？')}</a></div></div>`}
function first(){return heading('Set a new password','首次登录 · 设置新密码','Change your initial password before accessing your account.','请先修改初始密码，再使用账户功能。')+form('ops-first',field('currentPassword','Current password','当前密码','password','autocomplete="current-password"')+passwordFields()+`<p class="hint">${L('You will need to sign in again after changing your password.','修改后需要重新登录。')}</p>`,L('Save password','保存密码'))+'</div>'}
function forgot(){return heading('Reset your password','找回密码','Verify your work email to continue.','验证工作邮箱后设置新密码。')+`<div class="ops-step"><strong>${L('1 · Verify email','1 · 验证邮箱')}</strong><span>—</span><span>${L('2 · New password','2 · 设置新密码')}</span></div>`+form('ops-verify-recovery',field('recoveryEmail','Work email','工作邮箱','email','autocomplete="email" maxlength="254"')+codeField('ops-send-recovery')+(code&&code.purpose==='recovery'?`<p class="hint" role="status">${L('If this email belongs to an operations account, a code has been sent.','若该邮箱为运营端账号，验证码已发送。')}</p>`:''),L('Verify and continue','验证并继续'))+`<div class="ops-actions"><a class="btn-link" href="#${R(P.login)}">${L('Back to sign in','返回登录')}</a></div>`+support()+'</div>'}
function reset(){return heading('Choose a new password','设置新密码','Your email has been verified.','工作邮箱已验证。')+`<div class="ops-step"><span>${L('1 · Email verified','1 · 邮箱已验证')}</span><span>—</span><strong>${L('2 · New password','2 · 设置新密码')}</strong></div>`+form('ops-reset',passwordFields()+`<p class="hint">${L('All sessions will end. Sign in again with your new password.','所有设备将退出登录，请使用新密码重新登录。')}</p>`,L('Reset password','重置密码'))+`<div class="ops-actions"><a class="btn-link" href="#${R(P.login)}">${L('Back to sign in','返回登录')}</a></div></div>`}
function row(label,value,act){return `<div><dt>${label}</dt><dd>${value}</dd>${act?`<button class="btn-link" data-act="${act}">${L('Change','修改')}</button>`:''}</div>`}
function permissionList(){return permissionGroups().map(g=>{let items=g[2].filter(p=>can(p[0]));return items.length?`<div><strong>${g[1]}</strong><ul class="ops-permissions">${items.map(p=>`<li>${p[1]}</li>`).join('')}</ul></div>`:''}).join('')}
function settings(){let surface=CF.surface({skelRows:4,deniedDesc:L('You do not have permission to view this page. Contact your platform provider.','您没有访问此页面的权限，请联系平台建设方。'),backTo:R(P.overview),backLabel:L('Back to overview','返回总览'),errorTitle:L('Could not load account information','账号信息加载失败'),emptyTitle:L('Account information is unavailable','暂无账号信息'),emptyDesc:L('Reload your account information.','请重新加载账号信息。')});return `<div class="page-head"><div><h1 class="page-title">${L('Account settings','账户设置')}</h1><p class="page-desc">${L('Manage your sign-in details and display preferences.','管理登录信息与显示偏好。')}</p></div></div>`+(surface||`<nav class="ops-tabs" aria-label="${L('Account sections','账户分区')}"><button data-act="ops-tab" data-v="info" aria-current="${accountTab==='info'}">${L('Account information','账号信息')}</button><button data-act="ops-tab" data-v="preferences" aria-current="${accountTab==='preferences'}">${L('Preferences','偏好信息')}</button></nav><div class="ops-settings"><section class="card ops-section" id="ops-info"><h2>${L('Account information','账号信息')}</h2><dl class="ops-details">${row(L('Work email','工作邮箱'),esc(a.email),'ops-email')}${row(L('Name','姓名'),esc(text(a.name)))}${row(L('Role','角色'),role())}${row(L('Status','账号状态'),CF.tag('ok',L('Active','正常')))}${row(L('Password','登录密码'),'••••••••','ops-password')}${row(L('Enabled permissions','已开通功能权限'),permissionList())}${row(L('Last sign-in','最近登录'),a.lastLogin?CF.fmtTime(a.lastLogin):'—')}${row(L('Created','创建时间'),CF.fmtTime(a.created))}</dl></section><section class="card ops-section" id="ops-preferences"><h2>${L('Preferences','偏好信息')}</h2><div class="ops-preferences"><div class="field"><label for="ops-language">${L('Interface language','界面语言')}</label><select class="inp" id="ops-language"><option value="en" ${S.lang==='en'?'selected':''}>English</option><option value="zh" ${S.lang==='zh'?'selected':''}>简体中文</option></select></div><div class="field"><label for="ops-timezone">${L('Time zone','时区')}</label><select class="inp" id="ops-timezone">${Array.from(new Set([S.tz,'UTC','Asia/Shanghai','Asia/Hong_Kong','Asia/Singapore','Europe/London','America/New_York'])).map(z=>`<option ${S.tz===z?'selected':''}>${esc(z)}</option>`).join('')}</select><p class="hint">${L('Times are displayed in your selected time zone.','页面时间按所选时区展示。')}</p></div></div></section></div><p class="ops-sample">${L('Demonstration data','演示数据')}</p>`)}
function overview(){return `<div class="page-head"><div><h1 class="page-title">${L('Overview','总览')}</h1><p class="page-desc">${L('Welcome to the operations console.','欢迎使用运营管理平台。')}</p></div></div>`+CF.empty(L('Your account is ready','账户已就绪'),L('Available operations appear in the navigation. You can manage your account and preferences from the account menu.','已开放的运营功能将显示在导航中。您可以通过账号菜单管理账户及偏好。'),button('ops-settings','Account settings','账户设置',false))}
function accountMenu(){return `<div class="dd"><button class="dd-btn" data-act="menu" data-v="ops-account" aria-haspopup="menu" aria-expanded="${S.menu==='ops-account'}"><span class="op-avatar xs">OP</span>${L('Account','我的账户')} ▾</button>${S.menu==='ops-account'?`<div class="dd-list" role="menu"><div class="ops-account-email">${esc(a.email)}<br>${CF.tag('ok',L('Active','正常'))}</div>${CF.opsNotifications&&can(12)?`<button role="menuitem" data-act="ops-notifications">${L('Notifications','消息中心')}</button>`:''}<button role="menuitem" data-act="ops-settings">${L('Account settings','账户设置')}</button><button role="menuitem" data-act="ops-logout">${L('Sign out','退出登录')}</button></div>`:''}</div>`}
function identity(){return `<div class="op-row"><span class="op-avatar">OP</span><div><div class="op-name">${role()}</div><div class="op-role">${L('Demonstration account','演示账户')}</div></div></div>`}
function emailEditor(){if(mode==='reauth')return {title:L('Verify your identity','验证身份'),html:form('ops-reauth',field('currentPassword','Current password','当前密码','password','autocomplete="current-password"'),L('Continue','继续')),foot:button('ops-cancel','Cancel','取消',false)};
return {title:L('Change work email','修改工作邮箱'),html:`<p class="ops-sub">${L('Your new email will become your sign-in and recovery address.','新邮箱将用于登录与找回密码。')}</p><p class="hint">${L('Current email: ','当前邮箱：')}${esc(a.email)}</p>`+form('ops-save-email',field('newEmail','New work email','新工作邮箱','email','autocomplete="email" maxlength="254"')+codeField('ops-send-email')+(code&&code.purpose==='email'?`<p class="hint" role="status">${L('Code sent to ','验证码已发送至 ')}${esc(code.target)}</p>`:''),L('Confirm email change','确认修改邮箱')),foot:button('ops-cancel','Cancel','取消',false)}}
function passwordEditor(){if(mode==='reauth')return {title:L('Verify your identity','验证身份'),html:form('ops-reauth',field('currentPassword','Current password','当前密码','password','autocomplete="current-password"'),L('Continue','继续')),foot:button('ops-cancel','Cancel','取消',false)};return {title:L('Change password','修改密码'),html:form('ops-save-password',passwordFields()+`<p class="hint">${L('All devices will be signed out after this change.','修改后所有设备将退出登录。')}</p>`,L('Save password','保存密码')),foot:button('ops-cancel','Cancel','取消',false)}}
function captcha(){return {title:L('Security verification','安全验证'),html:`<div class="ops-form">${feedback()}<label for="captcha">${L('Move the slider all the way to the right.','请将滑块拖动到最右端。')}</label><input id="captcha" class="ops-captcha" data-field="captcha" type="range" min="0" max="100" value="${V.captcha||0}" ${Date.now()<captchaUntil?'disabled':''}><p class="hint">${Date.now()<captchaUntil?L('Please wait 60 seconds and retry.','请等待 60 秒后重试。'):L('You can also use the arrow keys.','也可使用键盘方向键操作。')}</p>${support()}</div>`,foot:button('ops-cancel-captcha','Cancel','取消',false)+button('ops-captcha','Verify','验证',true,Date.now()<captchaUntil)}}
function sessionLayer(){return {title:L('Your session is expiring','登录即将到期'),html:`<p>${L('Continue working to stay signed in, or sign out now.','您可以继续保持登录，或立即退出。')}</p>`,foot:button('ops-logout','Sign out','退出登录',false)+button('ops-renew','Stay signed in','保持登录')}}
function expire(reason,broadcast=true){asyncVersion++;busy=false;session=false;verifiedUntil=0;recovery=false;code=null;S.layer=null;S.menu=null;mode='';clean();showLock=false;if(broadcast)save('hc.ops.invalidate',String(Date.now()));jump(P.login);if(reason)CF.toast(text(reason))}
function failPassword(id,unknown=false){a.fail++;if(a.fail>=5){if(Date.now()-a.lastLock>86400000)a.lockTier=0;a.lockTier=Math.min(2,a.lockTier+1);a.lastLock=Date.now();a.lockUntil=Date.now()+(a.lockTier===1?600000:1800000);a.fail=0;if(session){expire(msg('Account locked. Wait before signing in again.','账号已锁定，请稍后重新登录。'));showLock=true;return}}err(id,'Email or password is incorrect.','邮箱或密码不正确。');if(a.fail>=3)E[id]=msg(`Email or password is incorrect. ${5-a.fail} attempts remaining.`,`邮箱或密码不正确，还可尝试 ${5-a.fail} 次。`)}
function emailValue(id){let v=(V[id]||'').trim().toLowerCase();V[id]=v;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)||v.length>254){err(id,'Enter a valid work email (up to 254 characters).','请输入有效工作邮箱，最长 254 个字符。');return null}return v}
function validPassword(){const p=(V.newPassword||'').trim();V.newPassword=p;V.confirmPassword=(V.confirmPassword||'').trim();if(p.length<8||p.length>20||!/[a-z]/i.test(p)||!/\d/.test(p)||/\s/.test(p)){err('newPassword','Use 8–20 characters with a letter, a number, and no spaces.','请输入 8～20 位密码，包含字母和数字，中间不能有空格。');return false}if(p!==V.confirmPassword){err('confirmPassword','The passwords do not match.','两次输入的密码不一致。');return false}if(p===a.password||p===a.initial){err('newPassword','Use a password different from your current and initial passwords.','新密码不能与当前密码或初始密码相同。');return false}return true}
function reauthValid(){if(verifiedUntil>Date.now())return true;mode='reauth';code=null;notice=msg('Verification expired. Enter your current password again.','身份验证已过期，请重新输入当前密码。');return false}
function changePassword(kind){a.password=V.newPassword;if(kind==='first')a.first=false;events.push({event:'password-'+kind,channels:['email','in-app'],to:a.email,at:new Date().toISOString()});expire(msg('Password saved. Please sign in again.','密码已保存，请重新登录。'))}
function startAsync(fn){if(busy)return;busy=true;let version=asyncVersion;CF.render();setTimeout(()=>{if(version!==asyncVersion)return;busy=false;if(failNext==='network'){failNext='';notice=msg('Request timed out. Your input is saved; please retry.','请求超时，已保留输入，请重试。')}else fn();CF.render()},450)}
function requestCode(purpose){if(purpose==='email'&&!reauthValid())return;const id=purpose==='email'?'newEmail':'recoveryEmail',target=emailValue(id);if(!target)return;if(purpose==='email'&&(target===a.email||target==='taken@example.com')){err(id,target===a.email?'Enter a different email.':'This email is unavailable.',target===a.email?'请输入不同的新邮箱。':'此邮箱不可用。');return}sendPurpose=purpose;V.captcha='0';S.layer={type:'modal',key:'ops-captcha'};notice=null}
function sendCode(){const now=Date.now(),target=V[sendPurpose==='email'?'newEmail':'recoveryEmail'];let same=sendHistory.filter(s=>s.target===target),last=same.at(-1),hour=same.filter(s=>now-s.at<3600000),day=same.filter(s=>now-s.at<86400000);
if(failNext==='rate'||(last&&now-last.at<60000)||hour.length>=5||day.length>=10||sendHistory.filter(s=>now-s.at<3600000).length>=10){failNext='';notice=msg('Too many requests. Please wait before requesting another code.','发送过于频繁，请稍后再获取验证码。');restoreEditor();return}
if(failNext==='mail'){failNext='';notice=msg('Email could not be sent. Retry now.','邮件发送失败，请立即重试。');restoreEditor();return}
sendHistory.push({target,at:now});seq++;code={value:String(410000+seq),target,purpose:sendPurpose,expires:now+600000,tries:0,used:false};V.code='';notice=null;restoreEditor();}
function restoreEditor(){S.layer=sendPurpose==='email'?{type:'modal',key:'ops-email'}:null}
function checkCode(purpose){const normalized=(V.code||'').replace(/[\s-]/g,'');V.code=normalized;
const target=(V[purpose==='email'?'newEmail':'recoveryEmail']||'').trim().toLowerCase();
if(!code||code.used||code.expires<Date.now()||code.purpose!==purpose||code.target!==target||code.tries>=5||normalized!==code.value||(purpose==='recovery'&&target!==a.email)){if(code){code.tries++;if(code.tries>=5)code.used=true}err('code','The code is invalid or expired. Request a new code if needed.','验证码错误或已失效，请核对或重新获取。');return false}return true}
function authenticated(){if(!session){expire(msg('Your session has ended. Sign in again.','登录已失效，请重新登录。'));return false}if(locked()){expire(msg('Account locked. Please try again later.','账号已锁定，请稍后再试。'));showLock=true;return false}return true}
function submit(act){capture();E={};notice=null;if(busy)return;
if(['ops-save-email','ops-save-password','ops-reauth','ops-send-email','ops-first'].includes(act)&&!authenticated())return;
if(act==='ops-login'){
 const mail=emailValue('email');if(!V.password)err('password','Enter your password.','请输入密码。');if(!mail||!V.password)return;
 startAsync(()=>{if(mail!==a.email||V.password.trim()!==a.password){failPassword('password',mail!==a.email);return}if(locked()){showLock=true;notice=null;return}if(a.first&&a.expired){notice=msg('Your initial password has expired. Contact your platform provider or operations support.','初始密码已过期，请联系平台建设方或运维重新初始化。');return}a.fail=0;session=true;lastActivity=Date.now();sessionEnd=Date.now()+7200000;warned=false;a.lastLogin=new Date().toISOString();S.tz=read('hc.ops.timezone')||S.tz;clean();jump(a.first?P.first:returnTo)});return;
}
if(act==='ops-first'){if((V.currentPassword||'').trim()!==a.password){failPassword('currentPassword');return}if(validPassword())startAsync(()=>changePassword('first'));return}
if(act==='ops-send-recovery'){requestCode('recovery');return}
if(act==='ops-send-email'){requestCode('email');return}
if(act==='ops-verify-recovery'){if(!checkCode('recovery'))return;if(locked()){code.used=true;recovery=false;notice='locked';return}if(a.first&&a.expired){notice=msg('Initial password expired. Contact your platform provider or operations support.','初始密码已过期，请联系平台建设方或运维重新初始化。');return}code.used=true;recovery=true;V.newPassword='';V.confirmPassword='';jump(P.reset);return}
if(act==='ops-reset'){if(!recovery){jump(P.forgot);return}if(validPassword())startAsync(()=>changePassword('reset'));return}
if(act==='ops-reauth'){if((V.currentPassword||'').trim()!==a.password){failPassword('currentPassword');return}a.fail=0;verifiedUntil=Date.now()+600000;mode='edit';V.currentPassword='';return}
if(act==='ops-save-password'){if(reauthValid()&&validPassword())startAsync(()=>{if(authenticated()&&reauthValid())changePassword('change')});return}
if(act==='ops-save-email'){if(!reauthValid()||!emailValue('newEmail')||!checkCode('email'))return;startAsync(()=>{if(!authenticated()||!reauthValid())return;if(failNext==='taken'||V.newEmail==='taken@example.com'||V.newEmail===a.email){failNext='';err('newEmail','This email is unavailable. Try another email.','此邮箱不可用，请更换邮箱。');return}const old=a.email;a.email=V.newEmail;code.used=true;events.push({event:'email-changed',channels:['email'],to:[old,a.email],at:new Date().toISOString(),delivery:failNext==='notice'?'one-address-failed':'queued'});failNext='';code=null;mode='';verifiedUntil=0;clean();CF.closeLayer();CF.toast(L('Work email updated.','工作邮箱已修改。'))});return}
}
function beforeRender(){S.end='admin';S.role=session?'ops':'guest';if(session&&locked()){expire(msg('Account locked. Please wait before trying again.','账号已锁定，请稍后再试。'));showLock=true}
if(session&&a.first&&S.page!==P.first)jump(P.first);
if(!session&&![P.login,P.forgot,P.reset].includes(S.page)){if([P.account,P.overview].includes(S.page))returnTo=S.page;jump(P.login)}
if(S.page===P.reset&&!recovery)jump(P.forgot);
S.tz=read('hc.ops.timezone')||S.tz;
}
function afterRender(){document.querySelectorAll('.sidebar .brand-sub').forEach(el=>el.textContent=L('Operations','运营管理'));document.querySelectorAll('#anav').forEach(el=>el.setAttribute('aria-label',L('Main navigation','主导航')));if($('focusTools')&&S.page===P.first)$('focusTools').innerHTML+=button('ops-logout','Sign out','退出登录',false);
if(S.page===P.account)$('acrumb').innerHTML=`<a class="crumb-link" href="#${R(P.overview)}">${L('Overview','总览')}</a><span>/</span><span class="crumb-cur">${L('Account settings','账户设置')}</span>`;
document.querySelectorAll('#app,#focus').forEach(el=>el.inert=!!S.layer);
}
function demoButton(act,en,zh,value=''){return `<button class="btn sm" data-act="${act}" data-v="${value}">${L(en,zh)}</button>`}
function demo(){return `<h5>${L('Local demonstration · fictional data','本地演示 · 虚构数据')}</h5><p class="hint">${L('Use the buttons below to load a fictional account. Credentials are filled only in the sign-in form. No real emails are sent.','以下按钮载入演示账号，凭据仅填入登录表单，不发送真实邮件。')}</p><div class="ops-demo-actions">${demoButton('ops-seed','First sign-in','首次登录','first')}${demoButton('ops-seed','Administrator','运营管理员','admin')}${demoButton('ops-seed','Specialist','运营专员','specialist')}${demoButton('ops-seed','Expired initial password','初始密码过期','expired')}${demoButton('ops-seed','Locked · 10 seconds left','锁定剩余 10 秒','locked')}</div><h5>${L('Next request','下次请求')}</h5><div class="ops-demo-actions">${demoButton('ops-fault','Timeout','请求超时','network')}${demoButton('ops-fault','Email delivery fails','验证码发送失败','mail')}${demoButton('ops-fault','Rate limited','发送限频','rate')}${demoButton('ops-fault','Email taken at submit','提交时邮箱被占用','taken')}${demoButton('ops-fault','Security notice fails','安全通知失败','notice')}</div><p class="hint">${L('Pending fault: ','待触发异常：')}${esc(failNext||'—')}</p><h5>${L('Verification and session','验证与会话')}</h5><div class="ops-demo-actions">${demoButton('ops-fill-code','Fill demo code','填入演示验证码')}${demoButton('ops-expire-code','Expire code','验证码过期')}${demoButton('ops-expire-auth','Expire reauthentication','再认证过期')}${demoButton('ops-session-warning','Session expiry warning','会话到期提醒')}${demoButton('ops-session-expire','Session invalidated','会话失效')}${demoButton('ops-probe','Try unauthorized action','尝试未授权动作')}</div>${code?`<p class="hint">${L('Demo code','演示验证码')} (${esc(code.target)}): <strong>${code.value}</strong> · ${esc(code.purpose)}</p>`:''}<h5>${L('Account page','账户页')}</h5><div class="ops-demo-actions">${['default','loading','error','denied'].map(v=>demoButton('ops-state',({default:'Default',loading:'Loading',error:'Load failed',denied:'No access'})[v],({default:'默认',loading:'加载中',error:'加载失败',denied:'无权限'})[v],v)).join('')}</div><p class="hint">${L('Simulated notification events: ','模拟通知事件：')}${events.length}</p>${events.map(e=>`<p class="hint">${esc(e.event)} · ${esc(String(e.to))} · ${CF.fmtTime(e.at)}</p>`).join('')}`}
CF.NAV.admin=[P.overview];
CF.define({id:'ops-account',demoOnly:true,reviewToolsInLayer:true,dict:{en:{navOpsLogin:'Sign in',navOpsFirst:'Set a new password',navOpsForgot:'Reset your password',navOpsReset:'New password',navOpsAccount:'Account settings',navOverview:'Overview',navGroupOps:'Operations',opsCrumb:'Operations'},zh:{navOpsLogin:'登录',navOpsFirst:'首次登录 · 设置新密码',navOpsForgot:'找回密码',navOpsReset:'设置新密码',navOpsAccount:'账户设置',navOverview:'总览',navGroupOps:'运营管理',opsCrumb:'运营管理'}},beforeRender,afterRender,adminTools:accountMenu,adminIdentity:identity,adminNotifications:()=>CF.opsNotifications&&can(12)?CF.opsNotifications.bell():'',allowNav:id=>id===P.overview||!!(CF.PAGES[id].permission&&can(CF.PAGES[id].permission)),content:id=>({[P.login]:login,[P.first]:first,[P.forgot]:forgot,[P.reset]:reset,[P.account]:settings,[P.overview]:overview}[id]||overview)(),layers:{'ops-email':emailEditor,'ops-password':passwordEditor,'ops-captcha':captcha,'ops-session':sessionLayer},demo,
onBeforeAct(act,v,event){capture();if(act==='closelayer'&&event.type==='click'&&event.target.closest('[data-stop]')&&!event.target.closest('button[data-act="closelayer"]'))return false;if(act==='lang'){S.lang=v;save('hc.ops.language',v);S.menu=null;return true}if(busy&&act!=='ops-show'&&act!=='demo')return true;if(act==='closelayer'){if(S.layer&&S.layer.key==='ops-session'){return true}if(S.layer&&S.layer.key==='ops-captcha'){restoreEditor();notice=null;return true}mode='';verifiedUntil=0;code=null;clean();return false}return false},
onAct(act,v){
 if(act==='ops-send-email'||act==='ops-send-recovery'){submit(act);return true}
 if(act==='ops-show'){visible[v]=!visible[v];return true}
 if(act==='ops-login'||act==='ops-first'||act==='ops-reset'||act==='ops-reauth'){submit(act);return true}
 if(act==='ops-settings'){clean();S.menu=null;jump(P.account);return true}
 if(act==='ops-notifications'){if(CF.opsNotifications&&can(12))CF.opsNotifications.open();return true}
 if(act==='ops-logout'){expire(msg('Signed out on all devices.','已退出所有设备上的登录。'));return true}
 if(act==='ops-email'||act==='ops-password'){if(!can(14)){CF.toast(L('You do not have permission.','您没有操作权限。'));return true}clean();mode='reauth';verifiedUntil=0;code=null;CF.openLayer('modal',act);return true}
 if(act==='ops-cancel'){mode='';verifiedUntil=0;code=null;clean();CF.closeLayer();return true}
 if(act==='ops-cancel-captcha'){notice=null;restoreEditor();return true}
 if(act==='ops-captcha'){if(Date.now()<captchaUntil)return true;if(Number(V.captcha)<100){captchaErrors++;V.captcha='0';notice=msg('Verification failed. Move the slider to the end and retry.','验证未通过，请将滑块移至最右端后重试。');if(captchaErrors>=5){captchaUntil=Date.now()+60000;captchaErrors=0}return true}captchaErrors=0;startAsync(sendCode);return true}
 if(act==='ops-tab'){accountTab=v;setTimeout(()=>$('ops-'+v)?.scrollIntoView({block:'start'}),0);return true}
 if(act==='ops-renew'){sessionEnd=Date.now()+7200000;lastActivity=Date.now();warned=false;CF.closeLayer();return true}
 if(act==='ops-seed'){asyncVersion++;busy=false;a=fresh();if(v==='admin'||v==='specialist'||v==='locked'){a.first=false;a.password='Harbour123';a.role=v==='admin'?'admin':'specialist'}a.expired=v==='expired';if(v==='locked'){a.lockUntil=Date.now()+10000;a.lockTier=1}expire(null,false);returnTo=P.overview;V.email=a.email;V.password=a.password;V.recoveryEmail=a.email;showLock=false;sendHistory=[];failNext='';events=[];return true}
 if(act==='ops-fault'){failNext=v;return true}
 if(act==='ops-fill-code'){if(code)V.code=code.value;return true}
 if(act==='ops-expire-code'){if(code)code.expires=0;return true}
 if(act==='ops-expire-auth'){verifiedUntil=0;return true}
 if(act==='ops-session-warning'){if(session){sessionEnd=Date.now()+60000;warned=true;CF.openLayer('modal','ops-session')}else CF.toast(L('Sign in first.','请先登录。'));return true}
 if(act==='ops-session-expire'){returnTo=S.page===P.account?P.account:P.overview;expire(msg('Session expired. Sign in again.','登录已失效，请重新登录。'));return true}
 if(act==='ops-probe'){CF.toast(can(6)?L('Permission granted. Review work belongs to the certification module.','权限校验通过，审核业务由认证模块承接。'):L('You do not have permission to perform this action.','您没有执行此操作的权限。'));return true}
 if(act==='ops-state'){S.st=v;return true}
 return false;
},onRoute(prev,id){capture();E={};notice=null;if(!session&&[P.account,P.overview].includes(id))returnTo=id;if(prev===P.first&&!session)returnTo=P.overview;}
});
document.addEventListener('submit',e=>{if(e.target.dataset.submit){e.preventDefault();submit(e.target.dataset.submit);CF.render()}});
document.addEventListener('input',e=>{const id=e.target.dataset.field;if(!id)return;V[id]=e.target.value;refreshSendButtons();if(id==='newPassword'||id==='confirmPassword'){document.querySelectorAll('.ops-rules').forEach(el=>el.outerHTML=rules());const f=e.target.closest('form');if(f)f.querySelector('button[type=submit]').disabled=busy||!passwordReady()}if(E[id]){delete E[id];e.target.setAttribute('aria-invalid','false');if($(id+'-error'))$(id+'-error').textContent=''}});
document.addEventListener('change',e=>{if(e.target.id==='ops-language'){S.lang=e.target.value;save('hc.ops.language',S.lang);CF.render()}if(e.target.id==='ops-timezone'){S.tz=e.target.value;save('hc.ops.timezone',S.tz);CF.render();CF.toast(L('Time zone updated.','时区已更新。'))}});
['click','keydown','submit'].forEach(type=>document.addEventListener(type,e=>{if(e.isTrusted&&session)lastActivity=Date.now()}));
window.addEventListener('storage',e=>{if(e.key==='hc.ops.invalidate'&&session){expire(msg('Session ended on another tab. Sign in again.','其他标签页已退出登录，请重新登录。'),false);CF.render()}});
CF.opsAuth={can,getIdentity:()=>({email:a.email,name:text(a.name),role:a.role,permissions:permissionGroups().flatMap(g=>g[2].filter(p=>can(p[0])).map(p=>'PM-AL-'+String(p[0]).padStart(2,'0'))),language:S.lang,timezone:S.tz})};
if(!Object.values(P).some(id=>location.hash.split('?')[0]==='#'+R(id)))location.hash='#'+R(P.login);
CF.boot();
setInterval(()=>{refreshSendButtons();if(a.lockUntil&&a.lockUntil<=Date.now()){a.lockUntil=0;a.fail=0;showLock=false;capture();CF.render()}if($('lockText'))$('lockText').textContent=lockCopy();if(captchaUntil&&captchaUntil<=Date.now()){captchaUntil=0;if(S.layer?.key==='ops-captcha'){capture();CF.render()}}if(session){if(Date.now()>=sessionEnd||Date.now()-lastActivity>=1800000){returnTo=S.page===P.account?P.account:P.overview;expire(msg('Your session expired. Please sign in again.','登录已到期，请重新登录。'));CF.render()}else if(sessionEnd-Date.now()<60000&&!warned&&!S.layer){warned=true;capture();CF.openLayer('modal','ops-session')}}},1000);
})(window.CF);
